$axure.loadCurrentPage({
  "url":"物流商介绍.html",
  "generationDate":new Date(1427610287299.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c69062e28c034f6cad328702a11e7164",
    "type":"Axure:Page",
    "name":"物流商介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91dd5f8366f94c27bfcbe0458de050cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":270},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee269d3aad3d41bd800fc82934dfee73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":270},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2b5f3fc78cc4dc880ca75cb6b0f168b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"20px",
            "location":{
              "x":60,
              "y":331},
            "size":{
              "width":740,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c148d4223f2e4e14b19b5c09d719403c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"20px",
                "location":{
                  "x":60,
                  "y":331},
                "size":{
                  "width":740,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"346881f7ace649d79e00a6564832c64e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":650,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"665ddd45730b43f9985d8012a22dc878",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":650,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商介绍/u4.png"}},
{
          "id":"9303895e15f74968924be325e35299f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":78,
              "y":72},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7a7998ec664a61a54f457afc25f82d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":72},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f6847daf7c74988b8870ac243c05c07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":203,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b608669183bf47a8831980db6775d93e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":203,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77fdd735c9fc4429b6480363d105206b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":140},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582eda353510436ca841cc118d556846",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":140},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商介绍/u10.png"}},
{
          "id":"26bc1ed2b322439894235793bf933797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":204},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00e2d93e6a17423a8551658a0b3da69d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":204},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9113572ede246a7a5271bf6869f5e21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":293,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b13b2e4391604280abb76bf0dce21613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd850e846180427da78b71e796e4ad85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":13},
            "size":{
              "width":97,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f017e991c674518933d44279c044e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":13},
                "size":{
                  "width":97,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "91dd5f8366f94c27bfcbe0458de050cc":{
      "scriptId":"u0"},
    "ee269d3aad3d41bd800fc82934dfee73":{
      "scriptId":"u1"},
    "e2b5f3fc78cc4dc880ca75cb6b0f168b":{
      "scriptId":"u2"},
    "c148d4223f2e4e14b19b5c09d719403c":{
      "scriptId":"u3"},
    "346881f7ace649d79e00a6564832c64e":{
      "scriptId":"u4"},
    "665ddd45730b43f9985d8012a22dc878":{
      "scriptId":"u5"},
    "9303895e15f74968924be325e35299f9":{
      "scriptId":"u6"},
    "4f7a7998ec664a61a54f457afc25f82d":{
      "scriptId":"u7"},
    "7f6847daf7c74988b8870ac243c05c07":{
      "scriptId":"u8"},
    "b608669183bf47a8831980db6775d93e":{
      "scriptId":"u9"},
    "77fdd735c9fc4429b6480363d105206b":{
      "scriptId":"u10"},
    "582eda353510436ca841cc118d556846":{
      "scriptId":"u11"},
    "26bc1ed2b322439894235793bf933797":{
      "scriptId":"u12"},
    "00e2d93e6a17423a8551658a0b3da69d":{
      "scriptId":"u13"},
    "f9113572ede246a7a5271bf6869f5e21":{
      "scriptId":"u14"},
    "b13b2e4391604280abb76bf0dce21613":{
      "scriptId":"u15"},
    "dd850e846180427da78b71e796e4ad85":{
      "scriptId":"u16"},
    "1f017e991c674518933d44279c044e89":{
      "scriptId":"u17"}}});