$axure.loadCurrentPage({
  "url":"网点管理.html",
  "generationDate":new Date(1428320975703.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b664b7b0d97c435b9880ded2d80fc3c9",
    "type":"Axure:Page",
    "name":"网点管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1b3ff0b5f7364e46a603b841aa9686a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":78,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e92a191de64120b06daf40fe765850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":78,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1501ddccbc94df2ad5ae45fac30e12c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":750,
              "y":109},
            "size":{
              "width":70,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be98d3a58b1b49af901b2770b1126c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":750,
                  "y":109},
                "size":{
                  "width":70,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点介绍/u37.png"}},
{
          "id":"b89cf7f4bbcb4580ae97214d26b2ba3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":115},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a1732e6e734d39b43285d65adde510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":115},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91957987c36745769c97821727116002",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":73},
            "size":{
              "width":938,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/网点管理/u6_line.png"}},
{
          "id":"ec6e25687e6743309992dd62cb37ccc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":928,
              "y":30},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e2b47b37b64b9b807f5883a618560b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":928,
                  "y":30},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的线路/u19.png"}},
{
          "id":"d77b1ee3032045d3bb651aab4e5a93bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":171,
              "y":109},
            "size":{
              "width":129,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310a91ff594c4f86a8817c0df74ada63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":171,
                  "y":109},
                "size":{
                  "width":129,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点管理/u9.png"}},
{
          "id":"d6634b84bf874d07afdbc35116ed4c7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":337,
              "y":115},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5e83bc43ad24e359fb7ed8347319afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":337,
                  "y":115},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cd7e4f853d84da19128e5dcbef1f0ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":109},
            "size":{
              "width":129,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"786402ef693f4317aee046ce2c20578b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":109},
                "size":{
                  "width":129,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点管理/u9.png"}},
{
          "id":"50ecf284d350451ba8049fd13c157bed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":115},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18d9cdd3350423fa159fd75e1acce83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":115},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a0cb8a65d994d29ada1b26c5bd14039",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":611,
              "y":109},
            "size":{
              "width":129,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"060b6580f9c44dccb2d7d4ac27eb4a56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":611,
                  "y":109},
                "size":{
                  "width":129,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点管理/u9.png"}},
{
          "id":"9c3936039fb3413ba9b62fa7b5b0842f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":172},
            "size":{
              "width":938,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b0f50eb56843e5825ba0106aaf0979",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":169,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ec7ab6ed3314ee39aa514eb28a698d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":169,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u1.png"}},
{
              "id":"1c51ad33c2764463ade4ced2d06bd6fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":40},
                "size":{
                  "width":169,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91c3e1b29fb44c3181ea92b76eda012f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":40},
                    "size":{
                      "width":169,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u9.png"}},
{
              "id":"ed9a57f9b2ee4f90ba6e74ea37fdab70",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":108},
                "size":{
                  "width":169,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"af0311f5530e4527b97e5f786ce3547f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":108},
                    "size":{
                      "width":169,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u17.png"}},
{
              "id":"16ddb16518744454a0e3557ec4e3c6a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":289,
                  "y":0},
                "size":{
                  "width":131,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"633067b4d4a542668f7e3c04c714560e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":289,
                      "y":0},
                    "size":{
                      "width":131,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点管理/u24.png"}},
{
              "id":"ebd9dd4b700d4d46a52680cbaa8cbad0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":289,
                  "y":40},
                "size":{
                  "width":131,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a1a2e1c1bd34458a9026b25fc1e11db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":289,
                      "y":40},
                    "size":{
                      "width":131,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点管理/u38.png"}},
{
              "id":"2f71b51c8db24b7da73b01c52ec94c49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":289,
                  "y":108},
                "size":{
                  "width":131,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c7e0676df6b4a45933abf7122e818e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":289,
                      "y":108},
                    "size":{
                      "width":131,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点管理/u52.png"}},
{
              "id":"b0e9e5a0cb854d42a95d3b09d611aa1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"be28773309b24b2a9a81c0b09be1d914",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u3.png"}},
{
              "id":"94458b06552944c4a975fa1b18f402f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":420,
                  "y":40},
                "size":{
                  "width":150,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7f7b2719eab4467a2a337f88f789acd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":420,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u11.png"}},
{
              "id":"0ee25ebab69541abadd234672c5fb180",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":420,
                  "y":108},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42d7bdedcd254b8b960f819334393efb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":420,
                      "y":108},
                    "size":{
                      "width":150,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u19.png"}},
{
              "id":"ac9a832acbd7480fb9744c5fd972ad7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":838,
                  "y":0},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d293acc0c76a4772a581dee3cbe3f5da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":838,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u32.png"}},
{
              "id":"0bd99486015f4342b46d97b3a51db5f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":838,
                  "y":40},
                "size":{
                  "width":100,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87bcd075230f40488c51c056b6e46cf6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":838,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u44.png"}},
{
              "id":"42a131ec719a4119a101763dd5d5f41f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":838,
                  "y":108},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"259ddf70174b4c0b9de562b0e6e70225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":838,
                      "y":108},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u56.png"}},
{
              "id":"435e0d6c4a7c455a82999c44b0b73d92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5adaab91058424a9f3b108f73e9e1cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u22.png"}},
{
              "id":"7a60978d66c34a35a413d7ccc535ed68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":120,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"423d27fa689941888fc36742a4fe2a99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":120,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u34.png"}},
{
              "id":"ef490a24252d40d183b0e0ca237f525d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"daedc1d62ed74768a1293d4180cc58a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":108},
                    "size":{
                      "width":120,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/我的线路/u46.png"}},
{
              "id":"784fa1e1a3e6420d94b4189c87dcb5e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":570,
                  "y":0},
                "size":{
                  "width":134,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1454b62abbd41dd8e9c0e3562c94a16",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":570,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u5.png"}},
{
              "id":"adf8c54be2d14de5972793c0707df803",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":40},
                "size":{
                  "width":134,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9a1a970be7443efa88d993691e7f758",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":40},
                    "size":{
                      "width":134,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u13.png"}},
{
              "id":"6708cd309b4343858916b8758504738e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":108},
                "size":{
                  "width":134,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a3488aceffd4a988544c897eeb4b708",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":108},
                    "size":{
                      "width":134,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u21.png"}},
{
              "id":"8746a952193d496b94db42ee55e841ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":704,
                  "y":0},
                "size":{
                  "width":134,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28eba454d47b483b8578e8c2d8bcc75c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":704,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u5.png"}},
{
              "id":"9240509c60bf417db18599a7a4e0935c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":704,
                  "y":40},
                "size":{
                  "width":134,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22af57d0bde040f78329ba5e153ff509",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":704,
                      "y":40},
                    "size":{
                      "width":134,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u13.png"}},
{
              "id":"fb9545582ba648b9b6d3aa2c65406695",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":704,
                  "y":108},
                "size":{
                  "width":134,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45e71fd1a1eb4545a9818e920ad1a36d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":704,
                      "y":108},
                    "size":{
                      "width":134,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u21.png"}}]},
{
          "id":"5f83b5e19267432c82110e5a12697bcd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":180},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a93644b2cd8e4b1db7ed9a21235f3b09",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":243},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdea821d428f4122acaa31aa79a4571a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":243},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"df6b3221c2d046e9b9b4f054c3e0caec",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":294},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"772fc8ff14364f7ba2e129a931c2fb6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":294},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"eb788101bd1c4bc7a923e285460949eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":948,
              "y":109},
            "size":{
              "width":70,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ee09eb53f7043a5ad3b4a0383d0cba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":948,
                  "y":109},
                "size":{
                  "width":70,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点介绍/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1b3ff0b5f7364e46a603b841aa9686a5":{
      "scriptId":"u0"},
    "a1e92a191de64120b06daf40fe765850":{
      "scriptId":"u1"},
    "c1501ddccbc94df2ad5ae45fac30e12c":{
      "scriptId":"u2"},
    "be98d3a58b1b49af901b2770b1126c11":{
      "scriptId":"u3"},
    "b89cf7f4bbcb4580ae97214d26b2ba3b":{
      "scriptId":"u4"},
    "98a1732e6e734d39b43285d65adde510":{
      "scriptId":"u5"},
    "91957987c36745769c97821727116002":{
      "scriptId":"u6"},
    "ec6e25687e6743309992dd62cb37ccc3":{
      "scriptId":"u7"},
    "21e2b47b37b64b9b807f5883a618560b":{
      "scriptId":"u8"},
    "d77b1ee3032045d3bb651aab4e5a93bc":{
      "scriptId":"u9"},
    "310a91ff594c4f86a8817c0df74ada63":{
      "scriptId":"u10"},
    "d6634b84bf874d07afdbc35116ed4c7d":{
      "scriptId":"u11"},
    "d5e83bc43ad24e359fb7ed8347319afd":{
      "scriptId":"u12"},
    "2cd7e4f853d84da19128e5dcbef1f0ea":{
      "scriptId":"u13"},
    "786402ef693f4317aee046ce2c20578b":{
      "scriptId":"u14"},
    "50ecf284d350451ba8049fd13c157bed":{
      "scriptId":"u15"},
    "a18d9cdd3350423fa159fd75e1acce83":{
      "scriptId":"u16"},
    "9a0cb8a65d994d29ada1b26c5bd14039":{
      "scriptId":"u17"},
    "060b6580f9c44dccb2d7d4ac27eb4a56":{
      "scriptId":"u18"},
    "9c3936039fb3413ba9b62fa7b5b0842f":{
      "scriptId":"u19"},
    "435e0d6c4a7c455a82999c44b0b73d92":{
      "scriptId":"u20"},
    "b5adaab91058424a9f3b108f73e9e1cb":{
      "scriptId":"u21"},
    "b9b0f50eb56843e5825ba0106aaf0979":{
      "scriptId":"u22"},
    "3ec7ab6ed3314ee39aa514eb28a698d6":{
      "scriptId":"u23"},
    "16ddb16518744454a0e3557ec4e3c6a7":{
      "scriptId":"u24"},
    "633067b4d4a542668f7e3c04c714560e":{
      "scriptId":"u25"},
    "b0e9e5a0cb854d42a95d3b09d611aa1a":{
      "scriptId":"u26"},
    "be28773309b24b2a9a81c0b09be1d914":{
      "scriptId":"u27"},
    "784fa1e1a3e6420d94b4189c87dcb5e3":{
      "scriptId":"u28"},
    "f1454b62abbd41dd8e9c0e3562c94a16":{
      "scriptId":"u29"},
    "8746a952193d496b94db42ee55e841ca":{
      "scriptId":"u30"},
    "28eba454d47b483b8578e8c2d8bcc75c":{
      "scriptId":"u31"},
    "ac9a832acbd7480fb9744c5fd972ad7e":{
      "scriptId":"u32"},
    "d293acc0c76a4772a581dee3cbe3f5da":{
      "scriptId":"u33"},
    "7a60978d66c34a35a413d7ccc535ed68":{
      "scriptId":"u34"},
    "423d27fa689941888fc36742a4fe2a99":{
      "scriptId":"u35"},
    "1c51ad33c2764463ade4ced2d06bd6fd":{
      "scriptId":"u36"},
    "91c3e1b29fb44c3181ea92b76eda012f":{
      "scriptId":"u37"},
    "ebd9dd4b700d4d46a52680cbaa8cbad0":{
      "scriptId":"u38"},
    "4a1a2e1c1bd34458a9026b25fc1e11db":{
      "scriptId":"u39"},
    "94458b06552944c4a975fa1b18f402f4":{
      "scriptId":"u40"},
    "a7f7b2719eab4467a2a337f88f789acd":{
      "scriptId":"u41"},
    "adf8c54be2d14de5972793c0707df803":{
      "scriptId":"u42"},
    "e9a1a970be7443efa88d993691e7f758":{
      "scriptId":"u43"},
    "9240509c60bf417db18599a7a4e0935c":{
      "scriptId":"u44"},
    "22af57d0bde040f78329ba5e153ff509":{
      "scriptId":"u45"},
    "0bd99486015f4342b46d97b3a51db5f1":{
      "scriptId":"u46"},
    "87bcd075230f40488c51c056b6e46cf6":{
      "scriptId":"u47"},
    "ef490a24252d40d183b0e0ca237f525d":{
      "scriptId":"u48"},
    "daedc1d62ed74768a1293d4180cc58a5":{
      "scriptId":"u49"},
    "ed9a57f9b2ee4f90ba6e74ea37fdab70":{
      "scriptId":"u50"},
    "af0311f5530e4527b97e5f786ce3547f":{
      "scriptId":"u51"},
    "2f71b51c8db24b7da73b01c52ec94c49":{
      "scriptId":"u52"},
    "6c7e0676df6b4a45933abf7122e818e0":{
      "scriptId":"u53"},
    "0ee25ebab69541abadd234672c5fb180":{
      "scriptId":"u54"},
    "42d7bdedcd254b8b960f819334393efb":{
      "scriptId":"u55"},
    "6708cd309b4343858916b8758504738e":{
      "scriptId":"u56"},
    "7a3488aceffd4a988544c897eeb4b708":{
      "scriptId":"u57"},
    "fb9545582ba648b9b6d3aa2c65406695":{
      "scriptId":"u58"},
    "45e71fd1a1eb4545a9818e920ad1a36d":{
      "scriptId":"u59"},
    "42a131ec719a4119a101763dd5d5f41f":{
      "scriptId":"u60"},
    "259ddf70174b4c0b9de562b0e6e70225":{
      "scriptId":"u61"},
    "5f83b5e19267432c82110e5a12697bcd":{
      "scriptId":"u62"},
    "a93644b2cd8e4b1db7ed9a21235f3b09":{
      "scriptId":"u63"},
    "bdea821d428f4122acaa31aa79a4571a":{
      "scriptId":"u64"},
    "df6b3221c2d046e9b9b4f054c3e0caec":{
      "scriptId":"u65"},
    "772fc8ff14364f7ba2e129a931c2fb6b":{
      "scriptId":"u66"},
    "eb788101bd1c4bc7a923e285460949eb":{
      "scriptId":"u67"},
    "7ee09eb53f7043a5ad3b4a0383d0cba3":{
      "scriptId":"u68"}}});