$axure.loadCurrentPage({
  "url":"基本信息.html",
  "generationDate":new Date(1428320975876.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"df642c257a9343f6947881aacab5219c",
    "type":"Axure:Page",
    "name":"基本信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9c6a1992b8874ad9a4330811d8739485",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e6549cde3574d00899f3df0be23dc1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cff65bf3e48487d9989275a9f3efd22",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":188,
              "y":66},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ca6161c57849dd930e02ffce2b26e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":188,
                  "y":66},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f548da4a03045db98eb3a6242543b7c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"ad7ae80679634c9cb3c4b99e095868bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":170},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93c48f5ce04b4751b2654d669908922c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":170},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"47f1b8f2d3484d36846532c6f163068f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":177},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a566b1944942858a411d6dc144fe3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":177},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d20c5297b7154812bd82f91dd75a20ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":284},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576a861b8d82465ca0de88765ec2f2f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":284},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2dcb386409f4b51a7f884262919519e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":540},
            "size":{
              "width":140,
              "height":103},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8843913b6b174b999fe973855467b277",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":540},
                "size":{
                  "width":140,
                  "height":103},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u11.png"}},
{
          "id":"cd5ea5a24b5f4832a6b0d4f0a9032438",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":344},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"207d6c74039a4f69b1882e4c3909d9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":344},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7cf54d6a4d84e4495a2a54fe7f23630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":282},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c79ebf83229f4b9e808bb185e533b863",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":282},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"f9e720641a55490cacbad27620762629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":464},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c75ca1603144f049ba67970de169913",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":464},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f92c2709b90c41578440a23095842cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":345},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46884b6177f64743b4f16c23716e8afb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":345},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"c3f4f69eb83a4853a6a685cb8288d5bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":457},
            "size":{
              "width":379,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1384afe5eddf496cb4e50ace2330170a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":457},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u21.png"}},
{
          "id":"0ea3433fb37b4704895b981d8d116bfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":540},
            "size":{
              "width":64,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8400fcee03349ddb42d2158d11412fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":540},
                "size":{
                  "width":64,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac9497f043ca488aa6768c89a1c960b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":660},
            "size":{
              "width":316,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5646cae293543268a06c27094ad2eef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":660},
                "size":{
                  "width":316,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e909bcb17bd455d80fcba9c3b4db52e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":374,
              "y":352},
            "size":{
              "width":297,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f05a8a6406400da7b30cdd2463c444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":352},
                "size":{
                  "width":297,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fde29e62afe54aba84ca5d46610f16cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":374,
              "y":289},
            "size":{
              "width":352,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1fcef782494e10bcc22e8488c3e113",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":289},
                "size":{
                  "width":352,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"438751ad48054da1a9eefea193bdd79f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":374,
              "y":173},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da33005ba3c4d9aa07c093ad1d57dbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":374,
                  "y":173},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc3f19963ecd4892876ba304f51b7e5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":880},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58133928b86547ed800d5747a37d421b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":880},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48297c7db9d04579ae0c6d01ca01a508",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":870},
            "size":{
              "width":379,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcd25228934b4d4ab0874b7325533edc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":870},
                "size":{
                  "width":379,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u35.png"}},
{
          "id":"c4f79917bec54aa4b915e91ba26e630b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1016},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca07f2b59a3a44eda370dcd01b9e11f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1016},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77e43d2099834f0b9e2ec5e1f62945e9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":1016},
            "size":{
              "width":660,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b45bebb6724cea9d8ca597e8dbf88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":1016},
                "size":{
                  "width":660,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u39.png"}},
{
          "id":"f4f27bbfee2d4239809e8293be732379",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":1255},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1350741e77c14a55be21abe019f53923",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":700},
            "size":{
              "width":140,
              "height":103},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13dba3125a244ea18ae32c1c60e77a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":700},
                "size":{
                  "width":140,
                  "height":103},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u11.png"}},
{
          "id":"1b678908d5754f78893f876a162bf88c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":700},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6b302727cf49de8631b6114b371d80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":700},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15ac67ef456e492c9c1dc80ca29f1c56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":151,
              "y":820},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17223b5b25ae4640b467c69af38cc9ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":151,
                  "y":820},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d0cf8121e8f4e149b4d290c4c59000b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":220},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f66ec2e46a5e4a109f05e9b87980246c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":220},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"29c116f69c3d409c8325ef37deb27995",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":40,
              "y":227},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451d9df96c614928b457d398c4e60269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":227},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5abc82c021944abb9690fdb87358356",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF006600,
              "opacity":1},
            "location":{
              "x":40,
              "y":399},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bd13ed89d30422398bfbd1e9b0e701b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF006600,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":399},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae25b1f15c3b4ec0912453c29bf00a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":400},
            "size":{
              "width":60,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f26ec9d0d2a4f16aa248174b9936435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":400},
                "size":{
                  "width":60,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u54.png"}},
{
          "id":"84132b70e83343ebb99836ed556f7b8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":221,
              "y":400},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21327b7f815d4bfdbb6027d45aa1955f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":221,
                  "y":400},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u56.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9c6a1992b8874ad9a4330811d8739485":{
      "scriptId":"u0"},
    "3e6549cde3574d00899f3df0be23dc1a":{
      "scriptId":"u1"},
    "3cff65bf3e48487d9989275a9f3efd22":{
      "scriptId":"u2"},
    "83ca6161c57849dd930e02ffce2b26e2":{
      "scriptId":"u3"},
    "8f548da4a03045db98eb3a6242543b7c":{
      "scriptId":"u4"},
    "ad7ae80679634c9cb3c4b99e095868bb":{
      "scriptId":"u5"},
    "93c48f5ce04b4751b2654d669908922c":{
      "scriptId":"u6"},
    "47f1b8f2d3484d36846532c6f163068f":{
      "scriptId":"u7"},
    "a9a566b1944942858a411d6dc144fe3c":{
      "scriptId":"u8"},
    "d20c5297b7154812bd82f91dd75a20ac":{
      "scriptId":"u9"},
    "576a861b8d82465ca0de88765ec2f2f4":{
      "scriptId":"u10"},
    "d2dcb386409f4b51a7f884262919519e":{
      "scriptId":"u11"},
    "8843913b6b174b999fe973855467b277":{
      "scriptId":"u12"},
    "cd5ea5a24b5f4832a6b0d4f0a9032438":{
      "scriptId":"u13"},
    "207d6c74039a4f69b1882e4c3909d9da":{
      "scriptId":"u14"},
    "f7cf54d6a4d84e4495a2a54fe7f23630":{
      "scriptId":"u15"},
    "c79ebf83229f4b9e808bb185e533b863":{
      "scriptId":"u16"},
    "f9e720641a55490cacbad27620762629":{
      "scriptId":"u17"},
    "9c75ca1603144f049ba67970de169913":{
      "scriptId":"u18"},
    "f92c2709b90c41578440a23095842cbd":{
      "scriptId":"u19"},
    "46884b6177f64743b4f16c23716e8afb":{
      "scriptId":"u20"},
    "c3f4f69eb83a4853a6a685cb8288d5bb":{
      "scriptId":"u21"},
    "1384afe5eddf496cb4e50ace2330170a":{
      "scriptId":"u22"},
    "0ea3433fb37b4704895b981d8d116bfb":{
      "scriptId":"u23"},
    "f8400fcee03349ddb42d2158d11412fd":{
      "scriptId":"u24"},
    "ac9497f043ca488aa6768c89a1c960b1":{
      "scriptId":"u25"},
    "e5646cae293543268a06c27094ad2eef":{
      "scriptId":"u26"},
    "9e909bcb17bd455d80fcba9c3b4db52e":{
      "scriptId":"u27"},
    "16f05a8a6406400da7b30cdd2463c444":{
      "scriptId":"u28"},
    "fde29e62afe54aba84ca5d46610f16cd":{
      "scriptId":"u29"},
    "2c1fcef782494e10bcc22e8488c3e113":{
      "scriptId":"u30"},
    "438751ad48054da1a9eefea193bdd79f":{
      "scriptId":"u31"},
    "3da33005ba3c4d9aa07c093ad1d57dbe":{
      "scriptId":"u32"},
    "fc3f19963ecd4892876ba304f51b7e5b":{
      "scriptId":"u33"},
    "58133928b86547ed800d5747a37d421b":{
      "scriptId":"u34"},
    "48297c7db9d04579ae0c6d01ca01a508":{
      "scriptId":"u35"},
    "bcd25228934b4d4ab0874b7325533edc":{
      "scriptId":"u36"},
    "c4f79917bec54aa4b915e91ba26e630b":{
      "scriptId":"u37"},
    "ca07f2b59a3a44eda370dcd01b9e11f8":{
      "scriptId":"u38"},
    "77e43d2099834f0b9e2ec5e1f62945e9":{
      "scriptId":"u39"},
    "c5b45bebb6724cea9d8ca597e8dbf88d":{
      "scriptId":"u40"},
    "f4f27bbfee2d4239809e8293be732379":{
      "scriptId":"u41"},
    "1350741e77c14a55be21abe019f53923":{
      "scriptId":"u42"},
    "13dba3125a244ea18ae32c1c60e77a18":{
      "scriptId":"u43"},
    "1b678908d5754f78893f876a162bf88c":{
      "scriptId":"u44"},
    "bc6b302727cf49de8631b6114b371d80":{
      "scriptId":"u45"},
    "15ac67ef456e492c9c1dc80ca29f1c56":{
      "scriptId":"u46"},
    "17223b5b25ae4640b467c69af38cc9ce":{
      "scriptId":"u47"},
    "6d0cf8121e8f4e149b4d290c4c59000b":{
      "scriptId":"u48"},
    "f66ec2e46a5e4a109f05e9b87980246c":{
      "scriptId":"u49"},
    "29c116f69c3d409c8325ef37deb27995":{
      "scriptId":"u50"},
    "451d9df96c614928b457d398c4e60269":{
      "scriptId":"u51"},
    "c5abc82c021944abb9690fdb87358356":{
      "scriptId":"u52"},
    "1bd13ed89d30422398bfbd1e9b0e701b":{
      "scriptId":"u53"},
    "ae25b1f15c3b4ec0912453c29bf00a91":{
      "scriptId":"u54"},
    "5f26ec9d0d2a4f16aa248174b9936435":{
      "scriptId":"u55"},
    "84132b70e83343ebb99836ed556f7b8d":{
      "scriptId":"u56"},
    "21327b7f815d4bfdbb6027d45aa1955f":{
      "scriptId":"u57"}}});