$axure.loadCurrentPage({
  "url":"网店介绍.html",
  "generationDate":new Date(1427530828696.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2c8146ef44f5487ea3349cfff254b711",
    "type":"Axure:Page",
    "name":"网店介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3d8ce47260a4874a795ceaa84f89e2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":53},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e848c262ca54ea3b994c99570c32db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":53},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1a8e50b0cb544d3816348d24d46a942",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":122},
            "size":{
              "width":653,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dc5b11d8c84447a3806024d9d0c8ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":169,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcc263ac49764dfbb1d674a086bbc6d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":169,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u3.png"}},
{
              "id":"9efacfe95d1b4688b41601a82a0dbcda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":169,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ff73fe9ff1a4caea170864cfb926611",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":169,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u11.png"}},
{
              "id":"c83626b6e73c4f20bc393bb7b5611b18",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":169,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5f1ad06d5114abe8327149808ffa763",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":108},
                    "size":{
                      "width":169,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查找列表/u33.png"}},
{
              "id":"ff78b96bca334341b67f49c667148434",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":169,
                  "y":0},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd009deec664405287a9b61c44d1f3c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":169,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u5.png"}},
{
              "id":"cf7e7d60bbc9441297cfba1e5bf388a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":40},
                "size":{
                  "width":150,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"728d37b354054c5784cbf0b1726a8a0e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u13.png"}},
{
              "id":"ab6e37dc72e54ac2a825d71ab99eb761",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":108},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c9e0eec51ea74963b10badc78fc392c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":108},
                    "size":{
                      "width":150,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u21.png"}},
{
              "id":"74e1fc99c8ff4fab92fd2a52f6391593",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":453,
                  "y":0},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab5bec326f44492ca6f9da19b7182afd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u9.png"}},
{
              "id":"08cf0bdb3e6b4fbb8714b21e517a2e96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":40},
                "size":{
                  "width":200,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec9dacbae35f4333b3d7d6a43392aeb8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":453,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u17.png"}},
{
              "id":"145d3e1600044df7bc8190a57b4da526",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":108},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"507483df38ae46cc88191630d23a7889",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":453,
                      "y":108},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u25.png"}},
{
              "id":"b33998a9dc364060a322942466686d0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":319,
                  "y":0},
                "size":{
                  "width":134,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a4627b385ef841f4afda7d2615543ebd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":319,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u7.png"}},
{
              "id":"827edea6837647f099b5d24129a1761a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":40},
                "size":{
                  "width":134,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6494e04b202e4d28ae405f935f37f7a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":40},
                    "size":{
                      "width":134,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u15.png"}},
{
              "id":"e39b0fc901394d948a65ea2e9fbfd833",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":108},
                "size":{
                  "width":134,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90e65ffb8a3c49288cd9e8b49d96f2ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":108},
                    "size":{
                      "width":134,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网店介绍/u23.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "f3d8ce47260a4874a795ceaa84f89e2d":{
      "scriptId":"u0"},
    "2e848c262ca54ea3b994c99570c32db4":{
      "scriptId":"u1"},
    "a1a8e50b0cb544d3816348d24d46a942":{
      "scriptId":"u2"},
    "90dc5b11d8c84447a3806024d9d0c8ac":{
      "scriptId":"u3"},
    "dcc263ac49764dfbb1d674a086bbc6d1":{
      "scriptId":"u4"},
    "ff78b96bca334341b67f49c667148434":{
      "scriptId":"u5"},
    "fd009deec664405287a9b61c44d1f3c8":{
      "scriptId":"u6"},
    "b33998a9dc364060a322942466686d0d":{
      "scriptId":"u7"},
    "a4627b385ef841f4afda7d2615543ebd":{
      "scriptId":"u8"},
    "74e1fc99c8ff4fab92fd2a52f6391593":{
      "scriptId":"u9"},
    "ab5bec326f44492ca6f9da19b7182afd":{
      "scriptId":"u10"},
    "9efacfe95d1b4688b41601a82a0dbcda":{
      "scriptId":"u11"},
    "5ff73fe9ff1a4caea170864cfb926611":{
      "scriptId":"u12"},
    "cf7e7d60bbc9441297cfba1e5bf388a5":{
      "scriptId":"u13"},
    "728d37b354054c5784cbf0b1726a8a0e":{
      "scriptId":"u14"},
    "827edea6837647f099b5d24129a1761a":{
      "scriptId":"u15"},
    "6494e04b202e4d28ae405f935f37f7a8":{
      "scriptId":"u16"},
    "08cf0bdb3e6b4fbb8714b21e517a2e96":{
      "scriptId":"u17"},
    "ec9dacbae35f4333b3d7d6a43392aeb8":{
      "scriptId":"u18"},
    "c83626b6e73c4f20bc393bb7b5611b18":{
      "scriptId":"u19"},
    "d5f1ad06d5114abe8327149808ffa763":{
      "scriptId":"u20"},
    "ab6e37dc72e54ac2a825d71ab99eb761":{
      "scriptId":"u21"},
    "c9e0eec51ea74963b10badc78fc392c2":{
      "scriptId":"u22"},
    "e39b0fc901394d948a65ea2e9fbfd833":{
      "scriptId":"u23"},
    "90e65ffb8a3c49288cd9e8b49d96f2ea":{
      "scriptId":"u24"},
    "145d3e1600044df7bc8190a57b4da526":{
      "scriptId":"u25"},
    "507483df38ae46cc88191630d23a7889":{
      "scriptId":"u26"}}});