$axure.loadCurrentPage({
  "url":"添加线路.html",
  "generationDate":new Date(1428320975591.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"18a1157de40943819545f2ad968a43a2",
    "type":"Axure:Page",
    "name":"添加线路",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dcd0e072ce247a8be31d1330a0fbc06",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":78,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db26544d3f0043e3b413035399ea2c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":78,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8d7cb781fd84a24a290f926b6b6b4f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":150},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"270c4f426b40444b8a3ac76dbc9fe76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":150},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cfca0d9577f49d7b84d0721a6215718",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":189},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa76041b72a54882ba5221a946067014",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":189},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fdc259bab79463da15c51c84eb105ec",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":183},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"56ffaf0b495946c8a1993bcc3e73d1d9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":183},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"093eebfb2ad84d3e9a3b2c6147bef7dc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":439,
              "y":183},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7f2697bd261e47978598522194c6fcfe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":73},
            "size":{
              "width":550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的线路/u17_line.png"}},
{
          "id":"20df06ddaea64456a03dbe76ec026239",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":460},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"25598a69c5b7461e8b487bc87705946c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":240},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cba6f57905c646b1b77ae7a3d1fc8f69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":240},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"9b4f4a40860a4e3db2a51c9d044d99a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":245},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5de07f3b70244dd5aa2ed2546a85e582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":245},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27406e2d469f411e8ee6db4a981a4297",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":245},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89e69e4eccc54b3f8a275c8444931293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":245},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af180d0d40054387bd46cc54ae269580",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":290},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"088dcf59e32447ca83cc42588b118f6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":290},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7669d2bede494817ac8872b1bc18c2a9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":295},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e71717c80149d6b012ee0a1925181e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b062c3132544556a53fc2101ff5061e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u20.png"}},
{
              "id":"15ec8f4cf5f84233aca8542af4026232",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"405a2d4fb63444c297f83add6055b2b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"26d4220573ac4650957df9b798073b2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c470f12270e24fe3ba43804aa4812226",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"5b3dc51f5aa84a92b6a5e6ecb15ac829",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7652e2b44dd44d97a5e848bcd3240aed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u22.png"}},
{
              "id":"a794e095aeef46be9aadd31be37463fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2781dfc5cf0d4f8085b4f80de1e4c90d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u26.png"}},
{
              "id":"36498f8e0b9b42958dbc229d1239b4e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"204c22e066f84a6eb9de707140c108b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册/u5.png"}}]},
{
          "id":"9547ca6352a24bcf84717b5901fcd370",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":327},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab72fa862a9c4ab1a1c1afd0c0d30046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":327},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"447ed0aeff7b4f8088b5f4bd36863c67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":332},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbc81053d7a948e9b2fe2fe66714bde9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":332},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c313f82ffba647b09558f794fbc93267",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":356},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0b5b3efcc3244d0b1a0a3764a6fe713",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":356},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"21af6c78ccd149d8a0f1dfacb6c25efa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":362},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb44864127be4c2fbc24055b9dac04ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":381,
                  "y":362},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"765e83d981bf4168ae96e4e535a51f3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":409},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb109c7962a0463eb80892dbf2eab274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":409},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"d549edd531ed469180e413f385fa198a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":414},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43dc25764da34fd583a6cf05b26607ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":414},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d1487f0a3134f15b37d10e3bda6d40d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":414},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94201468d03a4c36a624e3bed55cd227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":414},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5697c95076564bb3b9c45fca1311c542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":150},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8c3dc4fa57942789e2ae1ed966bd3bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":150},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ab27971455c46a8a0e5bad91dd17498",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":104},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40565610aa641f3918d2a8770b19895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":104},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bce3cdae9654b9fa7a7507ab5478c55",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":104},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5de8f1efa3be4b3d8b003aa22bac9169",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":150},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1554d891f3914d1db92ae9811ebb837e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":150},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91d5e95e714e41b786201c3f8d3a4898",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":274},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f429ae1caf8d4b248c9f00bb6c0202fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":274},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82899e62f39e4cfc8764526ea3a54e1b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":268},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"af816fffd0834fde91a2c87712ce7c5d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":268},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4515c66ca9844ddc9a5be89cab10e0a3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":268},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f97416cf50ef49f9bb27cd34e3492a3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":885,
              "y":607.5},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dffe45b2144f461882563f86fcabd9c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":312.5},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d93cf8f861b43eaba579bbc9a6ee041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":312.5},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"cc585b1d765e4904b2d4d6bece82928d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":318},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c21f2a2dfd647d190764664a8bc67fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":318},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de4700bed34a42b584553b97e89e5ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1001,
              "y":318},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7ef613512e5408a8009787dd79ca3e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1001,
                  "y":318},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ccefa4ef4c44690af3b3510f875ea9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":362},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c044ff72d26543f7a06a68bfccd20047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":362},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b3ae6d92548425dbadc89424daf3a4a",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":367.5},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12478066e3ef458a813830a752308d3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":367.5},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"cd14efde9a1e429bb3873736dfb2e52e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":403.5},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96596e7d436e4be9bc525751af539137",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4615d891ad4e4045b03d844c72d205fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u20.png"}},
{
              "id":"96c38f4fc207417c884d8c557d9354c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfd13d3d678e43cfa8337c10d9423f69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"618ae60af7124c22b3801c5cd6ab7e7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ac350b4316145e59d8aed45dfbe253c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"4fe166b91c984597ae56ca4f32cf69b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96d86d288cce45beb0ce8704fb2f7c6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u22.png"}},
{
              "id":"b21f6bf97bd74454a7adbafaa53f5dad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fc45ff42a00409f8e6c6390df405061",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u26.png"}},
{
              "id":"8fd62e6c825348b0af074464b1a39e67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19770edadb834dbdbdfcefca65b3cbd3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册/u5.png"}}]},
{
          "id":"fd3ba3ed9c324d48b3df3e71af81a54f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1001,
              "y":435.5},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"805201734ed241b6ba0bb99ae8d99e7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1001,
                  "y":435.5},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"47c48b8b22b84d02b7edc17344fb61fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1112,
              "y":440},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dcbbfd6d342475fb7cfa66672a2655b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1112,
                  "y":440},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d4c80796e184788b3217b21cdda0ba1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1001,
              "y":464.5},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf661436718b48cbb52495aa371c8d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1001,
                  "y":464.5},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"a25585b23eee403291f109a2371ad88b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1112,
              "y":470},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"951e44f710024d358dfd44260ff660e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1112,
                  "y":470},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79d4e5ae20ab4528acd6ded293ecbdf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":527.5},
            "size":{
              "width":101,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd82cbf985c74671b5a6369ad91a57f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":527.5},
                "size":{
                  "width":101,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u11.png"}},
{
          "id":"6ea88a9c19b74c35aa4eb4b802bde63d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":532},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff000f9b85e24a798df0ef43185482dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":532},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"441fc00b71ac468f8144e89ed69a7592",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1001,
              "y":532},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06bc1b3f8fc1447ab4ea74c9b93049cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1001,
                  "y":532},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2b68477bc854ed188014486ee422192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":150},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52a7404957b74a489b86b87a8ac60b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":150},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c27dcc2bc7245f8aaaed193c54271a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":104},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c108c0b8657245248ec899436f519d17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":104},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d004b3a1fd8d4e21826e4f9f1980d6d2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":104},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2d5fa612d8d849448c22743f0fdb0eb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":809,
              "y":195},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9aa0b4b569040dfa1f74987682d3823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":809,
                  "y":195},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff63d9499c864af6a3836dc97384665a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":189},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e307057f2ad14eaab07494a1ea797d21",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":189},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"054fb17dab58411686fce0a64b952d81",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":189},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"49012311a12a426994387e16e6d99049",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":229},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"2eab0e0c01ec4dfd919ae13477f65e00",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":229},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a3fe357f38294577a583c895425bb725",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":229},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"4a91f2b5d67e4dc3b2e5e7ed7cffd388",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":1300,
              "y":229},
            "size":{
              "width":40,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c22403152e14f28aa1159eaac7ca2e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":1300,
                  "y":229},
                "size":{
                  "width":40,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u109.png"}},
{
          "id":"e7a872afcadf4ade89105e2169418d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":1350,
              "y":229},
            "size":{
              "width":40,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4eb03d4a63445db1225de7e5257bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":1350,
                  "y":229},
                "size":{
                  "width":40,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u109.png"}},
{
          "id":"a5043053cbdb4545a9dd2997d56b2b46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":1300,
              "y":189},
            "size":{
              "width":40,
              "height":22},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"038a66a7924e465cb76177a72c5e3c7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":1300,
                  "y":189},
                "size":{
                  "width":40,
                  "height":22},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加线路/u109.png"}},
{
          "id":"df23e2e0cb4f4623ae975be0e849ed2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1408,
              "y":235},
            "size":{
              "width":177,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75276999632848d3a734b2ad3ca913da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1408,
                  "y":235},
                "size":{
                  "width":177,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75b5604a6c634ef4b7c5ebb002c04288",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":809,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa1c1b70f004ec4a1e546b3b92fb9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":809,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bcee9e39f7f48b5982ce2ea33c9eddf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":811,
              "y":73},
            "size":{
              "width":550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的线路/u17_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9dcd0e072ce247a8be31d1330a0fbc06":{
      "scriptId":"u0"},
    "db26544d3f0043e3b413035399ea2c9c":{
      "scriptId":"u1"},
    "e8d7cb781fd84a24a290f926b6b6b4f0":{
      "scriptId":"u2"},
    "270c4f426b40444b8a3ac76dbc9fe76b":{
      "scriptId":"u3"},
    "4cfca0d9577f49d7b84d0721a6215718":{
      "scriptId":"u4"},
    "aa76041b72a54882ba5221a946067014":{
      "scriptId":"u5"},
    "2fdc259bab79463da15c51c84eb105ec":{
      "scriptId":"u6"},
    "56ffaf0b495946c8a1993bcc3e73d1d9":{
      "scriptId":"u7"},
    "093eebfb2ad84d3e9a3b2c6147bef7dc":{
      "scriptId":"u8"},
    "7f2697bd261e47978598522194c6fcfe":{
      "scriptId":"u9"},
    "20df06ddaea64456a03dbe76ec026239":{
      "scriptId":"u10"},
    "25598a69c5b7461e8b487bc87705946c":{
      "scriptId":"u11"},
    "cba6f57905c646b1b77ae7a3d1fc8f69":{
      "scriptId":"u12"},
    "9b4f4a40860a4e3db2a51c9d044d99a2":{
      "scriptId":"u13"},
    "5de07f3b70244dd5aa2ed2546a85e582":{
      "scriptId":"u14"},
    "27406e2d469f411e8ee6db4a981a4297":{
      "scriptId":"u15"},
    "89e69e4eccc54b3f8a275c8444931293":{
      "scriptId":"u16"},
    "af180d0d40054387bd46cc54ae269580":{
      "scriptId":"u17"},
    "088dcf59e32447ca83cc42588b118f6a":{
      "scriptId":"u18"},
    "7669d2bede494817ac8872b1bc18c2a9":{
      "scriptId":"u19"},
    "91e71717c80149d6b012ee0a1925181e":{
      "scriptId":"u20"},
    "7b062c3132544556a53fc2101ff5061e":{
      "scriptId":"u21"},
    "5b3dc51f5aa84a92b6a5e6ecb15ac829":{
      "scriptId":"u22"},
    "7652e2b44dd44d97a5e848bcd3240aed":{
      "scriptId":"u23"},
    "15ec8f4cf5f84233aca8542af4026232":{
      "scriptId":"u24"},
    "405a2d4fb63444c297f83add6055b2b3":{
      "scriptId":"u25"},
    "a794e095aeef46be9aadd31be37463fb":{
      "scriptId":"u26"},
    "2781dfc5cf0d4f8085b4f80de1e4c90d":{
      "scriptId":"u27"},
    "26d4220573ac4650957df9b798073b2c":{
      "scriptId":"u28"},
    "c470f12270e24fe3ba43804aa4812226":{
      "scriptId":"u29"},
    "36498f8e0b9b42958dbc229d1239b4e1":{
      "scriptId":"u30"},
    "204c22e066f84a6eb9de707140c108b9":{
      "scriptId":"u31"},
    "9547ca6352a24bcf84717b5901fcd370":{
      "scriptId":"u32"},
    "ab72fa862a9c4ab1a1c1afd0c0d30046":{
      "scriptId":"u33"},
    "447ed0aeff7b4f8088b5f4bd36863c67":{
      "scriptId":"u34"},
    "cbc81053d7a948e9b2fe2fe66714bde9":{
      "scriptId":"u35"},
    "c313f82ffba647b09558f794fbc93267":{
      "scriptId":"u36"},
    "b0b5b3efcc3244d0b1a0a3764a6fe713":{
      "scriptId":"u37"},
    "21af6c78ccd149d8a0f1dfacb6c25efa":{
      "scriptId":"u38"},
    "eb44864127be4c2fbc24055b9dac04ac":{
      "scriptId":"u39"},
    "765e83d981bf4168ae96e4e535a51f3e":{
      "scriptId":"u40"},
    "fb109c7962a0463eb80892dbf2eab274":{
      "scriptId":"u41"},
    "d549edd531ed469180e413f385fa198a":{
      "scriptId":"u42"},
    "43dc25764da34fd583a6cf05b26607ab":{
      "scriptId":"u43"},
    "0d1487f0a3134f15b37d10e3bda6d40d":{
      "scriptId":"u44"},
    "94201468d03a4c36a624e3bed55cd227":{
      "scriptId":"u45"},
    "5697c95076564bb3b9c45fca1311c542":{
      "scriptId":"u46"},
    "f8c3dc4fa57942789e2ae1ed966bd3bd":{
      "scriptId":"u47"},
    "4ab27971455c46a8a0e5bad91dd17498":{
      "scriptId":"u48"},
    "c40565610aa641f3918d2a8770b19895":{
      "scriptId":"u49"},
    "7bce3cdae9654b9fa7a7507ab5478c55":{
      "scriptId":"u50"},
    "5de8f1efa3be4b3d8b003aa22bac9169":{
      "scriptId":"u51"},
    "1554d891f3914d1db92ae9811ebb837e":{
      "scriptId":"u52"},
    "91d5e95e714e41b786201c3f8d3a4898":{
      "scriptId":"u53"},
    "f429ae1caf8d4b248c9f00bb6c0202fc":{
      "scriptId":"u54"},
    "82899e62f39e4cfc8764526ea3a54e1b":{
      "scriptId":"u55"},
    "af816fffd0834fde91a2c87712ce7c5d":{
      "scriptId":"u56"},
    "4515c66ca9844ddc9a5be89cab10e0a3":{
      "scriptId":"u57"},
    "f97416cf50ef49f9bb27cd34e3492a3d":{
      "scriptId":"u58"},
    "dffe45b2144f461882563f86fcabd9c0":{
      "scriptId":"u59"},
    "8d93cf8f861b43eaba579bbc9a6ee041":{
      "scriptId":"u60"},
    "cc585b1d765e4904b2d4d6bece82928d":{
      "scriptId":"u61"},
    "9c21f2a2dfd647d190764664a8bc67fa":{
      "scriptId":"u62"},
    "de4700bed34a42b584553b97e89e5ace":{
      "scriptId":"u63"},
    "a7ef613512e5408a8009787dd79ca3e8":{
      "scriptId":"u64"},
    "1ccefa4ef4c44690af3b3510f875ea9a":{
      "scriptId":"u65"},
    "c044ff72d26543f7a06a68bfccd20047":{
      "scriptId":"u66"},
    "7b3ae6d92548425dbadc89424daf3a4a":{
      "scriptId":"u67"},
    "12478066e3ef458a813830a752308d3e":{
      "scriptId":"u68"},
    "cd14efde9a1e429bb3873736dfb2e52e":{
      "scriptId":"u69"},
    "96596e7d436e4be9bc525751af539137":{
      "scriptId":"u70"},
    "4615d891ad4e4045b03d844c72d205fa":{
      "scriptId":"u71"},
    "4fe166b91c984597ae56ca4f32cf69b2":{
      "scriptId":"u72"},
    "96d86d288cce45beb0ce8704fb2f7c6d":{
      "scriptId":"u73"},
    "96c38f4fc207417c884d8c557d9354c9":{
      "scriptId":"u74"},
    "dfd13d3d678e43cfa8337c10d9423f69":{
      "scriptId":"u75"},
    "b21f6bf97bd74454a7adbafaa53f5dad":{
      "scriptId":"u76"},
    "9fc45ff42a00409f8e6c6390df405061":{
      "scriptId":"u77"},
    "618ae60af7124c22b3801c5cd6ab7e7e":{
      "scriptId":"u78"},
    "6ac350b4316145e59d8aed45dfbe253c":{
      "scriptId":"u79"},
    "8fd62e6c825348b0af074464b1a39e67":{
      "scriptId":"u80"},
    "19770edadb834dbdbdfcefca65b3cbd3":{
      "scriptId":"u81"},
    "fd3ba3ed9c324d48b3df3e71af81a54f":{
      "scriptId":"u82"},
    "805201734ed241b6ba0bb99ae8d99e7f":{
      "scriptId":"u83"},
    "47c48b8b22b84d02b7edc17344fb61fb":{
      "scriptId":"u84"},
    "7dcbbfd6d342475fb7cfa66672a2655b":{
      "scriptId":"u85"},
    "9d4c80796e184788b3217b21cdda0ba1":{
      "scriptId":"u86"},
    "cf661436718b48cbb52495aa371c8d25":{
      "scriptId":"u87"},
    "a25585b23eee403291f109a2371ad88b":{
      "scriptId":"u88"},
    "951e44f710024d358dfd44260ff660e6":{
      "scriptId":"u89"},
    "79d4e5ae20ab4528acd6ded293ecbdf2":{
      "scriptId":"u90"},
    "dd82cbf985c74671b5a6369ad91a57f1":{
      "scriptId":"u91"},
    "6ea88a9c19b74c35aa4eb4b802bde63d":{
      "scriptId":"u92"},
    "ff000f9b85e24a798df0ef43185482dc":{
      "scriptId":"u93"},
    "441fc00b71ac468f8144e89ed69a7592":{
      "scriptId":"u94"},
    "06bc1b3f8fc1447ab4ea74c9b93049cc":{
      "scriptId":"u95"},
    "c2b68477bc854ed188014486ee422192":{
      "scriptId":"u96"},
    "52a7404957b74a489b86b87a8ac60b98":{
      "scriptId":"u97"},
    "5c27dcc2bc7245f8aaaed193c54271a4":{
      "scriptId":"u98"},
    "c108c0b8657245248ec899436f519d17":{
      "scriptId":"u99"},
    "d004b3a1fd8d4e21826e4f9f1980d6d2":{
      "scriptId":"u100"},
    "2d5fa612d8d849448c22743f0fdb0eb1":{
      "scriptId":"u101"},
    "e9aa0b4b569040dfa1f74987682d3823":{
      "scriptId":"u102"},
    "ff63d9499c864af6a3836dc97384665a":{
      "scriptId":"u103"},
    "e307057f2ad14eaab07494a1ea797d21":{
      "scriptId":"u104"},
    "054fb17dab58411686fce0a64b952d81":{
      "scriptId":"u105"},
    "49012311a12a426994387e16e6d99049":{
      "scriptId":"u106"},
    "2eab0e0c01ec4dfd919ae13477f65e00":{
      "scriptId":"u107"},
    "a3fe357f38294577a583c895425bb725":{
      "scriptId":"u108"},
    "4a91f2b5d67e4dc3b2e5e7ed7cffd388":{
      "scriptId":"u109"},
    "9c22403152e14f28aa1159eaac7ca2e3":{
      "scriptId":"u110"},
    "e7a872afcadf4ade89105e2169418d3d":{
      "scriptId":"u111"},
    "ec4eb03d4a63445db1225de7e5257bf9":{
      "scriptId":"u112"},
    "a5043053cbdb4545a9dd2997d56b2b46":{
      "scriptId":"u113"},
    "038a66a7924e465cb76177a72c5e3c7b":{
      "scriptId":"u114"},
    "df23e2e0cb4f4623ae975be0e849ed2c":{
      "scriptId":"u115"},
    "75276999632848d3a734b2ad3ca913da":{
      "scriptId":"u116"},
    "75b5604a6c634ef4b7c5ebb002c04288":{
      "scriptId":"u117"},
    "bfa1c1b70f004ec4a1e546b3b92fb9be":{
      "scriptId":"u118"},
    "7bcee9e39f7f48b5982ce2ea33c9eddf":{
      "scriptId":"u119"}}});