$axure.loadCurrentPage({
  "url":"添加车辆.html",
  "generationDate":new Date(1428320979033.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bfbc6796092341008eb09f9cd7a96e09",
    "type":"Axure:Page",
    "name":"添加车辆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6afd966a135f46f4871602553196f2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a186e6ccfce485680de281931135f0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dda8b6f9f60424f95df44816ec07fca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"7be110e31c9c4e01b4d32f2589ac7034",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":40,
              "y":184},
            "size":{
              "width":92,
              "height":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb324b14a71b42bc8c6e28c2a27f349f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":40,
                  "y":184},
                "size":{
                  "width":92,
                  "height":256}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e04ac3088a8e42e6832d6af5b8fb186c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":191},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aae4686b55444cabcfafc18893f7346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":191},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"f882e6bbb9d5467180d5132cd3da10ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":285},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb377f6af5dc48db8fc2cb8e50b1b50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":285},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"50feed206b414b3189057993f88f9150",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":242},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bd3f55ad5c9e470ebee80c5e25a3fd89",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":415},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bed8a5fb556042ddbf57590e9bde40c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":340},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f149a769ed8b49b1bc1b3ebca02aa147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":340},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6afd966a135f46f4871602553196f2e9":{
      "scriptId":"u0"},
    "3a186e6ccfce485680de281931135f0b":{
      "scriptId":"u1"},
    "3dda8b6f9f60424f95df44816ec07fca":{
      "scriptId":"u2"},
    "7be110e31c9c4e01b4d32f2589ac7034":{
      "scriptId":"u3"},
    "cb324b14a71b42bc8c6e28c2a27f349f":{
      "scriptId":"u4"},
    "e04ac3088a8e42e6832d6af5b8fb186c":{
      "scriptId":"u5"},
    "6aae4686b55444cabcfafc18893f7346":{
      "scriptId":"u6"},
    "f882e6bbb9d5467180d5132cd3da10ca":{
      "scriptId":"u7"},
    "bb377f6af5dc48db8fc2cb8e50b1b50c":{
      "scriptId":"u8"},
    "50feed206b414b3189057993f88f9150":{
      "scriptId":"u9"},
    "bd3f55ad5c9e470ebee80c5e25a3fd89":{
      "scriptId":"u10"},
    "bed8a5fb556042ddbf57590e9bde40c2":{
      "scriptId":"u11"},
    "f149a769ed8b49b1bc1b3ebca02aa147":{
      "scriptId":"u12"}}});