$axure.loadCurrentPage({
  "url":"产品服务说明.html",
  "generationDate":new Date(1428320975897.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b86a8521cf942fd9c415818f5c081dc",
    "type":"Axure:Page",
    "name":"产品服务说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"683abda0cf1d4a74b0a8e4db82169184",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f49cfbf1901b4a65ac599891f0b9166e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38c20bd87a364e72af0d356098cf3ebf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":188,
              "y":66},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f292171d6e4209b238fa6882d4372c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":188,
                  "y":66},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d940505a0b274362a4477fcfbd1f1efa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"566dd28fdf504a7d9c298f36edde4226",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":210},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf4087b709674d4f884993b5c095ae04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":210},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91b4f549fd6646979c8804e3c8d0ca40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":210},
            "size":{
              "width":660,
              "height":214}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2bff4713a9450287ef333c5b992862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":210},
                "size":{
                  "width":660,
                  "height":214}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u39.png"}},
{
          "id":"31bcb1d479bc487aaea581b39b581192",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":449},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "683abda0cf1d4a74b0a8e4db82169184":{
      "scriptId":"u0"},
    "f49cfbf1901b4a65ac599891f0b9166e":{
      "scriptId":"u1"},
    "38c20bd87a364e72af0d356098cf3ebf":{
      "scriptId":"u2"},
    "c8f292171d6e4209b238fa6882d4372c":{
      "scriptId":"u3"},
    "d940505a0b274362a4477fcfbd1f1efa":{
      "scriptId":"u4"},
    "566dd28fdf504a7d9c298f36edde4226":{
      "scriptId":"u5"},
    "cf4087b709674d4f884993b5c095ae04":{
      "scriptId":"u6"},
    "91b4f549fd6646979c8804e3c8d0ca40":{
      "scriptId":"u7"},
    "6f2bff4713a9450287ef333c5b992862":{
      "scriptId":"u8"},
    "31bcb1d479bc487aaea581b39b581192":{
      "scriptId":"u9"}}});