$axure.loadCurrentPage({
  "url":"默认页_1.html",
  "generationDate":new Date(1428320976013.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"743eb4992e9c4804abc751c5ee439e6a",
    "type":"Axure:Page",
    "name":"默认页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"37562ccb0005488a9d54e9b40cef9684",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":40,
              "y":134},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfbe46b8e58947d9962324a6f85746c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":40,
                  "y":134},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"3fe11bf9e7eb493589d84f4a48cab6d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":174},
            "size":{
              "width":53,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7c7dc4e04f49cbad40c26d5312203f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":174},
                "size":{
                  "width":53,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a18f340d3ce4b61a8146807d2965cd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":40,
              "y":230},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2db6ac9df90452696e06c609a6a2e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":40,
                  "y":230},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"65f90cd03112416ababab3b0a614e2d6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":204},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u6_line.png"}},
{
          "id":"92854ebca4ad48709e730830872821ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":40,
              "y":340},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f291a8a1d14fc5b7b1ef9febee650a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":40,
                  "y":340},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"c9ba0fabc34c41cc8b92f43807481225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":270},
            "size":{
              "width":53,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b2060756aec4d428166a836d9537c64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":270},
                "size":{
                  "width":53,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f16924adb1144cfea0987477fb87e937",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":300},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u6_line.png"}},
{
          "id":"c996e302b723405a9a659a88b607bc5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":394},
            "size":{
              "width":53,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61b73fecb53f41ccb124d14eac106d59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":394},
                "size":{
                  "width":53,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d978462346e4dee8bac2a4d57f36649",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":424},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u6_line.png"}},
{
          "id":"723068af51174c7fb9127994217e6e65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":40,
              "y":466},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a05f8d2c04754eb5ae5ecb29f2ca1548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":40,
                  "y":466},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"66c803e2132845a3a79641562a6c56b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":520},
            "size":{
              "width":53,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1eec51aa5fce4878b6a8fdde958cba50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":520},
                "size":{
                  "width":53,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfdd39c651d14f0ea06bf1ae5afc386d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":550},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u6_line.png"}},
{
          "id":"b6334449d11542f799df6000c3c2a0d8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":1310,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u20_line.png"}},
{
          "id":"11a667da66d246a2a472c94555954b90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":48},
            "size":{
              "width":73,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c8adaeb66a4289a61fb08e1fd38e39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":48},
                "size":{
                  "width":73,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08e38c5d09bf4522af6b88d690db8300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":24},
            "size":{
              "width":182,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"508893594f2243c2abe859b6ce6a62fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":24},
                "size":{
                  "width":182,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d923d2e470b14e699b91067d06ba71f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":174,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7599b4ad37dd47d690eb6e59ded28ab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":174,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66a6a1607f794c55afc542c59c874263",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":40,
              "y":606},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e8273c01e564184a63e072ccddf4540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":40,
                  "y":606},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"57f38a75eef94918b4e4d5bc46feea53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":70,
              "y":660},
            "size":{
              "width":53,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe3dd33cb1c04c47aea015551877e362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":70,
                  "y":660},
                "size":{
                  "width":53,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e427aa6083af4eb3960e47c984e9c859",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":690},
            "size":{
              "width":200,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u6_line.png"}},
{
          "id":"91d4fad0735540deac942a50d2116645",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":134},
            "size":{
              "width":550,
              "height":236}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb29768d64a74239a75fbc231ead269d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":134},
                "size":{
                  "width":550,
                  "height":236}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u32.png"}},
{
          "id":"037de3b2f9d1423f89145bb44534d83a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":174},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15b1ac9a89c48118471393f2ba0a5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":174},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c84c9d5b4d3447ba94996262e87c6c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":174},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"983b4ad164af4936be9cbfed340856a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":570,
                  "y":174},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "37562ccb0005488a9d54e9b40cef9684":{
      "scriptId":"u0"},
    "bfbe46b8e58947d9962324a6f85746c0":{
      "scriptId":"u1"},
    "3fe11bf9e7eb493589d84f4a48cab6d8":{
      "scriptId":"u2"},
    "4a7c7dc4e04f49cbad40c26d5312203f":{
      "scriptId":"u3"},
    "4a18f340d3ce4b61a8146807d2965cd4":{
      "scriptId":"u4"},
    "d2db6ac9df90452696e06c609a6a2e28":{
      "scriptId":"u5"},
    "65f90cd03112416ababab3b0a614e2d6":{
      "scriptId":"u6"},
    "92854ebca4ad48709e730830872821ee":{
      "scriptId":"u7"},
    "71f291a8a1d14fc5b7b1ef9febee650a":{
      "scriptId":"u8"},
    "c9ba0fabc34c41cc8b92f43807481225":{
      "scriptId":"u9"},
    "8b2060756aec4d428166a836d9537c64":{
      "scriptId":"u10"},
    "f16924adb1144cfea0987477fb87e937":{
      "scriptId":"u11"},
    "c996e302b723405a9a659a88b607bc5c":{
      "scriptId":"u12"},
    "61b73fecb53f41ccb124d14eac106d59":{
      "scriptId":"u13"},
    "5d978462346e4dee8bac2a4d57f36649":{
      "scriptId":"u14"},
    "723068af51174c7fb9127994217e6e65":{
      "scriptId":"u15"},
    "a05f8d2c04754eb5ae5ecb29f2ca1548":{
      "scriptId":"u16"},
    "66c803e2132845a3a79641562a6c56b6":{
      "scriptId":"u17"},
    "1eec51aa5fce4878b6a8fdde958cba50":{
      "scriptId":"u18"},
    "dfdd39c651d14f0ea06bf1ae5afc386d":{
      "scriptId":"u19"},
    "b6334449d11542f799df6000c3c2a0d8":{
      "scriptId":"u20"},
    "11a667da66d246a2a472c94555954b90":{
      "scriptId":"u21"},
    "b2c8adaeb66a4289a61fb08e1fd38e39":{
      "scriptId":"u22"},
    "08e38c5d09bf4522af6b88d690db8300":{
      "scriptId":"u23"},
    "508893594f2243c2abe859b6ce6a62fd":{
      "scriptId":"u24"},
    "d923d2e470b14e699b91067d06ba71f0":{
      "scriptId":"u25"},
    "7599b4ad37dd47d690eb6e59ded28ab7":{
      "scriptId":"u26"},
    "66a6a1607f794c55afc542c59c874263":{
      "scriptId":"u27"},
    "2e8273c01e564184a63e072ccddf4540":{
      "scriptId":"u28"},
    "57f38a75eef94918b4e4d5bc46feea53":{
      "scriptId":"u29"},
    "fe3dd33cb1c04c47aea015551877e362":{
      "scriptId":"u30"},
    "e427aa6083af4eb3960e47c984e9c859":{
      "scriptId":"u31"},
    "91d4fad0735540deac942a50d2116645":{
      "scriptId":"u32"},
    "fb29768d64a74239a75fbc231ead269d":{
      "scriptId":"u33"},
    "037de3b2f9d1423f89145bb44534d83a":{
      "scriptId":"u34"},
    "d15b1ac9a89c48118471393f2ba0a5b5":{
      "scriptId":"u35"},
    "4c84c9d5b4d3447ba94996262e87c6c5":{
      "scriptId":"u36"},
    "983b4ad164af4936be9cbfed340856a8":{
      "scriptId":"u37"}}});