$axure.loadCurrentPage({
  "url":"平台基础页面管理.html",
  "generationDate":new Date(1428320978724.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d8461536e4774d26b9fd3a6e8842494e",
    "type":"Axure:Page",
    "name":"平台基础页面管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d01a535bde54becb9fd3b57aea3eb7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":225,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bdb823e23a84e4894864594ad76847b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":225,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65d35f82e6fa4d00ba68505fb5017ed1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"69a1bb4049f14586b3fefad0fb2a591d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":690,
              "y":73},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07287d20711f407b86d1714d66a191eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":690,
                  "y":73},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的线路/u19.png"}},
{
          "id":"35695d46c92148cf97e62291854ad282",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":571,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0493436cc96648918eaf03d3dcbc7aa2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da6312d0ada94c99a197b482b122acdb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u6.png"}},
{
              "id":"c260649d322a4363b483ddb55dddd13f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acc22e41a8a14248b501e149bb968816",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u10.png"}},
{
              "id":"b2cef79e8b2f40ee84d280d9c499c0b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":380,
                  "y":0},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9bc04f44fff4dc0af5b1201a1505b47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":380,
                      "y":0},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u8.png"}},
{
              "id":"6e03b21f9616463f8cf66818608f4728",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":380,
                  "y":30},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0275b5505914f2caf05647c5cbbe7b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":380,
                      "y":30},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u12.png"}},
{
              "id":"725855f8dea94834a9a12e19375b1eca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab679ae30953420cb0d7d05e1285040b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u14.png"}},
{
              "id":"88c5467c345e4a5e833acd2902344cf3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":380,
                  "y":60},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"793b2a366c2a4fce9969747e474d694c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":380,
                      "y":60},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u16.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "4d01a535bde54becb9fd3b57aea3eb7d":{
      "scriptId":"u0"},
    "7bdb823e23a84e4894864594ad76847b":{
      "scriptId":"u1"},
    "65d35f82e6fa4d00ba68505fb5017ed1":{
      "scriptId":"u2"},
    "69a1bb4049f14586b3fefad0fb2a591d":{
      "scriptId":"u3"},
    "07287d20711f407b86d1714d66a191eb":{
      "scriptId":"u4"},
    "35695d46c92148cf97e62291854ad282":{
      "scriptId":"u5"},
    "0493436cc96648918eaf03d3dcbc7aa2":{
      "scriptId":"u6"},
    "da6312d0ada94c99a197b482b122acdb":{
      "scriptId":"u7"},
    "b2cef79e8b2f40ee84d280d9c499c0b3":{
      "scriptId":"u8"},
    "e9bc04f44fff4dc0af5b1201a1505b47":{
      "scriptId":"u9"},
    "c260649d322a4363b483ddb55dddd13f":{
      "scriptId":"u10"},
    "acc22e41a8a14248b501e149bb968816":{
      "scriptId":"u11"},
    "6e03b21f9616463f8cf66818608f4728":{
      "scriptId":"u12"},
    "e0275b5505914f2caf05647c5cbbe7b1":{
      "scriptId":"u13"},
    "725855f8dea94834a9a12e19375b1eca":{
      "scriptId":"u14"},
    "ab679ae30953420cb0d7d05e1285040b":{
      "scriptId":"u15"},
    "88c5467c345e4a5e833acd2902344cf3":{
      "scriptId":"u16"},
    "793b2a366c2a4fce9969747e474d694c":{
      "scriptId":"u17"}}});