$axure.loadCurrentPage({
  "url":"添加网点.html",
  "generationDate":new Date(1428320975784.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"45b3dc69fc094bb7a2d81b133d5a8992",
    "type":"Axure:Page",
    "name":"添加网点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d7dd64a5c32c45cd8d6168cd733b625c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":78,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6041269219824ca0b3b77ccab8309548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":78,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9488a8ab20b4b39a37538441496fdc2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":73},
            "size":{
              "width":938,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/网点管理/u6_line.png"}},
{
          "id":"e8e8de098ba344f1b5808a8b33b28235",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":71,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f191ecf1c4241ff89a1904ee5ecd9f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":80,
                  "y":100},
                "size":{
                  "width":71,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2abd5b556f644dfea12217f05feb2981",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":110},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8faf2d3fc6e34633b034f87d90db7c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":110},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"688421d78df44836957229a304c5314e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":156},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417901dd18fb4cea8a613d45e4f9ac1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":156},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"416c43086ac6485ca91083a1653fe263",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":161,
              "y":202},
            "size":{
              "width":53,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6f56244fad48a5b7a46e61a42398dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":161,
                  "y":202},
                "size":{
                  "width":53,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcfac249d9f8402caa02c8b06b8baced",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":214},
            "size":{
              "width":300,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aef71de5f5844cde9c27c40d84258309",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":214},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u11.png"}},
{
          "id":"be09e4a3653e435ba4663f91ec3efe8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":260},
            "size":{
              "width":300,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c7ee0bf1284b30884aef0982c7d953",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":260},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u11.png"}},
{
          "id":"3333ec8d56e64b86acae8ed7a82922fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":306},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18da99533a324b85a84c74f9a5a67b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":306},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u15.png"}},
{
          "id":"651d3a5b0e584a7d8e24dbd4e496edad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":313},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f2a17403bf74a90921c43e2dfb9d9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":324,
                  "y":313},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06dacf83ab484eccb77ea6e49ecb786a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":364,
              "y":306},
            "size":{
              "width":156,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d5765494c9741ee8f0a5384dedc7b7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":364,
                  "y":306},
                "size":{
                  "width":156,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u19.png"}},
{
          "id":"2e03b38f31d94065881ab92405d55743",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":161,
              "y":735},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db570acd4eb2485b9344bb91bd7829d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":735},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69b8b087fa97404abfb2ee78bbf14f8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":771},
            "size":{
              "width":594,
              "height":344}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ca4ed6eac364caebc2100fb058e25d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":771},
                "size":{
                  "width":594,
                  "height":344}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u23.png"}},
{
          "id":"567def6ce377441788c87b5a87cee203",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1175},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"498e298ec1564b10af9761053b12cb7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":590},
            "size":{
              "width":149,
              "height":90},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58cf3e2fea94cb6bf97b2d5f5884630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":590},
                "size":{
                  "width":149,
                  "height":90},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u26.png"}},
{
          "id":"1df5c7006bd54881bb212825ee88d3da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":330,
              "y":664},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daa2d2aa3604458e9ffa96348cbc9e43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":664},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c835437aacf48d18fee893339ae4160",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":360},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a937d7f3f9cc44058697aa6e933f9be5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":360},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2d3dc7ea90064c86b7c69ca6f70e24ce",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":360},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ded6c28405b45259f07538ac8c3b28f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":360},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6771f8c9a3904afc97757a0b44778024",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":360},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a6bac030ba64d798f2317c6232d9480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":421,
                  "y":360},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b83c793a8f4e424887d720a3942265b2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":551,
              "y":360},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a77aab766d4c0ab1d58f1ccfd26310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":551,
                  "y":360},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f68fee41e8154fb99774301265f597f2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":410},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ec4de4845c2f42d580c096558b1ae563",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":301,
              "y":410},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e45ebad7004b4f01b3ffffa6defe0454",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":410},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"114ade8732634e298ec3bc565eded6dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":978,
              "y":484},
            "size":{
              "width":573,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65cb0a2ef56448c78bbca05a48ac4c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":978,
                  "y":484},
                "size":{
                  "width":573,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b561cb621f01466db2109c159eace22c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":161,
              "y":474},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c33c72b17948cebae160691b5a7132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":474},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39fc0549b29c4822841f412163c6dcf4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":470},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d7dd64a5c32c45cd8d6168cd733b625c":{
      "scriptId":"u0"},
    "6041269219824ca0b3b77ccab8309548":{
      "scriptId":"u1"},
    "c9488a8ab20b4b39a37538441496fdc2":{
      "scriptId":"u2"},
    "e8e8de098ba344f1b5808a8b33b28235":{
      "scriptId":"u3"},
    "2f191ecf1c4241ff89a1904ee5ecd9f4":{
      "scriptId":"u4"},
    "2abd5b556f644dfea12217f05feb2981":{
      "scriptId":"u5"},
    "8faf2d3fc6e34633b034f87d90db7c46":{
      "scriptId":"u6"},
    "688421d78df44836957229a304c5314e":{
      "scriptId":"u7"},
    "417901dd18fb4cea8a613d45e4f9ac1c":{
      "scriptId":"u8"},
    "416c43086ac6485ca91083a1653fe263":{
      "scriptId":"u9"},
    "ee6f56244fad48a5b7a46e61a42398dc":{
      "scriptId":"u10"},
    "fcfac249d9f8402caa02c8b06b8baced":{
      "scriptId":"u11"},
    "aef71de5f5844cde9c27c40d84258309":{
      "scriptId":"u12"},
    "be09e4a3653e435ba4663f91ec3efe8d":{
      "scriptId":"u13"},
    "35c7ee0bf1284b30884aef0982c7d953":{
      "scriptId":"u14"},
    "3333ec8d56e64b86acae8ed7a82922fc":{
      "scriptId":"u15"},
    "18da99533a324b85a84c74f9a5a67b27":{
      "scriptId":"u16"},
    "651d3a5b0e584a7d8e24dbd4e496edad":{
      "scriptId":"u17"},
    "1f2a17403bf74a90921c43e2dfb9d9ef":{
      "scriptId":"u18"},
    "06dacf83ab484eccb77ea6e49ecb786a":{
      "scriptId":"u19"},
    "1d5765494c9741ee8f0a5384dedc7b7a":{
      "scriptId":"u20"},
    "2e03b38f31d94065881ab92405d55743":{
      "scriptId":"u21"},
    "db570acd4eb2485b9344bb91bd7829d8":{
      "scriptId":"u22"},
    "69b8b087fa97404abfb2ee78bbf14f8b":{
      "scriptId":"u23"},
    "8ca4ed6eac364caebc2100fb058e25d5":{
      "scriptId":"u24"},
    "567def6ce377441788c87b5a87cee203":{
      "scriptId":"u25"},
    "498e298ec1564b10af9761053b12cb7e":{
      "scriptId":"u26"},
    "d58cf3e2fea94cb6bf97b2d5f5884630":{
      "scriptId":"u27"},
    "1df5c7006bd54881bb212825ee88d3da":{
      "scriptId":"u28"},
    "daa2d2aa3604458e9ffa96348cbc9e43":{
      "scriptId":"u29"},
    "0c835437aacf48d18fee893339ae4160":{
      "scriptId":"u30"},
    "a937d7f3f9cc44058697aa6e933f9be5":{
      "scriptId":"u31"},
    "2d3dc7ea90064c86b7c69ca6f70e24ce":{
      "scriptId":"u32"},
    "8ded6c28405b45259f07538ac8c3b28f":{
      "scriptId":"u33"},
    "6771f8c9a3904afc97757a0b44778024":{
      "scriptId":"u34"},
    "5a6bac030ba64d798f2317c6232d9480":{
      "scriptId":"u35"},
    "b83c793a8f4e424887d720a3942265b2":{
      "scriptId":"u36"},
    "80a77aab766d4c0ab1d58f1ccfd26310":{
      "scriptId":"u37"},
    "f68fee41e8154fb99774301265f597f2":{
      "scriptId":"u38"},
    "ec4de4845c2f42d580c096558b1ae563":{
      "scriptId":"u39"},
    "e45ebad7004b4f01b3ffffa6defe0454":{
      "scriptId":"u40"},
    "114ade8732634e298ec3bc565eded6dd":{
      "scriptId":"u41"},
    "65cb0a2ef56448c78bbca05a48ac4c2b":{
      "scriptId":"u42"},
    "b561cb621f01466db2109c159eace22c":{
      "scriptId":"u43"},
    "23c33c72b17948cebae160691b5a7132":{
      "scriptId":"u44"},
    "39fc0549b29c4822841f412163c6dcf4":{
      "scriptId":"u45"}}});