$axure.loadCurrentPage({
  "url":"承运商详细页.html",
  "generationDate":new Date(1428320976857.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"03d0d4b6ba074be4a7c126ec2668f0b8",
    "type":"Axure:Page",
    "name":"承运商详细页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12568a79b03c444293a31321caefe622",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4f4de36c1c49c2a49bce78a1f00dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7fe00a1239544f4a39551a2903edebc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "12568a79b03c444293a31321caefe622":{
      "scriptId":"u0"},
    "fc4f4de36c1c49c2a49bce78a1f00dff":{
      "scriptId":"u1"},
    "b7fe00a1239544f4a39551a2903edebc":{
      "scriptId":"u2"}}});