$axure.loadCurrentPage({
  "url":"优惠劵.html",
  "generationDate":new Date(1428320977016.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56b47c5f89a7474a9ee2c1ad890222b3",
    "type":"Axure:Page",
    "name":"优惠劵",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d6653ff422c4a21941b01a61767201f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e684ad7c1e1483a88028248e86a447a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cd462b35ccd4e379c0a34801b12f89a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"6b7116c6eb8745309667e03051adc2e3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":400,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5daa4119e974704986cdb1a71ff442b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65ba82b281454da492e289deabf01ee9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"4eb36ace08514225a3b8a7055dac34a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32079255c17e4457835f310d6472cb8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u30.png"}},
{
              "id":"c8bc667410744964a86bc9d6f7ffc37d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28eddf94ffe644fcad82e35bfce0622e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"639f94a6e062429fa06e8347d1ad3020",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"546d88ec08ae48dda0abea77bb982be2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"1b0f1d906cad4cf8a991aa517b3f4b1f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98b0af2c0e0f4336a2b565fe8a393e19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/优惠劵/u8.png"}},
{
              "id":"86c024abeff643bf92f5353352a84fe0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9178f65628c409ba46fb9dd1f984d0c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册/u11.png"}}]},
{
          "id":"e8b32c4b77aa48a8ac289907ff79dfc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":690,
              "y":73},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c9b2fa3f43a4c33a1f52a669a376a43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":690,
                  "y":73},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的线路/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3d6653ff422c4a21941b01a61767201f":{
      "scriptId":"u0"},
    "5e684ad7c1e1483a88028248e86a447a":{
      "scriptId":"u1"},
    "6cd462b35ccd4e379c0a34801b12f89a":{
      "scriptId":"u2"},
    "6b7116c6eb8745309667e03051adc2e3":{
      "scriptId":"u3"},
    "c5daa4119e974704986cdb1a71ff442b":{
      "scriptId":"u4"},
    "65ba82b281454da492e289deabf01ee9":{
      "scriptId":"u5"},
    "c8bc667410744964a86bc9d6f7ffc37d":{
      "scriptId":"u6"},
    "28eddf94ffe644fcad82e35bfce0622e":{
      "scriptId":"u7"},
    "1b0f1d906cad4cf8a991aa517b3f4b1f":{
      "scriptId":"u8"},
    "98b0af2c0e0f4336a2b565fe8a393e19":{
      "scriptId":"u9"},
    "4eb36ace08514225a3b8a7055dac34a9":{
      "scriptId":"u10"},
    "32079255c17e4457835f310d6472cb8e":{
      "scriptId":"u11"},
    "639f94a6e062429fa06e8347d1ad3020":{
      "scriptId":"u12"},
    "546d88ec08ae48dda0abea77bb982be2":{
      "scriptId":"u13"},
    "86c024abeff643bf92f5353352a84fe0":{
      "scriptId":"u14"},
    "e9178f65628c409ba46fb9dd1f984d0c":{
      "scriptId":"u15"},
    "e8b32c4b77aa48a8ac289907ff79dfc6":{
      "scriptId":"u16"},
    "1c9b2fa3f43a4c33a1f52a669a376a43":{
      "scriptId":"u17"}}});