$axure.loadCurrentPage({
  "url":"帮助中心_1.html",
  "generationDate":new Date(1428320978834.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e5c2570cd16f4d69a5ee454dffc7def3",
    "type":"Axure:Page",
    "name":"帮助中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dcc5c1e972f8400da2db74bc0cb233fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04ba121b97e4d8498683907c5ae2669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b6a10b0430c46f7a91fc0a31462c466",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"03dbdee29d8244b4b98c4985ec81a7f6",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":670,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80c90ef40af4f9f8bfa0b935647814c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76bbde765d5044b4b1b4910284a6abf5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u6.png"}},
{
              "id":"465daea984ea44988cb205c28fb90621",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dbba0a1cf534d5d94b87b41f93d7557",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u6.png"}},
{
              "id":"85a07607dd3b4747aa5a9ae70ffba735",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":379,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b022b7b2c0a4bf5bc06bff9f6263013",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":90},
                    "size":{
                      "width":379,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u24.png"}},
{
              "id":"e589e2608ad7407ba62df70de9eb3169",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":479,
                  "y":0},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f4ff2b64cea420d90cc45eb55696119",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":479,
                      "y":0},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u12.png"}},
{
              "id":"5dcd1a4270a844eb8b174e9d7e54b5cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":30},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"195862b082814bb19f84f040709aab71",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":479,
                      "y":30},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u12.png"}},
{
              "id":"926950dd432a480fa616c080eaba902b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":90},
                "size":{
                  "width":191,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29bd9a34489d437eafffde5d1ddc9de0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":479,
                      "y":90},
                    "size":{
                      "width":191,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u26.png"}},
{
              "id":"e6ece06f01894898b4ddf9b3141cc3db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"382a459552964d5ea6629f0c53efb384",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u6.png"}},
{
              "id":"c668076069ec4a2da95ff489b2d0f8d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":60},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7492a1f32ddd47acaef465b6a051ffb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":479,
                      "y":60},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u12.png"}},
{
              "id":"863bd33dfc3740399933bad68a853771",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":126},
                "size":{
                  "width":379,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a261e7c1000844aca67c1c2966894e2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":126},
                    "size":{
                      "width":379,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/帮助中心_1/u30.png"}},
{
              "id":"426412ce1e354beb9f048e7ec0d21b46",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":479,
                  "y":126},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ad29aa2910b42d0bf48983a567c004f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":479,
                      "y":126},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u16.png"}},
{
              "id":"8163a6b3681b4b83bb3d54cee62630ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a093bef99a714ee4ab83f189799a1306",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"9b0e2f72ed4e436db03fc461bc06e739",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a8f24b5ffef43538c1ee0345af09654",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"5a14666a9eff41998dff34bc82c4bf28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7d1b7a5f9d24f70bb01725dd6151d3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"9d25bae59cd94d39ac13dbe2141acb20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85aeb0eb13544e7499a6db4b01cdd4bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u14.png"}},
{
              "id":"d9b045575f5b4be89132ca3f46daabf6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":126},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a08a6dc5946f436ea957945a3bee4434",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":126},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}}]},
{
          "id":"13a0ed45be7041acb5ecd86dddc5a7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":690,
              "y":73},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1d89dc1d72b440e9d63d9a2675acb36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":690,
                  "y":73},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的线路/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dcc5c1e972f8400da2db74bc0cb233fa":{
      "scriptId":"u0"},
    "b04ba121b97e4d8498683907c5ae2669":{
      "scriptId":"u1"},
    "2b6a10b0430c46f7a91fc0a31462c466":{
      "scriptId":"u2"},
    "03dbdee29d8244b4b98c4985ec81a7f6":{
      "scriptId":"u3"},
    "8163a6b3681b4b83bb3d54cee62630ed":{
      "scriptId":"u4"},
    "a093bef99a714ee4ab83f189799a1306":{
      "scriptId":"u5"},
    "a80c90ef40af4f9f8bfa0b935647814c":{
      "scriptId":"u6"},
    "76bbde765d5044b4b1b4910284a6abf5":{
      "scriptId":"u7"},
    "e589e2608ad7407ba62df70de9eb3169":{
      "scriptId":"u8"},
    "0f4ff2b64cea420d90cc45eb55696119":{
      "scriptId":"u9"},
    "9b0e2f72ed4e436db03fc461bc06e739":{
      "scriptId":"u10"},
    "1a8f24b5ffef43538c1ee0345af09654":{
      "scriptId":"u11"},
    "465daea984ea44988cb205c28fb90621":{
      "scriptId":"u12"},
    "5dbba0a1cf534d5d94b87b41f93d7557":{
      "scriptId":"u13"},
    "5dcd1a4270a844eb8b174e9d7e54b5cf":{
      "scriptId":"u14"},
    "195862b082814bb19f84f040709aab71":{
      "scriptId":"u15"},
    "5a14666a9eff41998dff34bc82c4bf28":{
      "scriptId":"u16"},
    "a7d1b7a5f9d24f70bb01725dd6151d3a":{
      "scriptId":"u17"},
    "e6ece06f01894898b4ddf9b3141cc3db":{
      "scriptId":"u18"},
    "382a459552964d5ea6629f0c53efb384":{
      "scriptId":"u19"},
    "c668076069ec4a2da95ff489b2d0f8d6":{
      "scriptId":"u20"},
    "7492a1f32ddd47acaef465b6a051ffb6":{
      "scriptId":"u21"},
    "9d25bae59cd94d39ac13dbe2141acb20":{
      "scriptId":"u22"},
    "85aeb0eb13544e7499a6db4b01cdd4bc":{
      "scriptId":"u23"},
    "85a07607dd3b4747aa5a9ae70ffba735":{
      "scriptId":"u24"},
    "4b022b7b2c0a4bf5bc06bff9f6263013":{
      "scriptId":"u25"},
    "926950dd432a480fa616c080eaba902b":{
      "scriptId":"u26"},
    "29bd9a34489d437eafffde5d1ddc9de0":{
      "scriptId":"u27"},
    "d9b045575f5b4be89132ca3f46daabf6":{
      "scriptId":"u28"},
    "a08a6dc5946f436ea957945a3bee4434":{
      "scriptId":"u29"},
    "863bd33dfc3740399933bad68a853771":{
      "scriptId":"u30"},
    "a261e7c1000844aca67c1c2966894e2b":{
      "scriptId":"u31"},
    "426412ce1e354beb9f048e7ec0d21b46":{
      "scriptId":"u32"},
    "2ad29aa2910b42d0bf48983a567c004f":{
      "scriptId":"u33"},
    "13a0ed45be7041acb5ecd86dddc5a7fb":{
      "scriptId":"u34"},
    "b1d89dc1d72b440e9d63d9a2675acb36":{
      "scriptId":"u35"}}});