$axure.loadCurrentPage({
  "url":"安全设置.html",
  "generationDate":new Date(1428320975920.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92aeec41cefd40beab2f09d2cb1b1676",
    "type":"Axure:Page",
    "name":"安全设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f011a2299b8a4dde898da4f92a621545",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8552cdc01d5d40e9b7dd6673d78bdfdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1da66572af8b43bcb142cd7348500694",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"bff0c37536134b2895a5f63462741c73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":170},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0238d5ae3dbe4c9b950aab51f61ea8d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":170},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"7bf1007039bc49b2b47a453196756272",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":177},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f570bcd2af74c8db08d6e5541d71b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":177},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f465aa49676b4b51b7e0020682673c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":237},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c075d1b0638d4706a3f89009b1b94de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":237},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54cfc124f461497cb3d49fa7f3aefa53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":284},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df5230c365954581a0aaf04a59149fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":284},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b137f5985ccc4fe896d3916fb3876128",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":227},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e88bbfc131b4d27836debb474957aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":227},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"d2c412a37a064270b6e618ffc541fdb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":284},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4a7f2f6fec44641ab4f7a1fcb274552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":284},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"58e7d2866b194e2a97b4927fcfd9f445",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":345},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f011a2299b8a4dde898da4f92a621545":{
      "scriptId":"u0"},
    "8552cdc01d5d40e9b7dd6673d78bdfdd":{
      "scriptId":"u1"},
    "1da66572af8b43bcb142cd7348500694":{
      "scriptId":"u2"},
    "bff0c37536134b2895a5f63462741c73":{
      "scriptId":"u3"},
    "0238d5ae3dbe4c9b950aab51f61ea8d4":{
      "scriptId":"u4"},
    "7bf1007039bc49b2b47a453196756272":{
      "scriptId":"u5"},
    "8f570bcd2af74c8db08d6e5541d71b35":{
      "scriptId":"u6"},
    "f465aa49676b4b51b7e0020682673c14":{
      "scriptId":"u7"},
    "c075d1b0638d4706a3f89009b1b94de9":{
      "scriptId":"u8"},
    "54cfc124f461497cb3d49fa7f3aefa53":{
      "scriptId":"u9"},
    "df5230c365954581a0aaf04a59149fde":{
      "scriptId":"u10"},
    "b137f5985ccc4fe896d3916fb3876128":{
      "scriptId":"u11"},
    "3e88bbfc131b4d27836debb474957aa0":{
      "scriptId":"u12"},
    "d2c412a37a064270b6e618ffc541fdb7":{
      "scriptId":"u13"},
    "b4a7f2f6fec44641ab4f7a1fcb274552":{
      "scriptId":"u14"},
    "58e7d2866b194e2a97b4927fcfd9f445":{
      "scriptId":"u15"}}});