$axure.loadCurrentPage({
  "url":"新增优惠劵.html",
  "generationDate":new Date(1428320977037.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"991f5d2571574462805160f3e9feddfb",
    "type":"Axure:Page",
    "name":"新增优惠劵",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4bf40f3e92c540f58bb674a9fcb39bbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca40eab6112e42ecaa10c6f3187c7f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6cafb369e4d46ca9762005624e04fe1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"23391d50a1b547d5b6a1583fff6004b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":40,
              "y":170},
            "size":{
              "width":66,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f218fdb53e2d4a8bbcc5378c6f954d72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":40,
                  "y":170},
                "size":{
                  "width":66,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"237616619db64ed285ac6d65dee16d37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":181},
            "size":{
              "width":200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e16424d2f9e46daae69e0c4936cdaf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":181},
                "size":{
                  "width":200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增优惠劵/u5.png"}},
{
          "id":"fa721cc3fe0f48ae9088d873972f889e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":227},
            "size":{
              "width":104,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8602b39a28bd49e7b00a5b4f7a25c887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":227},
                "size":{
                  "width":104,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增优惠劵/u7.png"}},
{
          "id":"f2de85aa1bd942b3aad80401214b3ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":230},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eb3d09bec7847789eb8e095a51cddff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":230},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc860c083fe745259dfa6650d35f61d4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":278},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5abfd532b2ce4110affd8d0e8c9ba35d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":350},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "4bf40f3e92c540f58bb674a9fcb39bbd":{
      "scriptId":"u0"},
    "ca40eab6112e42ecaa10c6f3187c7f5b":{
      "scriptId":"u1"},
    "b6cafb369e4d46ca9762005624e04fe1":{
      "scriptId":"u2"},
    "23391d50a1b547d5b6a1583fff6004b3":{
      "scriptId":"u3"},
    "f218fdb53e2d4a8bbcc5378c6f954d72":{
      "scriptId":"u4"},
    "237616619db64ed285ac6d65dee16d37":{
      "scriptId":"u5"},
    "2e16424d2f9e46daae69e0c4936cdaf1":{
      "scriptId":"u6"},
    "fa721cc3fe0f48ae9088d873972f889e":{
      "scriptId":"u7"},
    "8602b39a28bd49e7b00a5b4f7a25c887":{
      "scriptId":"u8"},
    "f2de85aa1bd942b3aad80401214b3ff8":{
      "scriptId":"u9"},
    "2eb3d09bec7847789eb8e095a51cddff":{
      "scriptId":"u10"},
    "cc860c083fe745259dfa6650d35f61d4":{
      "scriptId":"u11"},
    "5abfd532b2ce4110affd8d0e8c9ba35d":{
      "scriptId":"u12"}}});