$axure.loadCurrentPage({
  "url":"帮助中心.html",
  "generationDate":new Date(1428320975968.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a8d48ae4d12e498a980c5f1e0ed96815",
    "type":"Axure:Page",
    "name":"帮助中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"839d901a62164a3585b21aee88cedaf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":700,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ab732e95c6432a935ac55fb462b169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":60,
                  "y":100},
                "size":{
                  "width":700,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助中心/u0.png"}},
{
          "id":"b141c0420605429bb308c78bd20725ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":112},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7c0608db10549d49d0914d6d05882ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":112},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea1f7d79c90a489b9322379a2c0c9dbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":78,
              "y":154},
            "size":{
              "width":53,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab09f9d60b574869bb191af31a172855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":78,
                  "y":154},
                "size":{
                  "width":53,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e1a551214f443e69f19ae6237be7398",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":180},
            "size":{
              "width":700,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助中心/u6_line.png"}},
{
          "id":"ecf0cb90ab2e432b9a8b04cc0eb2137e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":226},
            "size":{
              "width":700,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助中心/u6_line.png"}},
{
          "id":"bf4bafc006c141a6a82691b5bb1a887a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":60,
              "y":260},
            "size":{
              "width":700,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cbe39ef7dfc43ce9d0dfa06c0a6999f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":60,
                  "y":260},
                "size":{
                  "width":700,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/帮助中心/u0.png"}},
{
          "id":"ac541fcd52084990b98a8664821bd4a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":272},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72dd789c0c79452681858b3dd368e9ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":272},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f03e1a0b1a184d019c5d32faef839da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":78,
              "y":318},
            "size":{
              "width":53,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81b52117ca0a475797ef32f9fdb25abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":78,
                  "y":318},
                "size":{
                  "width":53,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9660ed91eeca44dd9d9bc8b6a9f6cca1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":344},
            "size":{
              "width":700,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助中心/u6_line.png"}},
{
          "id":"afe7b283b73946fbaaeceaed795c1ad0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":390},
            "size":{
              "width":700,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/帮助中心/u6_line.png"}},
{
          "id":"a32244f078594598939a5a0a73a05ebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":40},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b775bd8fa6b4357bfc844ddbcfee5d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":40},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "839d901a62164a3585b21aee88cedaf2":{
      "scriptId":"u0"},
    "d8ab732e95c6432a935ac55fb462b169":{
      "scriptId":"u1"},
    "b141c0420605429bb308c78bd20725ee":{
      "scriptId":"u2"},
    "c7c0608db10549d49d0914d6d05882ff":{
      "scriptId":"u3"},
    "ea1f7d79c90a489b9322379a2c0c9dbb":{
      "scriptId":"u4"},
    "ab09f9d60b574869bb191af31a172855":{
      "scriptId":"u5"},
    "4e1a551214f443e69f19ae6237be7398":{
      "scriptId":"u6"},
    "ecf0cb90ab2e432b9a8b04cc0eb2137e":{
      "scriptId":"u7"},
    "bf4bafc006c141a6a82691b5bb1a887a":{
      "scriptId":"u8"},
    "4cbe39ef7dfc43ce9d0dfa06c0a6999f":{
      "scriptId":"u9"},
    "ac541fcd52084990b98a8664821bd4a2":{
      "scriptId":"u10"},
    "72dd789c0c79452681858b3dd368e9ba":{
      "scriptId":"u11"},
    "f03e1a0b1a184d019c5d32faef839da1":{
      "scriptId":"u12"},
    "81b52117ca0a475797ef32f9fdb25abc":{
      "scriptId":"u13"},
    "9660ed91eeca44dd9d9bc8b6a9f6cca1":{
      "scriptId":"u14"},
    "afe7b283b73946fbaaeceaed795c1ad0":{
      "scriptId":"u15"},
    "a32244f078594598939a5a0a73a05ebb":{
      "scriptId":"u16"},
    "0b775bd8fa6b4357bfc844ddbcfee5d4":{
      "scriptId":"u17"}}});