$axure.loadCurrentPage({
  "url":"物流商入驻申请.html",
  "generationDate":new Date(1427610287262.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a76a5ff6b3d14ec8bc574e464f1b831c",
    "type":"Axure:Page",
    "name":"物流商入驻申请",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7db7de8ae6ad49548419e672b854a9a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":80},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05f1cff15c345079899bd9f628fb7f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":80},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64caa95f769f4dd98f32f2b5e6d6caf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":184},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff98a9d6503843f18ac4a83e7e0d14b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":184},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4966dfa59f6e453c8bcd22ea6189b8ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":177},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"065deaf5f1cd4a66b09e25adb8598d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":177},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商入驻申请/u4.png"}},
{
          "id":"afa1d0480c7a47538e5cedf33d600d32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":244},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc6b05dbb6b445d807f201839879007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":244},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58b3956710b448399d5a1ea939b782ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":237},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09cb71c9f3c47eeac2b0411ef6b3997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"6de8187a5ee1460492bc2c881f034b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":237},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132f5748242e4989abc4f6f1fc427c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"a04011f1db5244bc83a56e82478534c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":158,
              "y":310},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42ed849d57cd4fdfb4f12e341243b58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":158,
                  "y":310},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"1fe35dc246d540e09a93ad8539e0a8e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":137},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/物流商入驻申请/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7db7de8ae6ad49548419e672b854a9a7":{
      "scriptId":"u0"},
    "e05f1cff15c345079899bd9f628fb7f8":{
      "scriptId":"u1"},
    "64caa95f769f4dd98f32f2b5e6d6caf6":{
      "scriptId":"u2"},
    "ff98a9d6503843f18ac4a83e7e0d14b6":{
      "scriptId":"u3"},
    "4966dfa59f6e453c8bcd22ea6189b8ef":{
      "scriptId":"u4"},
    "065deaf5f1cd4a66b09e25adb8598d81":{
      "scriptId":"u5"},
    "afa1d0480c7a47538e5cedf33d600d32":{
      "scriptId":"u6"},
    "6fc6b05dbb6b445d807f201839879007":{
      "scriptId":"u7"},
    "58b3956710b448399d5a1ea939b782ec":{
      "scriptId":"u8"},
    "b09cb71c9f3c47eeac2b0411ef6b3997":{
      "scriptId":"u9"},
    "6de8187a5ee1460492bc2c881f034b92":{
      "scriptId":"u10"},
    "132f5748242e4989abc4f6f1fc427c0f":{
      "scriptId":"u11"},
    "a04011f1db5244bc83a56e82478534c2":{
      "scriptId":"u12"},
    "42ed849d57cd4fdfb4f12e341243b58d":{
      "scriptId":"u13"},
    "1fe35dc246d540e09a93ad8539e0a8e3":{
      "scriptId":"u14"}}});