$axure.loadCurrentPage({
  "url":"意见反馈管理.html",
  "generationDate":new Date(1428320978774.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3d140a3920db4a13ad9bd481e5ca2bae",
    "type":"Axure:Page",
    "name":"意见反馈管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bef3ce07c5fd43a18a9c680e95056ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f43764f2f454ea9b12cdf0ed8a3d1c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15dc6b215a1c4dc485e2e10150ce6e3f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"1a3672a1c1dd4e7eaf614e824e64a441",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":240},
            "size":{
              "width":670,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff7437a9df540cab74905590cf784a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afc3a91568cf46fc86af5214680aa374",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u6.png"}},
{
              "id":"6c977536fccf4dcda33990a5b0bdc138",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dd22b89f5a24348984fa1f9977cfe29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u10.png"}},
{
              "id":"a2a201ea4fc14c01ae16c6ae87b6fa04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":480,
                  "y":0},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a01cf9063f7f49769f08cd3096aecb9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":480,
                      "y":0},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/意见反馈管理/u8.png"}},
{
              "id":"5202f427db2444ca9f13a3cc4c3a51b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":30},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"824f5e2c04a948a3895260d68bb4d5f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":480,
                      "y":30},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/意见反馈管理/u14.png"}},
{
              "id":"be0876594f27434fb7f33936f99fe85f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":380,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7644e5241b4c4c58b15c53ed7a01a12c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":380,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u14.png"}},
{
              "id":"bfbafc99085d4f7c9c259483feb6e6ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":60},
                "size":{
                  "width":190,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ddef38e140c54c26b988713950053a94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":480,
                      "y":60},
                    "size":{
                      "width":190,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/意见反馈管理/u20.png"}},
{
              "id":"19538163069342a19ddf231520b31ff0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f0c1e582d6d448b79e0ff2c168882613",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/意见反馈管理/u4.png"}},
{
              "id":"9761c7d3aae3400fac290e28b275503d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff8246f3a7b04d32a0f13bd8f970d814",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"7916a7af3d564343890693322c6dd13e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f5937e8d8658447488c72f2dc1fb5922",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}}]},
{
          "id":"b80131e1eef243bb99961ecd9b5a5a21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":164},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94d63dfc752a4ee2a2fb7a00f6c55532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":164},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"559a4745354b4f168f1a79e0a0e06043",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":169},
            "size":{
              "width":5,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed53e5638da14f34890e3c75705d73d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":169},
                "size":{
                  "width":5,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff1b2f2cdbed41049170dbbcd653ebc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":164},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf2711eb7194985957c888135b0da6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":164},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"4d86846b46c145c5a52de3b6fb300b2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":168},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c280e6202c4b059b787a7c10a1f869",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":168},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u35.png"}},
{
          "id":"4eaacf1f6ae542c2ad5d5c21ea03a26c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":168},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bc014c18d634f0ba6c6ed702e296853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":168},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u35.png"}},
{
          "id":"ce217918819141099ff6fbefaba9c063",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":340,
              "y":164},
            "size":{
              "width":70,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bb1ed2e9edf43bdb0a98c56991cf9c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":340,
                  "y":164},
                "size":{
                  "width":70,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点介绍/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bef3ce07c5fd43a18a9c680e95056ec4":{
      "scriptId":"u0"},
    "8f43764f2f454ea9b12cdf0ed8a3d1c6":{
      "scriptId":"u1"},
    "15dc6b215a1c4dc485e2e10150ce6e3f":{
      "scriptId":"u2"},
    "1a3672a1c1dd4e7eaf614e824e64a441":{
      "scriptId":"u3"},
    "19538163069342a19ddf231520b31ff0":{
      "scriptId":"u4"},
    "f0c1e582d6d448b79e0ff2c168882613":{
      "scriptId":"u5"},
    "eff7437a9df540cab74905590cf784a6":{
      "scriptId":"u6"},
    "afc3a91568cf46fc86af5214680aa374":{
      "scriptId":"u7"},
    "a2a201ea4fc14c01ae16c6ae87b6fa04":{
      "scriptId":"u8"},
    "a01cf9063f7f49769f08cd3096aecb9a":{
      "scriptId":"u9"},
    "9761c7d3aae3400fac290e28b275503d":{
      "scriptId":"u10"},
    "ff8246f3a7b04d32a0f13bd8f970d814":{
      "scriptId":"u11"},
    "6c977536fccf4dcda33990a5b0bdc138":{
      "scriptId":"u12"},
    "6dd22b89f5a24348984fa1f9977cfe29":{
      "scriptId":"u13"},
    "5202f427db2444ca9f13a3cc4c3a51b6":{
      "scriptId":"u14"},
    "824f5e2c04a948a3895260d68bb4d5f8":{
      "scriptId":"u15"},
    "7916a7af3d564343890693322c6dd13e":{
      "scriptId":"u16"},
    "f5937e8d8658447488c72f2dc1fb5922":{
      "scriptId":"u17"},
    "be0876594f27434fb7f33936f99fe85f":{
      "scriptId":"u18"},
    "7644e5241b4c4c58b15c53ed7a01a12c":{
      "scriptId":"u19"},
    "bfbafc99085d4f7c9c259483feb6e6ac":{
      "scriptId":"u20"},
    "ddef38e140c54c26b988713950053a94":{
      "scriptId":"u21"},
    "b80131e1eef243bb99961ecd9b5a5a21":{
      "scriptId":"u22"},
    "94d63dfc752a4ee2a2fb7a00f6c55532":{
      "scriptId":"u23"},
    "559a4745354b4f168f1a79e0a0e06043":{
      "scriptId":"u24"},
    "ed53e5638da14f34890e3c75705d73d3":{
      "scriptId":"u25"},
    "ff1b2f2cdbed41049170dbbcd653ebc7":{
      "scriptId":"u26"},
    "bdf2711eb7194985957c888135b0da6c":{
      "scriptId":"u27"},
    "4d86846b46c145c5a52de3b6fb300b2f":{
      "scriptId":"u28"},
    "32c280e6202c4b059b787a7c10a1f869":{
      "scriptId":"u29"},
    "4eaacf1f6ae542c2ad5d5c21ea03a26c":{
      "scriptId":"u30"},
    "5bc014c18d634f0ba6c6ed702e296853":{
      "scriptId":"u31"},
    "ce217918819141099ff6fbefaba9c063":{
      "scriptId":"u32"},
    "7bb1ed2e9edf43bdb0a98c56991cf9c9":{
      "scriptId":"u33"}}});