$axure.loadCurrentPage({
  "url":"承运商入驻申请.html",
  "generationDate":new Date(1428320974705.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a76a5ff6b3d14ec8bc574e464f1b831c",
    "type":"Axure:Page",
    "name":"承运商入驻申请",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7db7de8ae6ad49548419e672b854a9a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":80},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e05f1cff15c345079899bd9f628fb7f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":80},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64caa95f769f4dd98f32f2b5e6d6caf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":184},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff98a9d6503843f18ac4a83e7e0d14b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":184},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4966dfa59f6e453c8bcd22ea6189b8ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":177},
            "size":{
              "width":210,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"065deaf5f1cd4a66b09e25adb8598d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":177},
                "size":{
                  "width":210,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u4.png"}},
{
          "id":"afa1d0480c7a47538e5cedf33d600d32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":244},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc6b05dbb6b445d807f201839879007",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":244},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58b3956710b448399d5a1ea939b782ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":237},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b09cb71c9f3c47eeac2b0411ef6b3997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"6de8187a5ee1460492bc2c881f034b92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":237},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"132f5748242e4989abc4f6f1fc427c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":237},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"a04011f1db5244bc83a56e82478534c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":158,
              "y":310},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42ed849d57cd4fdfb4f12e341243b58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":158,
                  "y":310},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"1fe35dc246d540e09a93ad8539e0a8e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":137},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/承运商入驻申请/u14_line.png"}},
{
          "id":"bd7171b43ae34c98abfdb902fb9fb7e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":878,
              "y":147},
            "size":{
              "width":84,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dccd4a4c3a0c445c93d04a3e7f3f07cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":878,
                  "y":147},
                "size":{
                  "width":84,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1aab2babb414dc68886b704016bdea7",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":253},
            "size":{
              "width":162,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5d0733b4eb434c67a5af83dbf3d3889c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":163},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11bcf917c4d1467193a368ca23b053bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":163},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"86f935f9a8ec472e9aab0aed85186da8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":203},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d277162dbb604c9e94d372dc7ab5604b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":203},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"5df1debfc8d743a9b24e5694272a0d97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":303},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"218b6f60eb5d4a338b140aa30d2f94da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":303},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"330d4b8c72d94d89bc540662bdf82085",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":348},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b248f0270c744fa0aaf94d5ae899ad1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":348},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"5900e0488bcd41dbb8955e1f36ae231a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":962,
              "y":397},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e03cb01a25ce4c3d86fd09ad15006c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":962,
                  "y":397},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"c1c2ba846fac453490a197d4a1016464",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":70},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d0b1beb4364156a017829deab95997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":870,
                  "y":70},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f4ba980caad41aa86baa4fd0f70f155",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":127},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/承运商入驻申请/u14_line.png"}},
{
          "id":"071a617ca51049b789c339553bcebe51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":878,
              "y":510},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20b2be17d60a4181a06b63a66545f9a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":878,
                  "y":510},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"81913f4c5e834c3285ce6c72cc3131b5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":460},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/承运商入驻申请/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7db7de8ae6ad49548419e672b854a9a7":{
      "scriptId":"u0"},
    "e05f1cff15c345079899bd9f628fb7f8":{
      "scriptId":"u1"},
    "64caa95f769f4dd98f32f2b5e6d6caf6":{
      "scriptId":"u2"},
    "ff98a9d6503843f18ac4a83e7e0d14b6":{
      "scriptId":"u3"},
    "4966dfa59f6e453c8bcd22ea6189b8ef":{
      "scriptId":"u4"},
    "065deaf5f1cd4a66b09e25adb8598d81":{
      "scriptId":"u5"},
    "afa1d0480c7a47538e5cedf33d600d32":{
      "scriptId":"u6"},
    "6fc6b05dbb6b445d807f201839879007":{
      "scriptId":"u7"},
    "58b3956710b448399d5a1ea939b782ec":{
      "scriptId":"u8"},
    "b09cb71c9f3c47eeac2b0411ef6b3997":{
      "scriptId":"u9"},
    "6de8187a5ee1460492bc2c881f034b92":{
      "scriptId":"u10"},
    "132f5748242e4989abc4f6f1fc427c0f":{
      "scriptId":"u11"},
    "a04011f1db5244bc83a56e82478534c2":{
      "scriptId":"u12"},
    "42ed849d57cd4fdfb4f12e341243b58d":{
      "scriptId":"u13"},
    "1fe35dc246d540e09a93ad8539e0a8e3":{
      "scriptId":"u14"},
    "bd7171b43ae34c98abfdb902fb9fb7e7":{
      "scriptId":"u15"},
    "dccd4a4c3a0c445c93d04a3e7f3f07cf":{
      "scriptId":"u16"},
    "c1aab2babb414dc68886b704016bdea7":{
      "scriptId":"u17"},
    "5d0733b4eb434c67a5af83dbf3d3889c":{
      "scriptId":"u18"},
    "11bcf917c4d1467193a368ca23b053bf":{
      "scriptId":"u19"},
    "86f935f9a8ec472e9aab0aed85186da8":{
      "scriptId":"u20"},
    "d277162dbb604c9e94d372dc7ab5604b":{
      "scriptId":"u21"},
    "5df1debfc8d743a9b24e5694272a0d97":{
      "scriptId":"u22"},
    "218b6f60eb5d4a338b140aa30d2f94da":{
      "scriptId":"u23"},
    "330d4b8c72d94d89bc540662bdf82085":{
      "scriptId":"u24"},
    "b248f0270c744fa0aaf94d5ae899ad1c":{
      "scriptId":"u25"},
    "5900e0488bcd41dbb8955e1f36ae231a":{
      "scriptId":"u26"},
    "e03cb01a25ce4c3d86fd09ad15006c24":{
      "scriptId":"u27"},
    "c1c2ba846fac453490a197d4a1016464":{
      "scriptId":"u28"},
    "14d0b1beb4364156a017829deab95997":{
      "scriptId":"u29"},
    "4f4ba980caad41aa86baa4fd0f70f155":{
      "scriptId":"u30"},
    "071a617ca51049b789c339553bcebe51":{
      "scriptId":"u31"},
    "20b2be17d60a4181a06b63a66545f9a8":{
      "scriptId":"u32"},
    "81913f4c5e834c3285ce6c72cc3131b5":{
      "scriptId":"u33"}}});