$axure.loadCurrentPage({
  "url":"增值服务设置.html",
  "generationDate":new Date(1428320979085.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5efb639562f645e5b235c2f46c11c617",
    "type":"Axure:Page",
    "name":"增值服务设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"816de8c63d804e7ebbfec19556da1794",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":169,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c29017471d74b3faa414b873a0afa7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":169,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17483bc31e824a8e9f3d3bac38583a8b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":836,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/车辆录入/u2_line.png"}},
{
          "id":"b0805bd3ad914eeb9bcd6d0ea8c42a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":435},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009881ea0fe6436bbb0f95aa066f2ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":435},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"3ad8c1265cb6492f90cfd18dc287a746",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":440},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"195e626e7f64415c8479bb6f7cc19eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":440},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a45a66aaa4244886a6d31ff3ca1586e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":171},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad04744eb594ce09f2f622aec8d87c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":171},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33546134487c44dd81ed7a516fb6cb5b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":172.5},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f6f4c5f7c414e34aed0cfd4b3875633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":172.5},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"649a46476bd4403ab6fa981d5923aa6c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":172},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d26f81450d36477a9b845ab7b9afda5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":172},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3ac90a82f0b14970b03ceb5d52b84a4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":231},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51a9a4f94b7e4dcaa12677cd0988062f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":231},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3dc00c2be9d74127abbe4c00654dc099",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":231},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca9135e0c75b4dfcb7a866f12d28dfb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":231},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"dc19334743e64f3f86d507f86e3fc9f6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":231},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87deadf92aba4b2d99f938173c9ddc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":231},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"a880a493a99049728df086abda2d403e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":291},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5502efe7c5f64f018adcf331470afde7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":291},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82c78801e0fb473f9387fa67d13bd0fd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":291},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1fceda757a24a6eacec3a050fa999ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":291},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d01477580c2243c3a5a347940aaf3685",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":291},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55f389cbf0d8483c8cae4003a67d5c8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":291},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c6eeed13d8a947ba837967286fca9ee1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":341},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064ba0aeea04452c96abb4e74a4b93a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":341},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acfb862e637d41f9bf738e703444a7ec",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":341},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8258e5ad8b774badb4846496e461d942",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":341},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"100cce5b6dd14b819cb2852d34516e45",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":341},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8fa44d5185e4cb0b8325a5abd5c0ba1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":341},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"22ccaf2cd8984b7eaf741087a6c6e647",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":390},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abd3c711d714ffdb69e92eb66c8b6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":390},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50561a18d62441eb9aa346d20dc08abe",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ffbb98fd4e42fcb39478ce8794d589",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e2368f65d36a40e2916ca667cde5a30b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"776c1df78ad747c89f514a741d038b87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0e9d3e5d64624c6096cf6253a6259f1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":440},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c22d7e1fe03453fbb8d107e5733523d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":440},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81733b2bf75c4718b25e5abe284ab25c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":440},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ea887b1d28244279ca019303eba1b99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":440},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"433ad43360d54a1f94c75971346426cf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":440},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"205165790d2d40259696e7c7fce508ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":440},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d4731be7feb146f8aa38bed5dc8e135e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":440},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f647422059a942d3a14912411f3b31a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":440},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"558954b78a58446fa9fb2d78d61455c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":484},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09a2df3597e4ec691cd7fceec712538",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":484},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"e2a1b1332eb64ed881ebc2919687eff9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":489},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"744659d21f844e669e4414a3bd71cd36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":489},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8fdf52216e014b16b3e7dd3e2e08bda2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":489},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31446c9f3e4c42ad9800328af98f57d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":489},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4d1370ac6e742038d6d74c728d558c7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":489},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50ade17a3ed640a885f4ef304e9d1852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":489},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"32f92fe4ed2244ba9c256c050de748d2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":489},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ed359ffed74e5091e4386c4e02515e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":489},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b38dc6f47db7437ab0bd3b9e0f3993c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":489},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55709500b16844fc99d144ddb0c1f77d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":489},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdc4edd1a49f40cfa435129a5dafc068",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d424073009b9429a81e341684ebdecf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e53bf34c7ffa4f628a1b8da34577af58",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":537},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"204e3531a78f44f3a3bc775ec1ed691b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":537},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9e03b900121a44798ec8b6b70541e3a6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":537},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd436bbaf60c41f79d7f0d439cc234be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":537},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"580f0c60f0634f6fbc64bf15b6bc1bff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1050,
              "y":220},
            "size":{
              "width":187,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcf33d3b60b34b0793df7bd3245e8099",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1050,
                  "y":220},
                "size":{
                  "width":187,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e4e3c1ccf194779ab4070fb163ad169",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":590},
            "size":{
              "width":836,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/增值服务设置/u65_line.png"}},
{
          "id":"c2c87218dc0948f6887c096574bc7ac6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":630},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "816de8c63d804e7ebbfec19556da1794":{
      "scriptId":"u0"},
    "3c29017471d74b3faa414b873a0afa7c":{
      "scriptId":"u1"},
    "17483bc31e824a8e9f3d3bac38583a8b":{
      "scriptId":"u2"},
    "b0805bd3ad914eeb9bcd6d0ea8c42a63":{
      "scriptId":"u3"},
    "009881ea0fe6436bbb0f95aa066f2ada":{
      "scriptId":"u4"},
    "3ad8c1265cb6492f90cfd18dc287a746":{
      "scriptId":"u5"},
    "195e626e7f64415c8479bb6f7cc19eb2":{
      "scriptId":"u6"},
    "a45a66aaa4244886a6d31ff3ca1586e5":{
      "scriptId":"u7"},
    "fad04744eb594ce09f2f622aec8d87c4":{
      "scriptId":"u8"},
    "33546134487c44dd81ed7a516fb6cb5b":{
      "scriptId":"u9"},
    "4f6f4c5f7c414e34aed0cfd4b3875633":{
      "scriptId":"u10"},
    "649a46476bd4403ab6fa981d5923aa6c":{
      "scriptId":"u11"},
    "d26f81450d36477a9b845ab7b9afda5f":{
      "scriptId":"u12"},
    "3ac90a82f0b14970b03ceb5d52b84a4a":{
      "scriptId":"u13"},
    "51a9a4f94b7e4dcaa12677cd0988062f":{
      "scriptId":"u14"},
    "3dc00c2be9d74127abbe4c00654dc099":{
      "scriptId":"u15"},
    "ca9135e0c75b4dfcb7a866f12d28dfb6":{
      "scriptId":"u16"},
    "dc19334743e64f3f86d507f86e3fc9f6":{
      "scriptId":"u17"},
    "87deadf92aba4b2d99f938173c9ddc57":{
      "scriptId":"u18"},
    "a880a493a99049728df086abda2d403e":{
      "scriptId":"u19"},
    "5502efe7c5f64f018adcf331470afde7":{
      "scriptId":"u20"},
    "82c78801e0fb473f9387fa67d13bd0fd":{
      "scriptId":"u21"},
    "a1fceda757a24a6eacec3a050fa999ce":{
      "scriptId":"u22"},
    "d01477580c2243c3a5a347940aaf3685":{
      "scriptId":"u23"},
    "55f389cbf0d8483c8cae4003a67d5c8f":{
      "scriptId":"u24"},
    "c6eeed13d8a947ba837967286fca9ee1":{
      "scriptId":"u25"},
    "064ba0aeea04452c96abb4e74a4b93a3":{
      "scriptId":"u26"},
    "acfb862e637d41f9bf738e703444a7ec":{
      "scriptId":"u27"},
    "8258e5ad8b774badb4846496e461d942":{
      "scriptId":"u28"},
    "100cce5b6dd14b819cb2852d34516e45":{
      "scriptId":"u29"},
    "c8fa44d5185e4cb0b8325a5abd5c0ba1":{
      "scriptId":"u30"},
    "22ccaf2cd8984b7eaf741087a6c6e647":{
      "scriptId":"u31"},
    "7abd3c711d714ffdb69e92eb66c8b6cf":{
      "scriptId":"u32"},
    "50561a18d62441eb9aa346d20dc08abe":{
      "scriptId":"u33"},
    "d1ffbb98fd4e42fcb39478ce8794d589":{
      "scriptId":"u34"},
    "e2368f65d36a40e2916ca667cde5a30b":{
      "scriptId":"u35"},
    "776c1df78ad747c89f514a741d038b87":{
      "scriptId":"u36"},
    "0e9d3e5d64624c6096cf6253a6259f1a":{
      "scriptId":"u37"},
    "5c22d7e1fe03453fbb8d107e5733523d":{
      "scriptId":"u38"},
    "81733b2bf75c4718b25e5abe284ab25c":{
      "scriptId":"u39"},
    "0ea887b1d28244279ca019303eba1b99":{
      "scriptId":"u40"},
    "433ad43360d54a1f94c75971346426cf":{
      "scriptId":"u41"},
    "205165790d2d40259696e7c7fce508ea":{
      "scriptId":"u42"},
    "d4731be7feb146f8aa38bed5dc8e135e":{
      "scriptId":"u43"},
    "f647422059a942d3a14912411f3b31a1":{
      "scriptId":"u44"},
    "558954b78a58446fa9fb2d78d61455c5":{
      "scriptId":"u45"},
    "c09a2df3597e4ec691cd7fceec712538":{
      "scriptId":"u46"},
    "e2a1b1332eb64ed881ebc2919687eff9":{
      "scriptId":"u47"},
    "744659d21f844e669e4414a3bd71cd36":{
      "scriptId":"u48"},
    "8fdf52216e014b16b3e7dd3e2e08bda2":{
      "scriptId":"u49"},
    "31446c9f3e4c42ad9800328af98f57d8":{
      "scriptId":"u50"},
    "b4d1370ac6e742038d6d74c728d558c7":{
      "scriptId":"u51"},
    "50ade17a3ed640a885f4ef304e9d1852":{
      "scriptId":"u52"},
    "32f92fe4ed2244ba9c256c050de748d2":{
      "scriptId":"u53"},
    "69ed359ffed74e5091e4386c4e02515e":{
      "scriptId":"u54"},
    "b38dc6f47db7437ab0bd3b9e0f3993c6":{
      "scriptId":"u55"},
    "55709500b16844fc99d144ddb0c1f77d":{
      "scriptId":"u56"},
    "fdc4edd1a49f40cfa435129a5dafc068":{
      "scriptId":"u57"},
    "d424073009b9429a81e341684ebdecf1":{
      "scriptId":"u58"},
    "e53bf34c7ffa4f628a1b8da34577af58":{
      "scriptId":"u59"},
    "204e3531a78f44f3a3bc775ec1ed691b":{
      "scriptId":"u60"},
    "9e03b900121a44798ec8b6b70541e3a6":{
      "scriptId":"u61"},
    "fd436bbaf60c41f79d7f0d439cc234be":{
      "scriptId":"u62"},
    "580f0c60f0634f6fbc64bf15b6bc1bff":{
      "scriptId":"u63"},
    "bcf33d3b60b34b0793df7bd3245e8099":{
      "scriptId":"u64"},
    "1e4e3c1ccf194779ab4070fb163ad169":{
      "scriptId":"u65"},
    "c2c87218dc0948f6887c096574bc7ac6":{
      "scriptId":"u66"}}});