$axure.loadCurrentPage({
  "url":"审核.html",
  "generationDate":new Date(1428320976977.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"820a48a9b2f44c0aa6af712b8323118c",
    "type":"Axure:Page",
    "name":"审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"656bc5d7c72b462b8a346fa13bd64fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":78,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0cf2d0a64943e68db391a6039463bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":78,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0340d319e8e347c1a5ae9cd243d089d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":1196},
            "size":{
              "width":938,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/网点管理/u6_line.png"}},
{
          "id":"408bbc09134949fd84bc436e44df9bf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":71,
              "height":430}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4e870103324f8aad8bbfcf72a6023d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":80,
                  "y":100},
                "size":{
                  "width":71,
                  "height":430}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0711ac17587445d78201e9d6948f3473",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":161,
              "y":202},
            "size":{
              "width":53,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732f322add974fed96b2b2ee34f7b84f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":161,
                  "y":202},
                "size":{
                  "width":53,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e693bcff00b45eabcab369b6523ac27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":217,
              "y":356},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d5c075f4c542b195b79c3313ce5d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":356},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af314a555eff4043972695bd0cc32d78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":161,
              "y":781},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"203443e6c4eb470f8f40115c17d04137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":161,
                  "y":781},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9278f50187ca49ba863a60f83bfee0fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":817},
            "size":{
              "width":594,
              "height":344}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55ed9b3dcc2434db9a1a2eb7dd803cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":817},
                "size":{
                  "width":594,
                  "height":344}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u23.png"}},
{
          "id":"499ff2fff4de434789c3f0e7379f3ca8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1421},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6fefdebba68140f693f4e9e1a1a58a00",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":626},
            "size":{
              "width":229,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef7b594a7d54e719e5642ad87f5ca97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":626},
                "size":{
                  "width":229,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审核/u14.png"}},
{
          "id":"19ba5f920840493fb0b59434a9aa2cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":1229},
            "size":{
              "width":65,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ced35fe273841769fe4a697f0412bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85,
                  "y":1229},
                "size":{
                  "width":65,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dce764db73ee4668ab67d57e08f634b1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":1294},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d1ae00cb55914b52bd3851b82806ab3e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":1356},
            "size":{
              "width":938,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/网点管理/u6_line.png"}},
{
          "id":"bfae6e94c5e24da6a757c13d1a6b8865",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":547},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"548960c14cd543d399924d18c5aa73b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":547},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a4a2703faee414ab0ffaf618daf05e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":586},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d49a31d3594d7a9125477afe9a5669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":586},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06ffeea5e6474affbdb5ed3cf4b3108a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":452},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf04fd826b5f4738be7910b21f0005a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":452},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5f03ab68e34e3eaeb539f06f974f3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13ba2a5ced67410e8b26db2acada1f6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d5abc7524de4d5f9454b44fb3407dd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":114},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87d36112800848baa2fc52c69194c8c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":114},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c6e5c445294d7883ad4d06f8598f87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":216},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b8610ce51b94acd9915904e876da11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":216},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5276010279b04088982112d4696a2475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":264},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9aa02fa30994d23844e50f9493a5d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":264},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acd12c766b4a4bd09e744c9434bbbdac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":217,
              "y":314},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a13a209aed247aaa174bfe4a4f76e04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":217,
                  "y":314},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65b616fd08a24cd894149cfa45334ff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":356},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58b5f92af3d4ce2849458a99c838d41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":356},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32964b4f403742e1bb4a83ff2e71e086",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":547},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bab3c76c1c2941bba6b6ebe3a75ba781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":547},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ce17a3ff70a4bc6a9a7252bada114c8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":85,
              "y":80},
            "size":{
              "width":938,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/网点管理/u6_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "656bc5d7c72b462b8a346fa13bd64fa7":{
      "scriptId":"u0"},
    "6f0cf2d0a64943e68db391a6039463bb":{
      "scriptId":"u1"},
    "0340d319e8e347c1a5ae9cd243d089d9":{
      "scriptId":"u2"},
    "408bbc09134949fd84bc436e44df9bf2":{
      "scriptId":"u3"},
    "8d4e870103324f8aad8bbfcf72a6023d":{
      "scriptId":"u4"},
    "0711ac17587445d78201e9d6948f3473":{
      "scriptId":"u5"},
    "732f322add974fed96b2b2ee34f7b84f":{
      "scriptId":"u6"},
    "0e693bcff00b45eabcab369b6523ac27":{
      "scriptId":"u7"},
    "11d5c075f4c542b195b79c3313ce5d20":{
      "scriptId":"u8"},
    "af314a555eff4043972695bd0cc32d78":{
      "scriptId":"u9"},
    "203443e6c4eb470f8f40115c17d04137":{
      "scriptId":"u10"},
    "9278f50187ca49ba863a60f83bfee0fe":{
      "scriptId":"u11"},
    "e55ed9b3dcc2434db9a1a2eb7dd803cf":{
      "scriptId":"u12"},
    "499ff2fff4de434789c3f0e7379f3ca8":{
      "scriptId":"u13"},
    "6fefdebba68140f693f4e9e1a1a58a00":{
      "scriptId":"u14"},
    "9ef7b594a7d54e719e5642ad87f5ca97":{
      "scriptId":"u15"},
    "19ba5f920840493fb0b59434a9aa2cfc":{
      "scriptId":"u16"},
    "9ced35fe273841769fe4a697f0412bf6":{
      "scriptId":"u17"},
    "dce764db73ee4668ab67d57e08f634b1":{
      "scriptId":"u18"},
    "d1ae00cb55914b52bd3851b82806ab3e":{
      "scriptId":"u19"},
    "bfae6e94c5e24da6a757c13d1a6b8865":{
      "scriptId":"u20"},
    "548960c14cd543d399924d18c5aa73b9":{
      "scriptId":"u21"},
    "6a4a2703faee414ab0ffaf618daf05e0":{
      "scriptId":"u22"},
    "e5d49a31d3594d7a9125477afe9a5669":{
      "scriptId":"u23"},
    "06ffeea5e6474affbdb5ed3cf4b3108a":{
      "scriptId":"u24"},
    "cf04fd826b5f4738be7910b21f0005a5":{
      "scriptId":"u25"},
    "4b5f03ab68e34e3eaeb539f06f974f3e":{
      "scriptId":"u26"},
    "13ba2a5ced67410e8b26db2acada1f6d":{
      "scriptId":"u27"},
    "2d5abc7524de4d5f9454b44fb3407dd5":{
      "scriptId":"u28"},
    "87d36112800848baa2fc52c69194c8c2":{
      "scriptId":"u29"},
    "11c6e5c445294d7883ad4d06f8598f87":{
      "scriptId":"u30"},
    "0b8610ce51b94acd9915904e876da11d":{
      "scriptId":"u31"},
    "5276010279b04088982112d4696a2475":{
      "scriptId":"u32"},
    "d9aa02fa30994d23844e50f9493a5d0b":{
      "scriptId":"u33"},
    "acd12c766b4a4bd09e744c9434bbbdac":{
      "scriptId":"u34"},
    "1a13a209aed247aaa174bfe4a4f76e04":{
      "scriptId":"u35"},
    "65b616fd08a24cd894149cfa45334ff6":{
      "scriptId":"u36"},
    "c58b5f92af3d4ce2849458a99c838d41":{
      "scriptId":"u37"},
    "32964b4f403742e1bb4a83ff2e71e086":{
      "scriptId":"u38"},
    "bab3c76c1c2941bba6b6ebe3a75ba781":{
      "scriptId":"u39"},
    "9ce17a3ff70a4bc6a9a7252bada114c8":{
      "scriptId":"u40"}}});