$axure.loadCurrentPage({
  "url":"基本信息_1.html",
  "generationDate":new Date(1428320976466.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a0d1b9954b549119e0b85a067fa73d4",
    "type":"Axure:Page",
    "name":"基本信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eb69ca7eadd8424fb2b590b0050bb12c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":119},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46a9318e85d641728dad61a1536b76b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":119},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3862fb7ae784938866561cda34b706b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":114},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a358accbe5d488d92b8349413fda9a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":114},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"6b6044e478a54469879aee2db75429a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":156},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1abe0633b4847238f1fa820fd6527ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":156},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9eab452ee99346dc91d59904bb8b96a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":194},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb4ac7bde3c4145a0c7fb8cc820721d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":194},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54103fc0aed0410fb6a9ee4a4c679bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":231},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7aff6cadf8e4d6b901ef9d8fa98bdde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":231},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4a233c3639d47a7a14b33a66df1bdaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":283},
            "size":{
              "width":82,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"709fa6e013db4d78804557d3b36c55c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":283},
                "size":{
                  "width":82,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8268f84cd31b40c3b5eac9762d4f2daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":187},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31831082a56a4a929c96ec0241052d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":187},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"c0a5e7c42dd448f49cb6001852c8ce19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":224},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f12ce5483bc142e58e8032df389359e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":224},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"b174cdfc0375485696cae3b7cf03a757",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":274},
            "size":{
              "width":119,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8bd7e406785435ca5e69f16c16b8f0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":274},
                "size":{
                  "width":119,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u13.png"}},
{
          "id":"0ef8228e07a9480d9995e16ce010a46d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":157},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"676e518d8f8c4b24bc4f82a78e6743df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":157},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"8850a8e87cc34404a020fbe9c9b1f7dc",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":157},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602f0cbe8564495d9ba175892f23038b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":157},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"98bb8b00dcb647959fb13017de51f5b1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":365},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9d9c758cee26485fbf1c0c7a7f48a60e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"25px",
            "location":{
              "x":58,
              "y":43},
            "size":{
              "width":101,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48600d78061248ad9f3b5b3ec58796e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"25px",
                "location":{
                  "x":58,
                  "y":43},
                "size":{
                  "width":101,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "eb69ca7eadd8424fb2b590b0050bb12c":{
      "scriptId":"u0"},
    "46a9318e85d641728dad61a1536b76b0":{
      "scriptId":"u1"},
    "c3862fb7ae784938866561cda34b706b":{
      "scriptId":"u2"},
    "9a358accbe5d488d92b8349413fda9a5":{
      "scriptId":"u3"},
    "6b6044e478a54469879aee2db75429a9":{
      "scriptId":"u4"},
    "f1abe0633b4847238f1fa820fd6527ed":{
      "scriptId":"u5"},
    "9eab452ee99346dc91d59904bb8b96a0":{
      "scriptId":"u6"},
    "ccb4ac7bde3c4145a0c7fb8cc820721d":{
      "scriptId":"u7"},
    "54103fc0aed0410fb6a9ee4a4c679bbb":{
      "scriptId":"u8"},
    "d7aff6cadf8e4d6b901ef9d8fa98bdde":{
      "scriptId":"u9"},
    "c4a233c3639d47a7a14b33a66df1bdaa":{
      "scriptId":"u10"},
    "709fa6e013db4d78804557d3b36c55c3":{
      "scriptId":"u11"},
    "8268f84cd31b40c3b5eac9762d4f2daa":{
      "scriptId":"u12"},
    "31831082a56a4a929c96ec0241052d91":{
      "scriptId":"u13"},
    "c0a5e7c42dd448f49cb6001852c8ce19":{
      "scriptId":"u14"},
    "f12ce5483bc142e58e8032df389359e3":{
      "scriptId":"u15"},
    "b174cdfc0375485696cae3b7cf03a757":{
      "scriptId":"u16"},
    "c8bd7e406785435ca5e69f16c16b8f0a":{
      "scriptId":"u17"},
    "0ef8228e07a9480d9995e16ce010a46d":{
      "scriptId":"u18"},
    "676e518d8f8c4b24bc4f82a78e6743df":{
      "scriptId":"u19"},
    "8850a8e87cc34404a020fbe9c9b1f7dc":{
      "scriptId":"u20"},
    "602f0cbe8564495d9ba175892f23038b":{
      "scriptId":"u21"},
    "98bb8b00dcb647959fb13017de51f5b1":{
      "scriptId":"u22"},
    "9d9c758cee26485fbf1c0c7a7f48a60e":{
      "scriptId":"u23"},
    "48600d78061248ad9f3b5b3ec58796e0":{
      "scriptId":"u24"}}});