$axure.loadCurrentPage({
  "url":"申请承运商.html",
  "generationDate":new Date(1428320976662.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2eefa9a71365415f98601748c6907849",
    "type":"Axure:Page",
    "name":"申请承运商",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"46fd225555d04edf8b51d4dfd56c0679",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ed1f88da85a4ba79f9c404434f8d58f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a5ec80ed91a4f89ba567f0d74baf922",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"10c9e103731440a3b301c08ed90ab0e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":38,
              "y":157},
            "size":{
              "width":84,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"721a5891721b445d85524f31472017df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":38,
                  "y":157},
                "size":{
                  "width":84,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d77bd3a1a6db48b6ab64df4b7569c72a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":263},
            "size":{
              "width":162,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d19070304146486ba5e7f40d39f28f8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":173},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f39e7f662a4db4a631dbe7e10037eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":173},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"c856179abad64dcd8b85ade8f11d753e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":213},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f88fa080f4b43d483e14b56d7f4a03f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":213},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"a6600e82b50c425e81f6e5cb5bc1a0bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":313},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be646c495a764272b6b1a4bea63161a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":313},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"bc8dc0a0f2434bfda24a3e4deaec46f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":358},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec9f5515f1ce4cf5a171fcd1308a5a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":358},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"f02c46a785104431aeb77b75a7122e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":407},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75c94adb31bc43b4933fc9b616cd3f15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":407},
                "size":{
                  "width":200,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/承运商入驻申请/u18.png"}},
{
          "id":"1bb30aaf54804b3a94635d07da5f0e17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":38,
              "y":520},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d609d3086cda4f3b918e145ddef91133",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":38,
                  "y":520},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"3a9dcbaa7da647b79f30b98ce5f63ff4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":470},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/承运商入驻申请/u14_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "46fd225555d04edf8b51d4dfd56c0679":{
      "scriptId":"u0"},
    "3ed1f88da85a4ba79f9c404434f8d58f":{
      "scriptId":"u1"},
    "7a5ec80ed91a4f89ba567f0d74baf922":{
      "scriptId":"u2"},
    "10c9e103731440a3b301c08ed90ab0e2":{
      "scriptId":"u3"},
    "721a5891721b445d85524f31472017df":{
      "scriptId":"u4"},
    "d77bd3a1a6db48b6ab64df4b7569c72a":{
      "scriptId":"u5"},
    "d19070304146486ba5e7f40d39f28f8b":{
      "scriptId":"u6"},
    "79f39e7f662a4db4a631dbe7e10037eb":{
      "scriptId":"u7"},
    "c856179abad64dcd8b85ade8f11d753e":{
      "scriptId":"u8"},
    "8f88fa080f4b43d483e14b56d7f4a03f":{
      "scriptId":"u9"},
    "a6600e82b50c425e81f6e5cb5bc1a0bd":{
      "scriptId":"u10"},
    "be646c495a764272b6b1a4bea63161a5":{
      "scriptId":"u11"},
    "bc8dc0a0f2434bfda24a3e4deaec46f6":{
      "scriptId":"u12"},
    "ec9f5515f1ce4cf5a171fcd1308a5a9f":{
      "scriptId":"u13"},
    "f02c46a785104431aeb77b75a7122e15":{
      "scriptId":"u14"},
    "75c94adb31bc43b4933fc9b616cd3f15":{
      "scriptId":"u15"},
    "1bb30aaf54804b3a94635d07da5f0e17":{
      "scriptId":"u16"},
    "d609d3086cda4f3b918e145ddef91133":{
      "scriptId":"u17"},
    "3a9dcbaa7da647b79f30b98ce5f63ff4":{
      "scriptId":"u18"}}});