$axure.loadCurrentPage({
  "url":"物流商订单流程.html",
  "generationDate":new Date(1428320973748.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"521edbfe0a3540e2bb68e036c5bad780",
    "type":"Axure:Page",
    "name":"物流商订单流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c95fa59fdc2e4766b8068888930b56c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":120,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdd6253c3c504d77aa22ca4557c0b660",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":120,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u0.png"}},
{
          "id":"f1f5a58e2f014a649174d169b228dc7e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b96260fcf54e4fd7b3e34ae543f840f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"e226386d06b942a0a6bdb51f876d46ed",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ffad48387474c5b8a397c7b137bb549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"cb43548f291b4d90a53297232ada2eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":124},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ba3b319d64349efa162abfcccffec2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":124},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1b7dba34b37410a8fc92189b737eace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":310,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db5072fe6f2495f83b675f4fe99ec3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":310,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"ad31c0fdc6054d40a42609d5ae8553b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":310,
              "y":210},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7da2a3ab5d2492782e1e5b4a011fc37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":310,
                  "y":210},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"ff96789b53304bf1869589bd90d262af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":210},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2fb192d544402aacbc0d0b6068695d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":210},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23d07cb3578493e8b827e778e7be9f3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"310f3796511442f3928a7a976102e0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"6511b4ab1c64437b9cbda7c9b687bb85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":124},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9166d5ec65e34fbb94e5d728805948ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":124},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95aa5a6adb114407983d25d13f065240",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":500,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b987b8fff48c49bc902bc90192c26347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":500,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"008df9ba8a624c2a96d8bd6c8ee26e4e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6235c516583341689bc912cb435b26be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"a25002c439d74bc1ab26e62cab6a49d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":643,
              "y":124},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c86e019cf644dd6ad10902c195aec76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":643,
                  "y":124},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c23cf472a28456b938a1309080ddd11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":690,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38b79ebedeb481499f0293ad9362792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":690,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"d0a6b178dfc445f691c86d113d8f43d3",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcb847a2affe49d3b813c43edba7d10c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"d836a00ef1004c48b6d49dfc8397ee3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":833,
              "y":124},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8efa33cade14ce09a0586bed019f85c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":833,
                  "y":124},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ffb44c7bf204f0798d9ffb84d2b1a0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":880,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6da0fc717cc544febd86a10b9377ab5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":880,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"52c9635be37749498e77235d226be4fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":354},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ae5876bd4fd4f1eb19b7fadbb4a1c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":354},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c95fa59fdc2e4766b8068888930b56c1":{
      "scriptId":"u0"},
    "bdd6253c3c504d77aa22ca4557c0b660":{
      "scriptId":"u1"},
    "f1f5a58e2f014a649174d169b228dc7e":{
      "scriptId":"u2"},
    "b96260fcf54e4fd7b3e34ae543f840f9":{
      "scriptId":"u3"},
    "e226386d06b942a0a6bdb51f876d46ed":{
      "scriptId":"u4"},
    "1ffad48387474c5b8a397c7b137bb549":{
      "scriptId":"u5"},
    "cb43548f291b4d90a53297232ada2eea":{
      "scriptId":"u6"},
    "2ba3b319d64349efa162abfcccffec2e":{
      "scriptId":"u7"},
    "a1b7dba34b37410a8fc92189b737eace":{
      "scriptId":"u8"},
    "8db5072fe6f2495f83b675f4fe99ec3a":{
      "scriptId":"u9"},
    "ad31c0fdc6054d40a42609d5ae8553b6":{
      "scriptId":"u10"},
    "e7da2a3ab5d2492782e1e5b4a011fc37":{
      "scriptId":"u11"},
    "ff96789b53304bf1869589bd90d262af":{
      "scriptId":"u12"},
    "5c2fb192d544402aacbc0d0b6068695d":{
      "scriptId":"u13"},
    "d23d07cb3578493e8b827e778e7be9f3":{
      "scriptId":"u14"},
    "310f3796511442f3928a7a976102e0cb":{
      "scriptId":"u15"},
    "6511b4ab1c64437b9cbda7c9b687bb85":{
      "scriptId":"u16"},
    "9166d5ec65e34fbb94e5d728805948ea":{
      "scriptId":"u17"},
    "95aa5a6adb114407983d25d13f065240":{
      "scriptId":"u18"},
    "b987b8fff48c49bc902bc90192c26347":{
      "scriptId":"u19"},
    "008df9ba8a624c2a96d8bd6c8ee26e4e":{
      "scriptId":"u20"},
    "6235c516583341689bc912cb435b26be":{
      "scriptId":"u21"},
    "a25002c439d74bc1ab26e62cab6a49d7":{
      "scriptId":"u22"},
    "6c86e019cf644dd6ad10902c195aec76":{
      "scriptId":"u23"},
    "6c23cf472a28456b938a1309080ddd11":{
      "scriptId":"u24"},
    "e38b79ebedeb481499f0293ad9362792":{
      "scriptId":"u25"},
    "d0a6b178dfc445f691c86d113d8f43d3":{
      "scriptId":"u26"},
    "dcb847a2affe49d3b813c43edba7d10c":{
      "scriptId":"u27"},
    "d836a00ef1004c48b6d49dfc8397ee3f":{
      "scriptId":"u28"},
    "f8efa33cade14ce09a0586bed019f85c":{
      "scriptId":"u29"},
    "7ffb44c7bf204f0798d9ffb84d2b1a0e":{
      "scriptId":"u30"},
    "6da0fc717cc544febd86a10b9377ab5b":{
      "scriptId":"u31"},
    "52c9635be37749498e77235d226be4fd":{
      "scriptId":"u32"},
    "3ae5876bd4fd4f1eb19b7fadbb4a1c96":{
      "scriptId":"u33"}}});