$axure.loadCurrentPage({
  "url":"添加物流园.html",
  "generationDate":new Date(1428320978918.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3443b110789347b098d992ed5cafceae",
    "type":"Axure:Page",
    "name":"添加物流园",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"27bb99fdae8b4935b7b112a8513c5207",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e02e50c9e14680a135b1bc5628904e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15583f47c1f742f6ab1f6d914808d2f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"6924f35c20cb4667936b3a02bbb316c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":40,
              "y":184},
            "size":{
              "width":79,
              "height":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f8c4f8c2ce4680bf67672c39cc8ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":40,
                  "y":184},
                "size":{
                  "width":79,
                  "height":256}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9045aead75ca49908a79a82610325983",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":191},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed704c57e344c6d8d66cabc6a8f4ded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":191},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"a260719bee6e4d01838908c3018f0fef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":285},
            "size":{
              "width":560,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63c8a074b91f49f59c15505d4dda2eeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":285},
                "size":{
                  "width":560,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加物流园/u7.png"}},
{
          "id":"825d9cd6ece04b9ab185f2d6b99362f6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":245},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e204f22d3f6246fba431f2c81ba01270",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":245},
            "size":{
              "width":90,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e1f801357e9e48eb8a01bfb7c72608bd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":745},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"abb51a16e50940acb71ffa31a494ba9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":346},
            "size":{
              "width":594,
              "height":344}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04f9fb0174294080b8ba9bef3963601f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":346},
                "size":{
                  "width":594,
                  "height":344}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加网点/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "27bb99fdae8b4935b7b112a8513c5207":{
      "scriptId":"u0"},
    "31e02e50c9e14680a135b1bc5628904e":{
      "scriptId":"u1"},
    "15583f47c1f742f6ab1f6d914808d2f8":{
      "scriptId":"u2"},
    "6924f35c20cb4667936b3a02bbb316c7":{
      "scriptId":"u3"},
    "01f8c4f8c2ce4680bf67672c39cc8ab1":{
      "scriptId":"u4"},
    "9045aead75ca49908a79a82610325983":{
      "scriptId":"u5"},
    "1ed704c57e344c6d8d66cabc6a8f4ded":{
      "scriptId":"u6"},
    "a260719bee6e4d01838908c3018f0fef":{
      "scriptId":"u7"},
    "63c8a074b91f49f59c15505d4dda2eeb":{
      "scriptId":"u8"},
    "825d9cd6ece04b9ab185f2d6b99362f6":{
      "scriptId":"u9"},
    "e204f22d3f6246fba431f2c81ba01270":{
      "scriptId":"u10"},
    "e1f801357e9e48eb8a01bfb7c72608bd":{
      "scriptId":"u11"},
    "abb51a16e50940acb71ffa31a494ba9f":{
      "scriptId":"u12"},
    "04f9fb0174294080b8ba9bef3963601f":{
      "scriptId":"u13"}}});