$axure.loadCurrentPage({
  "url":"订单详细（运输中）.html",
  "generationDate":new Date(1428320978350.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"04bd347fc76c49569a49bdfcabd4af06",
    "type":"Axure:Page",
    "name":"订单详细（运输中）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c15b31a7617f48b1bcaeb779dea78476",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":30,
              "y":54},
            "size":{
              "width":831,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"744387d6c580444d8e4bfbdeff56fa9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":30,
                  "y":54},
                "size":{
                  "width":831,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u0.png"}},
{
          "id":"8fdabca787d343a4967cbe68ab13b312",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":243},
            "size":{
              "width":830,
              "height":1087},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed219ee6b14405589719abd5a1eaea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":243},
                "size":{
                  "width":830,
                  "height":1087},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（已受理）/u2.png"}},
{
          "id":"6642df3558c94b4a9f4009757880fb35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":20},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dabae811d7bb4b0885870d74be1c5e85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":20},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ff2ea2960584f699c4811bbb03df2d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":17},
            "size":{
              "width":74,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff19ed7c25149d0b6c9960f7fa13efe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":17},
                "size":{
                  "width":74,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查找列表/u75.png"}},
{
          "id":"f17c39da04d04c05b5049fcd6d9a5144",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":263},
            "size":{
              "width":164,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46d646ccfbf4eac90da82eb057696a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":263},
                "size":{
                  "width":164,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad9f4c89ff294fe6b54b001f27047240",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":439},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u109_line.png"}},
{
          "id":"4df1d24c06ba48d18a386a4948d6422f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":459},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1488cdcc7d2f41fe8b55441c5652d9fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":459},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7aa1f66d368247e9ad96b77a56a24cf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":507},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04767acb001346d48235ab1095190e53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":507},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33bec9257d6449478a8d977c196247c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":294.5,
              "y":54},
            "size":{
              "width":65,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"721b405a817849de9e33a7d040a14bd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":294.5,
                  "y":54},
                "size":{
                  "width":65,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（已受理）/u15.png"}},
{
          "id":"f1173cf7736247b887279a0996661834",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":64},
            "size":{
              "width":367,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0963c066c324a11835c3fee9776f12e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":64},
                "size":{
                  "width":367,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85040526c7534b87a643e478faaccd07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":32,
              "y":181},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2694d5720c241a281d1a1fbf425d852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":32,
                  "y":181},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bfe270817f24d2088b4c0f6ef119fbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":270},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7076b26e4d8e44b08d5df2a001c335c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":270},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4a716770e6743699fde3e187f377b67",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":450},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"ffba132680a54ddd98008fa8ba3b625b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":493},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbcdfd72ca144676a6897900b6d7a8bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":493},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"345bc2050bc04914831feacdfaa331a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":720},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"cf4a6b99703c45cca070fc67f4177c51",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":744},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c896e626a2c249cd938ee81c802617d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":744},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81ad190737a246108fd6148a53652f3a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":960},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"7bc450ba5ee34945be1e749cbb4c5413",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":268,
              "y":1216},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"267e9967301a483aa6d58189bd6a0b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":268,
                  "y":1216},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ffb0f91327e4709a3a521a950525283",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":268,
              "y":1000},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0792b90fbf914704a3cf138862823bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":268,
                  "y":1000},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eafc0605b89f4956987483bf5ba8f712",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1186},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"103c738045324a1ca226302cb5e6c9fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":31,
              "y":208},
            "size":{
              "width":830,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f7f647373540718194479a89287ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":31,
                  "y":208},
                "size":{
                  "width":830,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u22.png"}},
{
          "id":"4ae54c6ad6b6457eaa5dd0bb859945c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":42,
              "y":215},
            "size":{
              "width":256,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"964739384a6a4b849872d598bb62eb00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":42,
                  "y":215},
                "size":{
                  "width":256,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642fe9b7f89b4acda75717f38cf007fd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":244},
            "size":{
              "width":10,
              "height":1086},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单详细（已受理）/u39_line.png"}},
{
          "id":"e733bafc91c646aab74b2212fe1ae94d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":284,
              "y":304},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"925206363650452893157d621b6fb0a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":284,
                  "y":304},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9410da9d375c4273a8aef98d3785f077",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":361,
              "y":304},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e660af3cb14ac4abad84902462b56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":361,
                  "y":304},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b975c7c75f934a25b3c05941c9bb24a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":32,
              "y":105},
            "size":{
              "width":829,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6af52a6221840eab2f9675b12888472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":32,
                  "y":105},
                "size":{
                  "width":829,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u27.png"}},
{
          "id":"f253b5c9d63c406991bef81d7b1cac14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":55,
              "y":120.5},
            "size":{
              "width":60,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f354a6f2c124c0fb9b94f6591317bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":55,
                  "y":120.5},
                "size":{
                  "width":60,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u29.png"}},
{
          "id":"c1775f4820de4a43849c07f8e0098a5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":120},
            "size":{
              "width":101,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7adf625fd7a94eb2bfc64063d79d9b13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":120},
                "size":{
                  "width":101,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（已受理）/u48.png"}},
{
          "id":"8a460cc4214d40fba0951458efbf8741",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":673,
              "y":128},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9cea7fe9d6d4a8b8d96d6695a14c857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":673,
                  "y":128},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0000d13323974ffb93e4a8880b5d9ede",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":361,
              "y":540},
            "size":{
              "width":338,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a608c67bbea47d8a81c9858f144015f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":361,
                  "y":540},
                "size":{
                  "width":338,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d782264f10147859d4ace12ec7a7755",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":284,
              "y":540},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1801e95b73742b68bd8900d8b380159",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":284,
                  "y":540},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eda5fc7448e7477898db13eba9b7d1ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":361,
              "y":786},
            "size":{
              "width":312,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887115ecf2a64594accd0d87284a1602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":361,
                  "y":786},
                "size":{
                  "width":312,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3326e70e3b44056a04628515bfd341c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "lineSpacing":"36px",
            "location":{
              "x":271,
              "y":786},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ca4246e29e4479b9b4a4bdfcf21940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "lineSpacing":"36px",
                "location":{
                  "x":271,
                  "y":786},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c16ee7382742739d8c80f8f8311068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1040},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6efeb95531848a2a8875d8def82d524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1040},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbfe33e56d594118b8960e45ba89992c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1040},
            "size":{
              "width":186,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149b52b3a556499caffba45852721226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1040},
                "size":{
                  "width":186,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65a599e3ff3e439f95ca2018a9f6ab16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1074},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70b9b5b728f147e6b5681752f9fc6f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1074},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5e955ba98414e46bb5329b97e730b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1074},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb0e520e4854fe6bd62a55e542b81b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1074},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62360eeb0fc1452bb530cef0904d2d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1110},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde543f39cba4afebdb4198306235416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1110},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2897ed17a3bb485c9bebc7a0c9963d9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1110},
            "size":{
              "width":218,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f8aa6594a704822b733e05b716b3f75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1110},
                "size":{
                  "width":218,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d310ceee0a6b45c181cf0dad4b978087",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1144},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5492988f2a9d469181dedc8defb15605",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1144},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b074ec648254671b433b92bec61e574",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":534,
              "y":1144},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc15ec222224dd2a6c2d4fe9aeab697",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":534,
                  "y":1144},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15d895b1b14d498ab2b9794c285832cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1264},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c901477e94bf4077b945f62a69681ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1264},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"223fe7439f134b1c87b45c919dae6e20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":32,
              "y":1344},
            "size":{
              "width":829,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e796ce37f8da4f23b7702b4e54224a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":32,
                  "y":1344},
                "size":{
                  "width":829,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u27.png"}},
{
          "id":"6e2ec4e181f1403292eaabe1614a493c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":55,
              "y":1359},
            "size":{
              "width":60,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"515ce156d99a43bf987d18751345a090",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":55,
                  "y":1359},
                "size":{
                  "width":60,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（待受理）/u29.png"}},
{
          "id":"5c03e96c7b3549759f3f6cbe43722d58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":720,
              "y":1367},
            "size":{
              "width":131,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6152c167881c460886ff6d19a8846d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":720,
                  "y":1367},
                "size":{
                  "width":131,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fc94c18427d41eeafb7c90c541fffec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":1359},
            "size":{
              "width":101,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb2a496921d241d2a4e1419959a8384a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":1359},
                "size":{
                  "width":101,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细（已受理）/u48.png"}},
{
          "id":"7e37a2274a264eac9c7618dbf0af8597",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":930,
              "y":128},
            "size":{
              "width":265,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80b0b1ae7cd04494b234259a4c649951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":930,
                  "y":128},
                "size":{
                  "width":265,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c15b31a7617f48b1bcaeb779dea78476":{
      "scriptId":"u0"},
    "744387d6c580444d8e4bfbdeff56fa9e":{
      "scriptId":"u1"},
    "8fdabca787d343a4967cbe68ab13b312":{
      "scriptId":"u2"},
    "6ed219ee6b14405589719abd5a1eaea8":{
      "scriptId":"u3"},
    "6642df3558c94b4a9f4009757880fb35":{
      "scriptId":"u4"},
    "dabae811d7bb4b0885870d74be1c5e85":{
      "scriptId":"u5"},
    "2ff2ea2960584f699c4811bbb03df2d6":{
      "scriptId":"u6"},
    "7ff19ed7c25149d0b6c9960f7fa13efe":{
      "scriptId":"u7"},
    "f17c39da04d04c05b5049fcd6d9a5144":{
      "scriptId":"u8"},
    "c46d646ccfbf4eac90da82eb057696a0":{
      "scriptId":"u9"},
    "ad9f4c89ff294fe6b54b001f27047240":{
      "scriptId":"u10"},
    "4df1d24c06ba48d18a386a4948d6422f":{
      "scriptId":"u11"},
    "1488cdcc7d2f41fe8b55441c5652d9fc":{
      "scriptId":"u12"},
    "7aa1f66d368247e9ad96b77a56a24cf4":{
      "scriptId":"u13"},
    "04767acb001346d48235ab1095190e53":{
      "scriptId":"u14"},
    "33bec9257d6449478a8d977c196247c6":{
      "scriptId":"u15"},
    "721b405a817849de9e33a7d040a14bd4":{
      "scriptId":"u16"},
    "f1173cf7736247b887279a0996661834":{
      "scriptId":"u17"},
    "b0963c066c324a11835c3fee9776f12e":{
      "scriptId":"u18"},
    "85040526c7534b87a643e478faaccd07":{
      "scriptId":"u19"},
    "f2694d5720c241a281d1a1fbf425d852":{
      "scriptId":"u20"},
    "6bfe270817f24d2088b4c0f6ef119fbf":{
      "scriptId":"u21"},
    "7076b26e4d8e44b08d5df2a001c335c8":{
      "scriptId":"u22"},
    "d4a716770e6743699fde3e187f377b67":{
      "scriptId":"u23"},
    "ffba132680a54ddd98008fa8ba3b625b":{
      "scriptId":"u24"},
    "cbcdfd72ca144676a6897900b6d7a8bb":{
      "scriptId":"u25"},
    "345bc2050bc04914831feacdfaa331a7":{
      "scriptId":"u26"},
    "cf4a6b99703c45cca070fc67f4177c51":{
      "scriptId":"u27"},
    "c896e626a2c249cd938ee81c802617d4":{
      "scriptId":"u28"},
    "81ad190737a246108fd6148a53652f3a":{
      "scriptId":"u29"},
    "7bc450ba5ee34945be1e749cbb4c5413":{
      "scriptId":"u30"},
    "267e9967301a483aa6d58189bd6a0b23":{
      "scriptId":"u31"},
    "1ffb0f91327e4709a3a521a950525283":{
      "scriptId":"u32"},
    "0792b90fbf914704a3cf138862823bc0":{
      "scriptId":"u33"},
    "eafc0605b89f4956987483bf5ba8f712":{
      "scriptId":"u34"},
    "103c738045324a1ca226302cb5e6c9fd":{
      "scriptId":"u35"},
    "35f7f647373540718194479a89287ecc":{
      "scriptId":"u36"},
    "4ae54c6ad6b6457eaa5dd0bb859945c4":{
      "scriptId":"u37"},
    "964739384a6a4b849872d598bb62eb00":{
      "scriptId":"u38"},
    "642fe9b7f89b4acda75717f38cf007fd":{
      "scriptId":"u39"},
    "e733bafc91c646aab74b2212fe1ae94d":{
      "scriptId":"u40"},
    "925206363650452893157d621b6fb0a4":{
      "scriptId":"u41"},
    "9410da9d375c4273a8aef98d3785f077":{
      "scriptId":"u42"},
    "e7e660af3cb14ac4abad84902462b56d":{
      "scriptId":"u43"},
    "b975c7c75f934a25b3c05941c9bb24a5":{
      "scriptId":"u44"},
    "a6af52a6221840eab2f9675b12888472":{
      "scriptId":"u45"},
    "f253b5c9d63c406991bef81d7b1cac14":{
      "scriptId":"u46"},
    "4f354a6f2c124c0fb9b94f6591317bb0":{
      "scriptId":"u47"},
    "c1775f4820de4a43849c07f8e0098a5b":{
      "scriptId":"u48"},
    "7adf625fd7a94eb2bfc64063d79d9b13":{
      "scriptId":"u49"},
    "8a460cc4214d40fba0951458efbf8741":{
      "scriptId":"u50"},
    "b9cea7fe9d6d4a8b8d96d6695a14c857":{
      "scriptId":"u51"},
    "0000d13323974ffb93e4a8880b5d9ede":{
      "scriptId":"u52"},
    "6a608c67bbea47d8a81c9858f144015f":{
      "scriptId":"u53"},
    "7d782264f10147859d4ace12ec7a7755":{
      "scriptId":"u54"},
    "f1801e95b73742b68bd8900d8b380159":{
      "scriptId":"u55"},
    "eda5fc7448e7477898db13eba9b7d1ed":{
      "scriptId":"u56"},
    "887115ecf2a64594accd0d87284a1602":{
      "scriptId":"u57"},
    "a3326e70e3b44056a04628515bfd341c":{
      "scriptId":"u58"},
    "67ca4246e29e4479b9b4a4bdfcf21940":{
      "scriptId":"u59"},
    "95c16ee7382742739d8c80f8f8311068":{
      "scriptId":"u60"},
    "c6efeb95531848a2a8875d8def82d524":{
      "scriptId":"u61"},
    "cbfe33e56d594118b8960e45ba89992c":{
      "scriptId":"u62"},
    "149b52b3a556499caffba45852721226":{
      "scriptId":"u63"},
    "65a599e3ff3e439f95ca2018a9f6ab16":{
      "scriptId":"u64"},
    "70b9b5b728f147e6b5681752f9fc6f81":{
      "scriptId":"u65"},
    "b5e955ba98414e46bb5329b97e730b00":{
      "scriptId":"u66"},
    "cbb0e520e4854fe6bd62a55e542b81b9":{
      "scriptId":"u67"},
    "62360eeb0fc1452bb530cef0904d2d06":{
      "scriptId":"u68"},
    "bde543f39cba4afebdb4198306235416":{
      "scriptId":"u69"},
    "2897ed17a3bb485c9bebc7a0c9963d9b":{
      "scriptId":"u70"},
    "7f8aa6594a704822b733e05b716b3f75":{
      "scriptId":"u71"},
    "d310ceee0a6b45c181cf0dad4b978087":{
      "scriptId":"u72"},
    "5492988f2a9d469181dedc8defb15605":{
      "scriptId":"u73"},
    "4b074ec648254671b433b92bec61e574":{
      "scriptId":"u74"},
    "9cc15ec222224dd2a6c2d4fe9aeab697":{
      "scriptId":"u75"},
    "15d895b1b14d498ab2b9794c285832cb":{
      "scriptId":"u76"},
    "c901477e94bf4077b945f62a69681ce8":{
      "scriptId":"u77"},
    "223fe7439f134b1c87b45c919dae6e20":{
      "scriptId":"u78"},
    "e796ce37f8da4f23b7702b4e54224a31":{
      "scriptId":"u79"},
    "6e2ec4e181f1403292eaabe1614a493c":{
      "scriptId":"u80"},
    "515ce156d99a43bf987d18751345a090":{
      "scriptId":"u81"},
    "5c03e96c7b3549759f3f6cbe43722d58":{
      "scriptId":"u82"},
    "6152c167881c460886ff6d19a8846d0e":{
      "scriptId":"u83"},
    "2fc94c18427d41eeafb7c90c541fffec":{
      "scriptId":"u84"},
    "cb2a496921d241d2a4e1419959a8384a":{
      "scriptId":"u85"},
    "7e37a2274a264eac9c7618dbf0af8597":{
      "scriptId":"u86"},
    "80b0b1ae7cd04494b234259a4c649951":{
      "scriptId":"u87"}}});