$axure.loadCurrentPage({
  "url":"发货地址.html",
  "generationDate":new Date(1428320976610.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb4ea7535eda4424bbb29821959d0fe7",
    "type":"Axure:Page",
    "name":"发货地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4b9f0784b1f840a6b450ed2f539dd9a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98e5de4acb04ce3ab17bfcff988d794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8624dd6e69044a1bde92cd515346acb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"cf30adbc171d441cae89c0661dad8a5a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":190},
            "size":{
              "width":700,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb16b35161f7420f92010ff4e1553f7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a7af5f3525f4111905c97c8001768c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF99},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u4.png"}},
{
              "id":"72e797f8d88d43a792482838045e9f8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85f59670d4da40f8889a07d5593610dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u14.png"}},
{
              "id":"b776439a0791428ea7edb76e22efcc40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f512f45c6ca54de19a3af14d104b85c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"2e45973772f847f499f633c7fec724e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08e8d355f6eb42b894151a5337d38e6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF99},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u6.png"}},
{
              "id":"087c8df117934be9bb6140a0b33d474a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6fd0dfd5978473aa8880986c08457a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u16.png"}},
{
              "id":"e970f08ebc3a42898deb63d88aab7bb3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":66},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee283efef5e14ab69e55400965912f84",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":66},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u26.png"}},
{
              "id":"01d36ba232944639bbfcfe7f5477fc37",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48564f3e77d742a6b313d2af0c8f363a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF99},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u4.png"}},
{
              "id":"0dc626ea9b884b4ea97e8f823c3c7c40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50eb5e3fa6aa450b8309b9b09b566fe4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u14.png"}},
{
              "id":"e67eef48c413440794ca9f58f36dc837",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":66},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"06118e19356c492188bbe237a251e34f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":66},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"209828756b0b4ba89cbf250a8aa20d9a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c8aecfd6e53438a926140b9cece2a72",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF99},
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u10.png"}},
{
              "id":"d7b84ae4235147c38d7c081c92895d19",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":200,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45e02fcaa47041af832bc93888646dcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u20.png"}},
{
              "id":"19f2303d00a1450fa8ca2fa6ab9994c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":66},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d99beb6f53b4245957fab5f61b3a266",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":66},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u30.png"}},
{
              "id":"87f58821050c4306af0254ad370f0b6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "location":{
                  "x":550,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e31d766e44449c195ba737bd32a7733",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF99},
                    "location":{
                      "x":550,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u12.png"}},
{
              "id":"6872b6f6f10c4091804055becd585af0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":30},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d42ae0700d624c329045debec4be43a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":550,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u22.png"}},
{
              "id":"85f9cff2a0104967960fab1b782e0c9f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":66},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c5f747de6aa4008b92c58f51ab5af6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":550,
                      "y":66},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u32.png"}}]},
{
          "id":"8ad2f0e5d4d244019f90c482bfc17b64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":40,
              "y":144},
            "size":{
              "width":130,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4dde7eb968646ef900c4d283dcb1a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":40,
                  "y":144},
                "size":{
                  "width":130,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收货地址/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4b9f0784b1f840a6b450ed2f539dd9a3":{
      "scriptId":"u0"},
    "c98e5de4acb04ce3ab17bfcff988d794":{
      "scriptId":"u1"},
    "d8624dd6e69044a1bde92cd515346acb":{
      "scriptId":"u2"},
    "cf30adbc171d441cae89c0661dad8a5a":{
      "scriptId":"u3"},
    "bb16b35161f7420f92010ff4e1553f7e":{
      "scriptId":"u4"},
    "4a7af5f3525f4111905c97c8001768c9":{
      "scriptId":"u5"},
    "2e45973772f847f499f633c7fec724e1":{
      "scriptId":"u6"},
    "08e8d355f6eb42b894151a5337d38e6b":{
      "scriptId":"u7"},
    "01d36ba232944639bbfcfe7f5477fc37":{
      "scriptId":"u8"},
    "48564f3e77d742a6b313d2af0c8f363a":{
      "scriptId":"u9"},
    "209828756b0b4ba89cbf250a8aa20d9a":{
      "scriptId":"u10"},
    "4c8aecfd6e53438a926140b9cece2a72":{
      "scriptId":"u11"},
    "87f58821050c4306af0254ad370f0b6d":{
      "scriptId":"u12"},
    "4e31d766e44449c195ba737bd32a7733":{
      "scriptId":"u13"},
    "72e797f8d88d43a792482838045e9f8e":{
      "scriptId":"u14"},
    "85f59670d4da40f8889a07d5593610dd":{
      "scriptId":"u15"},
    "087c8df117934be9bb6140a0b33d474a":{
      "scriptId":"u16"},
    "c6fd0dfd5978473aa8880986c08457a7":{
      "scriptId":"u17"},
    "0dc626ea9b884b4ea97e8f823c3c7c40":{
      "scriptId":"u18"},
    "50eb5e3fa6aa450b8309b9b09b566fe4":{
      "scriptId":"u19"},
    "d7b84ae4235147c38d7c081c92895d19":{
      "scriptId":"u20"},
    "45e02fcaa47041af832bc93888646dcb":{
      "scriptId":"u21"},
    "6872b6f6f10c4091804055becd585af0":{
      "scriptId":"u22"},
    "d42ae0700d624c329045debec4be43a0":{
      "scriptId":"u23"},
    "b776439a0791428ea7edb76e22efcc40":{
      "scriptId":"u24"},
    "f512f45c6ca54de19a3af14d104b85c1":{
      "scriptId":"u25"},
    "e970f08ebc3a42898deb63d88aab7bb3":{
      "scriptId":"u26"},
    "ee283efef5e14ab69e55400965912f84":{
      "scriptId":"u27"},
    "e67eef48c413440794ca9f58f36dc837":{
      "scriptId":"u28"},
    "06118e19356c492188bbe237a251e34f":{
      "scriptId":"u29"},
    "19f2303d00a1450fa8ca2fa6ab9994c5":{
      "scriptId":"u30"},
    "2d99beb6f53b4245957fab5f61b3a266":{
      "scriptId":"u31"},
    "85f9cff2a0104967960fab1b782e0c9f":{
      "scriptId":"u32"},
    "3c5f747de6aa4008b92c58f51ab5af6d":{
      "scriptId":"u33"},
    "8ad2f0e5d4d244019f90c482bfc17b64":{
      "scriptId":"u34"},
    "b4dde7eb968646ef900c4d283dcb1a18":{
      "scriptId":"u35"}}});