$axure.loadCurrentPage({
  "url":"客户订单流程.html",
  "generationDate":new Date(1428320973815.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab179eca43e2494b9607841f77177450",
    "type":"Axure:Page",
    "name":"客户订单流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0821d9c1cb6943d5aed607a61a610e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066CC},
            "location":{
              "x":120,
              "y":110},
            "size":{
              "width":120,
              "height":60},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7f6b851a8346689ca6fc4aea79ab3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066CC},
                "location":{
                  "x":120,
                  "y":110},
                "size":{
                  "width":120,
                  "height":60},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u0.png"}},
{
          "id":"45923d44368f42fa83baf1c455a51b2c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605f2ab809b043a58926cb584d20d11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"b796ca9151e14752a04833497f8ac674",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0005920879cd4108bc8b4937b9a0ef92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"c4590c293d98470f99b45f986db08831",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":124},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135e5edbbe4247e7ba6c5990fbd88d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":124},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"169433baecda4d30afeaf087e5539356",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":310,
              "y":111},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e1e07fbba34b24883e89f4099489e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":310,
                  "y":111},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"71080bc5b4ae408a89a3d94cc1597d1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":310,
              "y":210},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa61f146a45458baeb5e195b1525619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":310,
                  "y":210},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"1e2b767f846545a29fb9499a73408f56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":210},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b46dd505caf4ead8fd1bbfd8089a876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":210},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3635a568e5954aa5bf850d632ceed659",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"895a8d37e84d4b6b91bb9eda6c84366a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":140},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"c6c070cebd074274bf84389fe0d5a4e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":124},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f5a9d23d77c41a7968c0c5c441a9d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":124},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f109f4b24074868825361a43119bd4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":580,
              "y":111},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e32f2c01720449b196ea1b2e7c9667e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":580,
                  "y":111},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}},
{
          "id":"3bb14434987047fa8b44dee7b5f78e8f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":139},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF333333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00a277fd91fe48c19be65084d058e6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":139},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
}}]},
{
          "id":"2cc302730e844134bdbdf49c589c259e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":120},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b9643c8140b4ea2af78f5140f698b9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":120},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98c01a5aba3046a7a821f7d64b5042ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":810,
              "y":111},
            "size":{
              "width":120,
              "height":60},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f3e39449804203b600b969a578ba0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":810,
                  "y":111},
                "size":{
                  "width":120,
                  "height":60},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/物流商订单流程/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0821d9c1cb6943d5aed607a61a610e30":{
      "scriptId":"u0"},
    "af7f6b851a8346689ca6fc4aea79ab3c":{
      "scriptId":"u1"},
    "45923d44368f42fa83baf1c455a51b2c":{
      "scriptId":"u2"},
    "605f2ab809b043a58926cb584d20d11d":{
      "scriptId":"u3"},
    "b796ca9151e14752a04833497f8ac674":{
      "scriptId":"u4"},
    "0005920879cd4108bc8b4937b9a0ef92":{
      "scriptId":"u5"},
    "c4590c293d98470f99b45f986db08831":{
      "scriptId":"u6"},
    "135e5edbbe4247e7ba6c5990fbd88d3b":{
      "scriptId":"u7"},
    "169433baecda4d30afeaf087e5539356":{
      "scriptId":"u8"},
    "b2e1e07fbba34b24883e89f4099489e7":{
      "scriptId":"u9"},
    "71080bc5b4ae408a89a3d94cc1597d1e":{
      "scriptId":"u10"},
    "bfa61f146a45458baeb5e195b1525619":{
      "scriptId":"u11"},
    "1e2b767f846545a29fb9499a73408f56":{
      "scriptId":"u12"},
    "6b46dd505caf4ead8fd1bbfd8089a876":{
      "scriptId":"u13"},
    "3635a568e5954aa5bf850d632ceed659":{
      "scriptId":"u14"},
    "895a8d37e84d4b6b91bb9eda6c84366a":{
      "scriptId":"u15"},
    "c6c070cebd074274bf84389fe0d5a4e4":{
      "scriptId":"u16"},
    "8f5a9d23d77c41a7968c0c5c441a9d55":{
      "scriptId":"u17"},
    "7f109f4b24074868825361a43119bd4e":{
      "scriptId":"u18"},
    "e32f2c01720449b196ea1b2e7c9667e5":{
      "scriptId":"u19"},
    "3bb14434987047fa8b44dee7b5f78e8f":{
      "scriptId":"u20"},
    "00a277fd91fe48c19be65084d058e6f2":{
      "scriptId":"u21"},
    "2cc302730e844134bdbdf49c589c259e":{
      "scriptId":"u22"},
    "1b9643c8140b4ea2af78f5140f698b9a":{
      "scriptId":"u23"},
    "98c01a5aba3046a7a821f7d64b5042ad":{
      "scriptId":"u24"},
    "79f3e39449804203b600b969a578ba0b":{
      "scriptId":"u25"}}});