$axure.loadCurrentPage({
  "url":"下单.html",
  "generationDate":new Date(1428320974535.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"296173e454cb4035954cc00fc3ca4951",
    "type":"Axure:Page",
    "name":"下单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"df06e77634564aef925f87e52f011bdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":103},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed37dec1b5d42eea314759f420c3f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":103},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef3cf362c7db4ca8bba9a0a4bbd989ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"18px",
            "location":{
              "x":280,
              "y":150},
            "size":{
              "width":254,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b68e067e1694f739c7b60e86dca7a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"18px",
                "location":{
                  "x":280,
                  "y":150},
                "size":{
                  "width":254,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aa6cd1537244d8383c789894ddff21c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":210},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"2f319dcbd4c944f78cc6d7852807e9dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":720,
              "y":103},
            "size":{
              "width":50,
              "height":24},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f37dce38634d11bf0f39e94d0aac4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":720,
                  "y":103},
                "size":{
                  "width":50,
                  "height":24},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u5.png"}},
{
          "id":"1b77de0639ef4d15900b21a436ea6f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":253},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebfafccd5999416cbb8722c886ea49a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":253},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e1a0ffd0eb04a3884900451a40b486f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":280,
              "y":300},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d62a51468ddd4ae1a504316b8496d142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":280,
                  "y":300},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f14bd11ee784266b2b3aff4974c11d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":720,
              "y":253},
            "size":{
              "width":50,
              "height":24},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"342528798b704efaa8224b878682854b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":720,
                  "y":253},
                "size":{
                  "width":50,
                  "height":24},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u5.png"}},
{
          "id":"18dc1841660f445798f1148243a4857a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":310},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e655c848589e458594cfda8dbb5eef43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":310},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u13.png"}},
{
          "id":"4d39171c21d2406e86e7916c6a96a292",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":341},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfae759c7740452587f2da21c974cc72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":341},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u13.png"}},
{
          "id":"f99c6fd1f7284dd0b699c25b9757f0a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":410},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d1ee23c7c8b45d8a0f38db68eb8269a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":410},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u13.png"}},
{
          "id":"4be2e285d25d463baa7414c040a0092f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":450},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc630d22ce434972b2b14785ab6d8f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":450},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u13.png"}},
{
          "id":"b08b793ecb854d5888c12f9fae8b6885",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":484},
            "size":{
              "width":48,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2de64d33d8fd4618921b2348b8178606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":484},
                "size":{
                  "width":48,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u21.png"}},
{
          "id":"567dd4cc7bdb47eeab8505bba47885dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":484},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b8069444cc84edfba3bda22f2e52d05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":484},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u23.png"}},
{
          "id":"b501f273046c4aebb93d34e1b4747640",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":484},
            "size":{
              "width":48,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91737e07f7754cb9be75dfea47e34b82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":484},
                "size":{
                  "width":48,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u21.png"}},
{
          "id":"8011cc5cc643462aa0a5b509bb1b9842",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":587,
              "y":448},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c59277db343248399650fc3bb8b9d974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":587,
                  "y":448},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f09bd1a0933f42d686f178f47297a874",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":587,
              "y":410},
            "size":{
              "width":139,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"076659ddc5914e0baf318126131c1105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":587,
                  "y":410},
                "size":{
                  "width":139,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a518c8e526147189183ac89fea1f373",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":361,
              "y":378},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b04c55757004a0fa322ccc3147e6807",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":361,
                  "y":378},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb27d66546354ca898922bdb75a7faeb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":441,
              "y":376},
            "size":{
              "width":98,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"19e855aed0ec4098be2b4463140c8e76",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":550},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"d06eab66366b491faff92af3e6c7014c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":574},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3bc73f0969941ceb00a011459e0bcb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":574},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e5d882feaca4e59b7dad60652822001",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"36px",
            "location":{
              "x":280,
              "y":618},
            "size":{
              "width":84,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79a45a5c9a544f8da26539263d897152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"36px",
                "location":{
                  "x":280,
                  "y":618},
                "size":{
                  "width":84,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a21300e7ec4bcbb0f7209b1134f056",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":846},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"bfcce24f7c5441c0b8a0bd98676cc9a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":618},
            "size":{
              "width":200,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be825bf0ff234decbc3b8a8b06cfa30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":618},
                "size":{
                  "width":200,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u13.png"}},
{
          "id":"264ab983109c4c3cb31a7d13d5b739e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":698},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02bc7970668f41cdb09b31fbedc86633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":698},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u42.png"}},
{
          "id":"e005514463734b03b05866b6815f8e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":738},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49e27e8e259e4b56a61f18e974b63b19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":738},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u42.png"}},
{
          "id":"2f2732fcdf4d4266896fc1d384b8f4e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":699},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9994fe2b1c7449eab29a95e234f6db0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":699},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3905b417997146bc862cce59c586061c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":442,
              "y":740},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"057def1b16c843358d6a49b587dbac71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":442,
                  "y":740},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a09b612b87f4d33ba834b30c08e3b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":523,
              "y":740},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"199fbaed2ab745ea9662dbb9ff061d81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":523,
                  "y":740},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bb66a896a984ef59e98942655c7e1d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":738},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bac0d0b26d84580b69b7484a8304a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573,
                  "y":738},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u42.png"}},
{
          "id":"942fd996c49e40b3a8505f5689fc0a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":653,
              "y":740},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff38221af9da4270824677f8f63d4279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":653,
                  "y":740},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"038c8363482d4cc78240ce6beb5ee928",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"18px",
            "location":{
              "x":490,
              "y":739},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a196391075df448e9e60f7c0c3040ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"18px",
                "location":{
                  "x":490,
                  "y":739},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd9d9bd0c8c34f72b78740809174a29c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":580,
              "y":620},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7d3f0fb4b842f39c18b755155baa28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":620},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cf653db8b164b86b9ce0fc2247bbc03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":703,
              "y":738},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e47eedd64814908a3dbb4e3bf8b491c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":703,
                  "y":738},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2fed5a0eb5f4f2eb6640c11c2a59cbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":778},
            "size":{
              "width":332,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c566df4383ea4d40a6b81bfa46141465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":778},
                "size":{
                  "width":332,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u62.png"}},
{
          "id":"b0290c5c24e94525ad644468217b3017",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":268,
              "y":1160},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2446fd4c3acc480e839732050cb9643a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":268,
                  "y":1160},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d7060dc751e4220b6bff250f50f3826",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1230},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"0620b10bda2b4ab1a4d3a328892d452f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":1285},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9027394ecf4c4093b15dde2483480897",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":268,
              "y":866},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79986c2a5dac4b1795e2a85dba15e651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":268,
                  "y":866},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3966954c46914252a847b994ecf394f5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":934},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a04e03fe830e45d9b94c6d19ab42aad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":934},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c587a0ce0e8c4b9cac5bef42a47a743c",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1033},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a72e8c72af54d01ba63c2a39225639f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1033},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4f481c58aef24d1a99b53477536370c3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":934},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033ee52e279f4433b980673199dba758",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":934},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"57454ded87ce4c1e8e3c98dd98aeb324",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":929},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ce04cf15e94323800bb6779d9c5f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":701,
                  "y":929},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"d590cf31d33a4b1883888f994c5271ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":771,
              "y":934},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09018bce8ec845268ecde635bb093354",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":771,
                  "y":934},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b6eb94136bb49c9b51c3232ae9c56ef",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":1033},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f76e53017b6344858871a9da11c52fab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":1033},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0ff36b2f15084e30aa0ebd40665c39c9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":1032},
            "size":{
              "width":135,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"091c87a9c54c4e1a8556ca580cb9104e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1095},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f19e2f3c7b6b47b580e813d3c3581ef4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1095},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bb66b95b0bfb47f989995b30c16087ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":416,
              "y":1090},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"006cc1173e694eed88670d8950eaba77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":1090},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"84c641f8fc6349b88877dc01d8745ac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":1095},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1419e0d86efa41ebbf07611d3da49d34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":1095},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cfcaadada224b28a439f880f9187cbb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":1092},
            "size":{
              "width":63,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a2beee8f97b34435ba6eae663d1a4c89",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1064},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6853eda3a6434794960a214cfee63be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":1064},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6b6065cb29ee4f81afc48aea54c6b43d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":1064},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f02bd1a7754f76a0e7c0105ec1d750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":1064},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2f042fc872ee4c92b1c14ae77d4dfb38",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":1095},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172ef0d178894da68bd5098b2c0ac5cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":1095},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0c81bd6424924ccc9fcd679a50d2e382",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":1130},
            "size":{
              "width":490,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u4_line.png"}},
{
          "id":"15e92d86be9a45b983ac3807a66390d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":280,
              "y":54},
            "size":{
              "width":490,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e307e259a9a4d8eba5bb79cf6b9efd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":280,
                  "y":54},
                "size":{
                  "width":490,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u97.png"}},
{
          "id":"b322d34ce52d40159c2c7e87286a815a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":64},
            "size":{
              "width":301,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30db46e975bf4678be0709abade67d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":299,
                  "y":64},
                "size":{
                  "width":301,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a45ee575c1a459fb5094fdbfe6e3438",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":54},
            "size":{
              "width":210,
              "height":526},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6d9ea0247fe45b89392ed6115a3ed09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":54},
                "size":{
                  "width":210,
                  "height":526},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/下单/u101.png"}},
{
          "id":"16a65e401bf44d9b9c33e7303c3fd3c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":99},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"536fe55ef60b4262a2f78077bea742b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":99},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd31de59f6014c9aa8b51dae33d2c637",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":74,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15c8af1d80284eb0adf527261f50e1f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":74,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查找列表/u75.png"}},
{
          "id":"851c1db07e654ebdbcd0b139d2993c15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":134},
            "size":{
              "width":164,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f42620a2c24afb83c202add883d951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":134},
                "size":{
                  "width":164,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8782aa27752444f68d990135e719b3fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":310},
            "size":{
              "width":210,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/下单/u109_line.png"}},
{
          "id":"715bca126c7f4f798a83f772e3c9bcf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":330},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfeb2af382f84a86ab7371f2af326973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":330},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c023b75ba21d4fef9528cf9d082dcc33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"22px",
            "location":{
              "x":55,
              "y":378},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb774f387154daebd462a619e9c3f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"22px",
                "location":{
                  "x":55,
                  "y":378},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63e0fe2a0cdc4d00abe89413a8340274",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":1033},
            "size":{
              "width":107,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"069f6f34045041bb8498219a94237096",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1354,
              "y":702},
            "size":{
              "width":236,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f6b9a51e704b47b1892c5c0c5f2a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1354,
                  "y":702},
                "size":{
                  "width":236,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05b92d8c855d4c69ad056ecc8bcc7e05",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":960},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37a9eed504124a4cb37371ded77c660f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":960},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"91a775110cf5468c88e68eaf552f8191",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":986},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff0d72d0cab948fab79a21bd018caa85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":986},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"745a3989062f40a6a51e2033d84c486f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":658},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e1582fba6cfe4d0f867bf13dc6ab1b56",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":268,
              "y":1204},
            "size":{
              "width":143,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"989e25cfa8cf41789c0e4da145ee4835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":268,
                  "y":1204},
                "size":{
                  "width":143,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ffa280c8a46d447fb9df3dde706c35e7",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":444,
              "y":1204},
            "size":{
              "width":143,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8350c80462aa451b888d5c4b1e51a579",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":444,
                  "y":1204},
                "size":{
                  "width":143,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9198145fdbef4a9d9bc34ee1f1143871",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":369,
              "y":960},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6609289f584e460481fa10547d2bac2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":960},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74be57add10f4b9fa45cfd6d15d5df2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":369,
              "y":986},
            "size":{
              "width":194,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a4db0dabd4405a862c40e9c3744982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":369,
                  "y":986},
                "size":{
                  "width":194,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"767508ecc72e44e9a34c6888c4a72620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":846,
              "y":1032},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d18116da69984ab197af20fb05fbbcf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":846,
                  "y":1032},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "df06e77634564aef925f87e52f011bdc":{
      "scriptId":"u0"},
    "7ed37dec1b5d42eea314759f420c3f2f":{
      "scriptId":"u1"},
    "ef3cf362c7db4ca8bba9a0a4bbd989ea":{
      "scriptId":"u2"},
    "5b68e067e1694f739c7b60e86dca7a10":{
      "scriptId":"u3"},
    "8aa6cd1537244d8383c789894ddff21c":{
      "scriptId":"u4"},
    "2f319dcbd4c944f78cc6d7852807e9dd":{
      "scriptId":"u5"},
    "d7f37dce38634d11bf0f39e94d0aac4d":{
      "scriptId":"u6"},
    "1b77de0639ef4d15900b21a436ea6f30":{
      "scriptId":"u7"},
    "ebfafccd5999416cbb8722c886ea49a6":{
      "scriptId":"u8"},
    "2e1a0ffd0eb04a3884900451a40b486f":{
      "scriptId":"u9"},
    "d62a51468ddd4ae1a504316b8496d142":{
      "scriptId":"u10"},
    "5f14bd11ee784266b2b3aff4974c11d0":{
      "scriptId":"u11"},
    "342528798b704efaa8224b878682854b":{
      "scriptId":"u12"},
    "18dc1841660f445798f1148243a4857a":{
      "scriptId":"u13"},
    "e655c848589e458594cfda8dbb5eef43":{
      "scriptId":"u14"},
    "4d39171c21d2406e86e7916c6a96a292":{
      "scriptId":"u15"},
    "dfae759c7740452587f2da21c974cc72":{
      "scriptId":"u16"},
    "f99c6fd1f7284dd0b699c25b9757f0a7":{
      "scriptId":"u17"},
    "9d1ee23c7c8b45d8a0f38db68eb8269a":{
      "scriptId":"u18"},
    "4be2e285d25d463baa7414c040a0092f":{
      "scriptId":"u19"},
    "bc630d22ce434972b2b14785ab6d8f11":{
      "scriptId":"u20"},
    "b08b793ecb854d5888c12f9fae8b6885":{
      "scriptId":"u21"},
    "2de64d33d8fd4618921b2348b8178606":{
      "scriptId":"u22"},
    "567dd4cc7bdb47eeab8505bba47885dd":{
      "scriptId":"u23"},
    "1b8069444cc84edfba3bda22f2e52d05":{
      "scriptId":"u24"},
    "b501f273046c4aebb93d34e1b4747640":{
      "scriptId":"u25"},
    "91737e07f7754cb9be75dfea47e34b82":{
      "scriptId":"u26"},
    "8011cc5cc643462aa0a5b509bb1b9842":{
      "scriptId":"u27"},
    "c59277db343248399650fc3bb8b9d974":{
      "scriptId":"u28"},
    "f09bd1a0933f42d686f178f47297a874":{
      "scriptId":"u29"},
    "076659ddc5914e0baf318126131c1105":{
      "scriptId":"u30"},
    "3a518c8e526147189183ac89fea1f373":{
      "scriptId":"u31"},
    "6b04c55757004a0fa322ccc3147e6807":{
      "scriptId":"u32"},
    "eb27d66546354ca898922bdb75a7faeb":{
      "scriptId":"u33"},
    "19e855aed0ec4098be2b4463140c8e76":{
      "scriptId":"u34"},
    "d06eab66366b491faff92af3e6c7014c":{
      "scriptId":"u35"},
    "e3bc73f0969941ceb00a011459e0bcb3":{
      "scriptId":"u36"},
    "5e5d882feaca4e59b7dad60652822001":{
      "scriptId":"u37"},
    "79a45a5c9a544f8da26539263d897152":{
      "scriptId":"u38"},
    "01a21300e7ec4bcbb0f7209b1134f056":{
      "scriptId":"u39"},
    "bfcce24f7c5441c0b8a0bd98676cc9a1":{
      "scriptId":"u40"},
    "be825bf0ff234decbc3b8a8b06cfa30c":{
      "scriptId":"u41"},
    "264ab983109c4c3cb31a7d13d5b739e4":{
      "scriptId":"u42"},
    "02bc7970668f41cdb09b31fbedc86633":{
      "scriptId":"u43"},
    "e005514463734b03b05866b6815f8e13":{
      "scriptId":"u44"},
    "49e27e8e259e4b56a61f18e974b63b19":{
      "scriptId":"u45"},
    "2f2732fcdf4d4266896fc1d384b8f4e9":{
      "scriptId":"u46"},
    "e9994fe2b1c7449eab29a95e234f6db0":{
      "scriptId":"u47"},
    "3905b417997146bc862cce59c586061c":{
      "scriptId":"u48"},
    "057def1b16c843358d6a49b587dbac71":{
      "scriptId":"u49"},
    "9a09b612b87f4d33ba834b30c08e3b55":{
      "scriptId":"u50"},
    "199fbaed2ab745ea9662dbb9ff061d81":{
      "scriptId":"u51"},
    "8bb66a896a984ef59e98942655c7e1d1":{
      "scriptId":"u52"},
    "0bac0d0b26d84580b69b7484a8304a45":{
      "scriptId":"u53"},
    "942fd996c49e40b3a8505f5689fc0a39":{
      "scriptId":"u54"},
    "ff38221af9da4270824677f8f63d4279":{
      "scriptId":"u55"},
    "038c8363482d4cc78240ce6beb5ee928":{
      "scriptId":"u56"},
    "a196391075df448e9e60f7c0c3040ccb":{
      "scriptId":"u57"},
    "fd9d9bd0c8c34f72b78740809174a29c":{
      "scriptId":"u58"},
    "de7d3f0fb4b842f39c18b755155baa28":{
      "scriptId":"u59"},
    "6cf653db8b164b86b9ce0fc2247bbc03":{
      "scriptId":"u60"},
    "8e47eedd64814908a3dbb4e3bf8b491c":{
      "scriptId":"u61"},
    "e2fed5a0eb5f4f2eb6640c11c2a59cbd":{
      "scriptId":"u62"},
    "c566df4383ea4d40a6b81bfa46141465":{
      "scriptId":"u63"},
    "b0290c5c24e94525ad644468217b3017":{
      "scriptId":"u64"},
    "2446fd4c3acc480e839732050cb9643a":{
      "scriptId":"u65"},
    "2d7060dc751e4220b6bff250f50f3826":{
      "scriptId":"u66"},
    "0620b10bda2b4ab1a4d3a328892d452f":{
      "scriptId":"u67"},
    "9027394ecf4c4093b15dde2483480897":{
      "scriptId":"u68"},
    "79986c2a5dac4b1795e2a85dba15e651":{
      "scriptId":"u69"},
    "3966954c46914252a847b994ecf394f5":{
      "scriptId":"u70"},
    "a04e03fe830e45d9b94c6d19ab42aad0":{
      "scriptId":"u71"},
    "c587a0ce0e8c4b9cac5bef42a47a743c":{
      "scriptId":"u72"},
    "6a72e8c72af54d01ba63c2a39225639f":{
      "scriptId":"u73"},
    "4f481c58aef24d1a99b53477536370c3":{
      "scriptId":"u74"},
    "033ee52e279f4433b980673199dba758":{
      "scriptId":"u75"},
    "57454ded87ce4c1e8e3c98dd98aeb324":{
      "scriptId":"u76"},
    "44ce04cf15e94323800bb6779d9c5f0c":{
      "scriptId":"u77"},
    "d590cf31d33a4b1883888f994c5271ac":{
      "scriptId":"u78"},
    "09018bce8ec845268ecde635bb093354":{
      "scriptId":"u79"},
    "6b6eb94136bb49c9b51c3232ae9c56ef":{
      "scriptId":"u80"},
    "f76e53017b6344858871a9da11c52fab":{
      "scriptId":"u81"},
    "0ff36b2f15084e30aa0ebd40665c39c9":{
      "scriptId":"u82"},
    "091c87a9c54c4e1a8556ca580cb9104e":{
      "scriptId":"u83"},
    "f19e2f3c7b6b47b580e813d3c3581ef4":{
      "scriptId":"u84"},
    "bb66b95b0bfb47f989995b30c16087ac":{
      "scriptId":"u85"},
    "006cc1173e694eed88670d8950eaba77":{
      "scriptId":"u86"},
    "84c641f8fc6349b88877dc01d8745ac0":{
      "scriptId":"u87"},
    "1419e0d86efa41ebbf07611d3da49d34":{
      "scriptId":"u88"},
    "3cfcaadada224b28a439f880f9187cbb":{
      "scriptId":"u89"},
    "a2beee8f97b34435ba6eae663d1a4c89":{
      "scriptId":"u90"},
    "6853eda3a6434794960a214cfee63be9":{
      "scriptId":"u91"},
    "6b6065cb29ee4f81afc48aea54c6b43d":{
      "scriptId":"u92"},
    "82f02bd1a7754f76a0e7c0105ec1d750":{
      "scriptId":"u93"},
    "2f042fc872ee4c92b1c14ae77d4dfb38":{
      "scriptId":"u94"},
    "172ef0d178894da68bd5098b2c0ac5cb":{
      "scriptId":"u95"},
    "0c81bd6424924ccc9fcd679a50d2e382":{
      "scriptId":"u96"},
    "15e92d86be9a45b983ac3807a66390d2":{
      "scriptId":"u97"},
    "0e307e259a9a4d8eba5bb79cf6b9efd4":{
      "scriptId":"u98"},
    "b322d34ce52d40159c2c7e87286a815a":{
      "scriptId":"u99"},
    "30db46e975bf4678be0709abade67d19":{
      "scriptId":"u100"},
    "4a45ee575c1a459fb5094fdbfe6e3438":{
      "scriptId":"u101"},
    "b6d9ea0247fe45b89392ed6115a3ed09":{
      "scriptId":"u102"},
    "16a65e401bf44d9b9c33e7303c3fd3c1":{
      "scriptId":"u103"},
    "536fe55ef60b4262a2f78077bea742b9":{
      "scriptId":"u104"},
    "cd31de59f6014c9aa8b51dae33d2c637":{
      "scriptId":"u105"},
    "15c8af1d80284eb0adf527261f50e1f0":{
      "scriptId":"u106"},
    "851c1db07e654ebdbcd0b139d2993c15":{
      "scriptId":"u107"},
    "94f42620a2c24afb83c202add883d951":{
      "scriptId":"u108"},
    "8782aa27752444f68d990135e719b3fb":{
      "scriptId":"u109"},
    "715bca126c7f4f798a83f772e3c9bcf4":{
      "scriptId":"u110"},
    "dfeb2af382f84a86ab7371f2af326973":{
      "scriptId":"u111"},
    "c023b75ba21d4fef9528cf9d082dcc33":{
      "scriptId":"u112"},
    "9eb774f387154daebd462a619e9c3f18":{
      "scriptId":"u113"},
    "63e0fe2a0cdc4d00abe89413a8340274":{
      "scriptId":"u114"},
    "069f6f34045041bb8498219a94237096":{
      "scriptId":"u115"},
    "96f6b9a51e704b47b1892c5c0c5f2a41":{
      "scriptId":"u116"},
    "05b92d8c855d4c69ad056ecc8bcc7e05":{
      "scriptId":"u117"},
    "37a9eed504124a4cb37371ded77c660f":{
      "scriptId":"u118"},
    "91a775110cf5468c88e68eaf552f8191":{
      "scriptId":"u119"},
    "ff0d72d0cab948fab79a21bd018caa85":{
      "scriptId":"u120"},
    "745a3989062f40a6a51e2033d84c486f":{
      "scriptId":"u121"},
    "e1582fba6cfe4d0f867bf13dc6ab1b56":{
      "scriptId":"u122"},
    "989e25cfa8cf41789c0e4da145ee4835":{
      "scriptId":"u123"},
    "ffa280c8a46d447fb9df3dde706c35e7":{
      "scriptId":"u124"},
    "8350c80462aa451b888d5c4b1e51a579":{
      "scriptId":"u125"},
    "9198145fdbef4a9d9bc34ee1f1143871":{
      "scriptId":"u126"},
    "6609289f584e460481fa10547d2bac2d":{
      "scriptId":"u127"},
    "74be57add10f4b9fa45cfd6d15d5df2e":{
      "scriptId":"u128"},
    "54a4db0dabd4405a862c40e9c3744982":{
      "scriptId":"u129"},
    "767508ecc72e44e9a34c6888c4a72620":{
      "scriptId":"u130"},
    "d18116da69984ab197af20fb05fbbcf6":{
      "scriptId":"u131"}}});