$axure.loadCurrentPage({
  "url":"线路.html",
  "generationDate":new Date(1428320974947.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1d342243dbe0408facc0fd78860defec",
    "type":"Axure:Page",
    "name":"线路",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c206cdbf8db34cf2b7c70d818298a0ae",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":57,
              "y":272},
            "size":{
              "width":859,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0890fb7075934035b074d8f5d4df8f38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":169,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5509ab737ce4227b77445c3065e59ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":169,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u1.png"}},
{
              "id":"5d31a20afede45c2ab18678a2b899f5c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":169,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16ee2f3d432d4271a8f1f90e12ee96bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":169,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u9.png"}},
{
              "id":"f48ca93df61c4c379028a7787a23e47f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":169,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ffc372f0702409dab47a79439968b37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":108},
                    "size":{
                      "width":169,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u17.png"}},
{
              "id":"d3a4dc16de144fdbb80c2a4778034c86",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":169,
                  "y":0},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b1827ca40a24a6ba5de7efb32fc0368",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":169,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u3.png"}},
{
              "id":"a5e9cbf1080148aeae66fdf4a13acf4c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":40},
                "size":{
                  "width":150,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d1953aec8bf94751b94a9adeb3d46a64",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u11.png"}},
{
              "id":"0f51894d059e49cc9870810777efb67d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":169,
                  "y":108},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c32c9c2ea554cc9ad3d4be718577bb2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":169,
                      "y":108},
                    "size":{
                      "width":150,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u19.png"}},
{
              "id":"f21d8de0e0f849b5a0a93c860c96c455",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":453,
                  "y":0},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48025e3a9ad94fc5985b425d5971ac75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":453,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u7.png"}},
{
              "id":"8cc86a6975d140e487302a80a03465db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":40},
                "size":{
                  "width":100,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c5656c0295df40ecb4bf0143deaeb55e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":453,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u19.png"}},
{
              "id":"8e71bc13d72e48229fce0af1c8634e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":108},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2290643273d84595beb1f508e618cf88",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":453,
                      "y":108},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u31.png"}},
{
              "id":"5a7197b85e7e43f8ba17d971e88b6141",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":319,
                  "y":0},
                "size":{
                  "width":134,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f5e9816397ea45adbfee82c72a4eb071",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":319,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u5.png"}},
{
              "id":"e3557fa0242c42598d3485fcb28783f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":40},
                "size":{
                  "width":134,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"989a674fc8c14cdd9a93a4590ff52f9f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":40},
                    "size":{
                      "width":134,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u13.png"}},
{
              "id":"6c113c94437e406ebb984cbf65566a2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":319,
                  "y":108},
                "size":{
                  "width":134,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da55263d8aff42b0aed1c08ef7b55d14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":319,
                      "y":108},
                    "size":{
                      "width":134,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u21.png"}},
{
              "id":"8401774af3834116a99ce2a12115cd99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":553,
                  "y":0},
                "size":{
                  "width":163,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4256de55c7814aa48395c7c7e6fb9bce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":553,
                      "y":0},
                    "size":{
                      "width":163,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u9.png"}},
{
              "id":"c64dd8bdc91243b5bbc0d4ec32e91794",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":553,
                  "y":40},
                "size":{
                  "width":163,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f107aec72de4b94976006f39566e6fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":553,
                      "y":40},
                    "size":{
                      "width":163,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u21.png"}},
{
              "id":"627b3ba2e9374473a8f3d034a0b0fa0d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":553,
                  "y":108},
                "size":{
                  "width":163,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4576dbcd5bf747d8b3e119f989f2d2f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":553,
                      "y":108},
                    "size":{
                      "width":163,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u33.png"}},
{
              "id":"559c43cc42d14c0fad7605b6fe65b4db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":716,
                  "y":0},
                "size":{
                  "width":143,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c226e19395a439d8b31aff9d832994c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":716,
                      "y":0},
                    "size":{
                      "width":143,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u11.png"}},
{
              "id":"54031d33549a4278afbc604a30b5683f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":716,
                  "y":40},
                "size":{
                  "width":143,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac1c10af83374eddbcef77ee623c4485",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":716,
                      "y":40},
                    "size":{
                      "width":143,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u23.png"}},
{
              "id":"4935c68563d048ca832b36879ab18b1f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":716,
                  "y":108},
                "size":{
                  "width":143,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e0bbcf7a5a24847b4898ef3917f95c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":716,
                      "y":108},
                    "size":{
                      "width":143,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u35.png"}}]},
{
          "id":"6cc6f4b594684d8f97274016168b9701",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":60},
            "size":{
              "width":870,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af3db08fc98845c28022277a7016a4da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":60},
                "size":{
                  "width":870,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路/u37.png"}},
{
          "id":"6c761f9efe294cf3808173a46bed5f9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":78,
              "y":72},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62af8f2596124064b3177804b5ae3d51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":72},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5577c4a7e3fa481cb8c51fd87563030a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":203,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d72392aa5ade4ff39547a7476115a2ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":203,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3333c48a4ed047dab9fd12cc3ecc3fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":293,
              "y":72},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36ad8c2ec7de418dad53b3ec469fb47d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":72},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c75be76b7c78429ca17b3888bffb78bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":110},
            "size":{
              "width":870,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db5eb7e8731b4b52b9b37126fb93e997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":110},
                "size":{
                  "width":870,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路/u45.png"}},
{
          "id":"c2351596742e4fe38a3267e2f6598ca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":70,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2da366ad51104e8d8c68f175134a5ef7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":430,
                  "y":190},
                "size":{
                  "width":70,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/网点介绍/u37.png"}},
{
          "id":"bef49d07cf0f4f479f6a214eccf2d4f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":142},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a7b04b6b8d46ebad0db0c53e4f0307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":142},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3289d79648cb43f8ae29d34b023e786a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":141},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccfd780fbf224d2083a61e419f7cdcec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":141},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd72ceb3efbe47bf8a7f51781e46a01b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":138},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"395ee92ea2fb439b9245f45d46b2b5ca",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":138},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"df22e410b72d472a9b1e131e47a6dfc2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":138},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"13cd766638cc409a93a466367964cd5d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":683,
              "y":138},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c206cdbf8db34cf2b7c70d818298a0ae":{
      "scriptId":"u0"},
    "0890fb7075934035b074d8f5d4df8f38":{
      "scriptId":"u1"},
    "d5509ab737ce4227b77445c3065e59ff":{
      "scriptId":"u2"},
    "d3a4dc16de144fdbb80c2a4778034c86":{
      "scriptId":"u3"},
    "7b1827ca40a24a6ba5de7efb32fc0368":{
      "scriptId":"u4"},
    "5a7197b85e7e43f8ba17d971e88b6141":{
      "scriptId":"u5"},
    "f5e9816397ea45adbfee82c72a4eb071":{
      "scriptId":"u6"},
    "f21d8de0e0f849b5a0a93c860c96c455":{
      "scriptId":"u7"},
    "48025e3a9ad94fc5985b425d5971ac75":{
      "scriptId":"u8"},
    "8401774af3834116a99ce2a12115cd99":{
      "scriptId":"u9"},
    "4256de55c7814aa48395c7c7e6fb9bce":{
      "scriptId":"u10"},
    "559c43cc42d14c0fad7605b6fe65b4db":{
      "scriptId":"u11"},
    "0c226e19395a439d8b31aff9d832994c":{
      "scriptId":"u12"},
    "5d31a20afede45c2ab18678a2b899f5c":{
      "scriptId":"u13"},
    "16ee2f3d432d4271a8f1f90e12ee96bd":{
      "scriptId":"u14"},
    "a5e9cbf1080148aeae66fdf4a13acf4c":{
      "scriptId":"u15"},
    "d1953aec8bf94751b94a9adeb3d46a64":{
      "scriptId":"u16"},
    "e3557fa0242c42598d3485fcb28783f5":{
      "scriptId":"u17"},
    "989a674fc8c14cdd9a93a4590ff52f9f":{
      "scriptId":"u18"},
    "8cc86a6975d140e487302a80a03465db":{
      "scriptId":"u19"},
    "c5656c0295df40ecb4bf0143deaeb55e":{
      "scriptId":"u20"},
    "c64dd8bdc91243b5bbc0d4ec32e91794":{
      "scriptId":"u21"},
    "4f107aec72de4b94976006f39566e6fc":{
      "scriptId":"u22"},
    "54031d33549a4278afbc604a30b5683f":{
      "scriptId":"u23"},
    "ac1c10af83374eddbcef77ee623c4485":{
      "scriptId":"u24"},
    "f48ca93df61c4c379028a7787a23e47f":{
      "scriptId":"u25"},
    "3ffc372f0702409dab47a79439968b37":{
      "scriptId":"u26"},
    "0f51894d059e49cc9870810777efb67d":{
      "scriptId":"u27"},
    "9c32c9c2ea554cc9ad3d4be718577bb2":{
      "scriptId":"u28"},
    "6c113c94437e406ebb984cbf65566a2c":{
      "scriptId":"u29"},
    "da55263d8aff42b0aed1c08ef7b55d14":{
      "scriptId":"u30"},
    "8e71bc13d72e48229fce0af1c8634e38":{
      "scriptId":"u31"},
    "2290643273d84595beb1f508e618cf88":{
      "scriptId":"u32"},
    "627b3ba2e9374473a8f3d034a0b0fa0d":{
      "scriptId":"u33"},
    "4576dbcd5bf747d8b3e119f989f2d2f4":{
      "scriptId":"u34"},
    "4935c68563d048ca832b36879ab18b1f":{
      "scriptId":"u35"},
    "0e0bbcf7a5a24847b4898ef3917f95c9":{
      "scriptId":"u36"},
    "6cc6f4b594684d8f97274016168b9701":{
      "scriptId":"u37"},
    "af3db08fc98845c28022277a7016a4da":{
      "scriptId":"u38"},
    "6c761f9efe294cf3808173a46bed5f9f":{
      "scriptId":"u39"},
    "62af8f2596124064b3177804b5ae3d51":{
      "scriptId":"u40"},
    "5577c4a7e3fa481cb8c51fd87563030a":{
      "scriptId":"u41"},
    "d72392aa5ade4ff39547a7476115a2ad":{
      "scriptId":"u42"},
    "3333c48a4ed047dab9fd12cc3ecc3fb5":{
      "scriptId":"u43"},
    "36ad8c2ec7de418dad53b3ec469fb47d":{
      "scriptId":"u44"},
    "c75be76b7c78429ca17b3888bffb78bf":{
      "scriptId":"u45"},
    "db5eb7e8731b4b52b9b37126fb93e997":{
      "scriptId":"u46"},
    "c2351596742e4fe38a3267e2f6598ca0":{
      "scriptId":"u47"},
    "2da366ad51104e8d8c68f175134a5ef7":{
      "scriptId":"u48"},
    "bef49d07cf0f4f479f6a214eccf2d4f5":{
      "scriptId":"u49"},
    "33a7b04b6b8d46ebad0db0c53e4f0307":{
      "scriptId":"u50"},
    "3289d79648cb43f8ae29d34b023e786a":{
      "scriptId":"u51"},
    "ccfd780fbf224d2083a61e419f7cdcec":{
      "scriptId":"u52"},
    "cd72ceb3efbe47bf8a7f51781e46a01b":{
      "scriptId":"u53"},
    "395ee92ea2fb439b9245f45d46b2b5ca":{
      "scriptId":"u54"},
    "df22e410b72d472a9b1e131e47a6dfc2":{
      "scriptId":"u55"},
    "13cd766638cc409a93a466367964cd5d":{
      "scriptId":"u56"}}});