$axure.loadCurrentPage({
  "url":"物流商.html",
  "generationDate":new Date(1427610289182.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e74d65630edb47f8a1c9349245525cb4",
    "type":"Axure:Page",
    "name":"物流商",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f7450695462a481ea1954bf2de2364c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":85,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12bebe2376d149b9b1d99c9c3047285d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":85,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"632c9327e02d425fb155974a5473539a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"8e8eac7621c54c348d5d56115abf4e26",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":725,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9c00710a595442f9cc317385429409c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89d6e3e5c7b7456496a87f4a8265b972",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u4.png"}},
{
              "id":"f0c0e2effdb641409ec77f5de540b371",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da050772d07f4083a400b51612bc2afb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u4.png"}},
{
              "id":"fad9bcde6b8d46d0a49e37daf2928925",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc5f8b9ce2bf4cb1b02025b4ae3cc172",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u4.png"}},
{
              "id":"db4dad545ca54984b66ea0a2ce5b51cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a97ecec5f41432f87bf186f55be9056",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"ff42416ae5d947768153f3d5ee12231d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"197004cca2774d3fba18a71f5620439e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"736e256004a34e939fe4b3d00487f389",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5815019bdcca41d083c18aa4547179c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"d95d2f78d97e43889cfa9d257b9318ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":525,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e77ea752ec6b4cae9e6a4742635d6d79",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":525,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u37.png"}},
{
              "id":"e954bea160fa4e24ac1bfe125ef07e7e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04e18ab11f27423fa8d96198891274c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":525,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u37.png"}},
{
              "id":"d26e0e6c28594fd39f7c7c18b145e32c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"648caa1c0018439b9f7d95ced79cc1c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":525,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u37.png"}},
{
              "id":"f22491ed8b884e6cb376fef5c337a385",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f34597ed49c4b22a31c9bcc7f09fee5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"8b0480d342764c2ebaf53bd1a36ae321",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"090abd31952d4d12aa68f9ebdc7e0150",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"2d01aa23015949dcba0b7a61d3336794",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eda0554efac94f18ba60d48c7a66f862",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"76f2954230cc46c9a47c7242c0e632f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"357f2afcb4fa42cab6c097aa9a7b2563",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u4.png"}},
{
              "id":"b5ba362bee8f4e38828b2f806be950e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41e3f7791a4b4feb8d51893b2325f0c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"e947df06cad045529526b4b2c49ea0e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1112ce3bd3a447b0a014f9ee2ec3995a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u35.png"}},
{
              "id":"2c7583fc840044f3a7d494b409e4b629",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":90},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d84c38542af4b0399f0f8660d027e08",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":525,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u37.png"}},
{
              "id":"24449a24e56742579750531dc4889be2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71526b9f33554bd3850a6eb2d58db773",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/通讯录/u32.png"}},
{
              "id":"b56720dcc96d44239622724e697aa6de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bdc7a05996844623a2c24c99c8183499",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u39.png"}},
{
              "id":"2ccb23f5b59247179e998125844a9a4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a235284aaaa6420497823c32f1d0135a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u39.png"}},
{
              "id":"9ccdfe9fc6964397a826a23828f258ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":525,
                  "y":120},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96f704be54224f49a235491e10245e07",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":525,
                      "y":120},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/注册/u5.png"}},
{
              "id":"3c9fc9ffc5194f4da532ebb0486da21c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a0d10d57eb44006bc48e72f86ce95f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u10.png"}},
{
              "id":"933d1d81e85c4748aa2b63aa6fc6a6d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"272bc7d0c9d04d52bcbccbf83bcf21b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u10.png"}},
{
              "id":"39e4be42b6e04ceabe181bd0001d2efd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"322a584694ea4b7480ec2dd587e20f59",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u10.png"}},
{
              "id":"4a3ea325888f45d990f9077c36c253d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":90},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22e20006784f4662bbb84596da1e32a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":90},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u10.png"}},
{
              "id":"bfd314bbc12e4555ac2a9e443bc1fe80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":120},
                "size":{
                  "width":125,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6c61a44913e44e49cfdbf1eed220b16",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":120},
                    "size":{
                      "width":125,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流商/u50.png"}}]},
{
          "id":"a79eeed0be4c464ca04417e0fbe7fbd3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":195},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7318f0f000814e268ed0b33a1e70a026",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":225},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9daa4ee68d284c6b8190ca00859ce9a1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":254},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b669260d26714a96bc40d2c1cfe02f2e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":284},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "f7450695462a481ea1954bf2de2364c6":{
      "scriptId":"u0"},
    "12bebe2376d149b9b1d99c9c3047285d":{
      "scriptId":"u1"},
    "632c9327e02d425fb155974a5473539a":{
      "scriptId":"u2"},
    "8e8eac7621c54c348d5d56115abf4e26":{
      "scriptId":"u3"},
    "e9c00710a595442f9cc317385429409c":{
      "scriptId":"u4"},
    "89d6e3e5c7b7456496a87f4a8265b972":{
      "scriptId":"u5"},
    "db4dad545ca54984b66ea0a2ce5b51cd":{
      "scriptId":"u6"},
    "4a97ecec5f41432f87bf186f55be9056":{
      "scriptId":"u7"},
    "f22491ed8b884e6cb376fef5c337a385":{
      "scriptId":"u8"},
    "6f34597ed49c4b22a31c9bcc7f09fee5":{
      "scriptId":"u9"},
    "3c9fc9ffc5194f4da532ebb0486da21c":{
      "scriptId":"u10"},
    "5a0d10d57eb44006bc48e72f86ce95f9":{
      "scriptId":"u11"},
    "d95d2f78d97e43889cfa9d257b9318ad":{
      "scriptId":"u12"},
    "e77ea752ec6b4cae9e6a4742635d6d79":{
      "scriptId":"u13"},
    "f0c0e2effdb641409ec77f5de540b371":{
      "scriptId":"u14"},
    "da050772d07f4083a400b51612bc2afb":{
      "scriptId":"u15"},
    "ff42416ae5d947768153f3d5ee12231d":{
      "scriptId":"u16"},
    "197004cca2774d3fba18a71f5620439e":{
      "scriptId":"u17"},
    "8b0480d342764c2ebaf53bd1a36ae321":{
      "scriptId":"u18"},
    "090abd31952d4d12aa68f9ebdc7e0150":{
      "scriptId":"u19"},
    "933d1d81e85c4748aa2b63aa6fc6a6d4":{
      "scriptId":"u20"},
    "272bc7d0c9d04d52bcbccbf83bcf21b7":{
      "scriptId":"u21"},
    "e954bea160fa4e24ac1bfe125ef07e7e":{
      "scriptId":"u22"},
    "04e18ab11f27423fa8d96198891274c5":{
      "scriptId":"u23"},
    "fad9bcde6b8d46d0a49e37daf2928925":{
      "scriptId":"u24"},
    "dc5f8b9ce2bf4cb1b02025b4ae3cc172":{
      "scriptId":"u25"},
    "736e256004a34e939fe4b3d00487f389":{
      "scriptId":"u26"},
    "5815019bdcca41d083c18aa4547179c4":{
      "scriptId":"u27"},
    "2d01aa23015949dcba0b7a61d3336794":{
      "scriptId":"u28"},
    "eda0554efac94f18ba60d48c7a66f862":{
      "scriptId":"u29"},
    "39e4be42b6e04ceabe181bd0001d2efd":{
      "scriptId":"u30"},
    "322a584694ea4b7480ec2dd587e20f59":{
      "scriptId":"u31"},
    "d26e0e6c28594fd39f7c7c18b145e32c":{
      "scriptId":"u32"},
    "648caa1c0018439b9f7d95ced79cc1c7":{
      "scriptId":"u33"},
    "76f2954230cc46c9a47c7242c0e632f1":{
      "scriptId":"u34"},
    "357f2afcb4fa42cab6c097aa9a7b2563":{
      "scriptId":"u35"},
    "b5ba362bee8f4e38828b2f806be950e6":{
      "scriptId":"u36"},
    "41e3f7791a4b4feb8d51893b2325f0c1":{
      "scriptId":"u37"},
    "e947df06cad045529526b4b2c49ea0e8":{
      "scriptId":"u38"},
    "1112ce3bd3a447b0a014f9ee2ec3995a":{
      "scriptId":"u39"},
    "4a3ea325888f45d990f9077c36c253d9":{
      "scriptId":"u40"},
    "22e20006784f4662bbb84596da1e32a6":{
      "scriptId":"u41"},
    "2c7583fc840044f3a7d494b409e4b629":{
      "scriptId":"u42"},
    "5d84c38542af4b0399f0f8660d027e08":{
      "scriptId":"u43"},
    "24449a24e56742579750531dc4889be2":{
      "scriptId":"u44"},
    "71526b9f33554bd3850a6eb2d58db773":{
      "scriptId":"u45"},
    "b56720dcc96d44239622724e697aa6de":{
      "scriptId":"u46"},
    "bdc7a05996844623a2c24c99c8183499":{
      "scriptId":"u47"},
    "2ccb23f5b59247179e998125844a9a4b":{
      "scriptId":"u48"},
    "a235284aaaa6420497823c32f1d0135a":{
      "scriptId":"u49"},
    "bfd314bbc12e4555ac2a9e443bc1fe80":{
      "scriptId":"u50"},
    "a6c61a44913e44e49cfdbf1eed220b16":{
      "scriptId":"u51"},
    "9ccdfe9fc6964397a826a23828f258ae":{
      "scriptId":"u52"},
    "96f704be54224f49a235491e10245e07":{
      "scriptId":"u53"},
    "a79eeed0be4c464ca04417e0fbe7fbd3":{
      "scriptId":"u54"},
    "7318f0f000814e268ed0b33a1e70a026":{
      "scriptId":"u55"},
    "9daa4ee68d284c6b8190ca00859ce9a1":{
      "scriptId":"u56"},
    "b669260d26714a96bc40d2c1cfe02f2e":{
      "scriptId":"u57"}}});