$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1428320974599.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"670da8cb16db417f8954718c0db1c532",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55b0d24fc7144457ba9cfa20db3d4bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":58,
              "y":20},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4686c1d162e64ce7b567ce8756f5ac14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":58,
                  "y":20},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94418486dadd4ab89b61228f1bd49a1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":80},
            "size":{
              "width":840,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u2_line.png"}},
{
          "id":"793d4306d9b8482287248d71007f17ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":58,
              "y":130},
            "size":{
              "width":53,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f986cb040cb648dd9e411b980090b8e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":58,
                  "y":130},
                "size":{
                  "width":53,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a74488c9c87b44659efb69235d8ecf75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":140},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c77670783d4e1eaa288a0e5053d095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":140},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"ef0992541ab34ccb84e232e9d4e2da72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":190},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d388e43c6a047edb6f73d3fd261e0e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":190},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"0735d49021a64d7181c6befa5f151c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":240},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e0ed9f60a747f5bef5a217ea01daf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":240},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"dde798b9f70b4319959861c3b874e485",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":290},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a88ec217a87945bf9bf6b0623eb6e519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":290},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"fe9d1188aefe415d868a84502ed5468d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":262,
              "y":290},
            "size":{
              "width":68,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a0c499ef6b43e19352a778d94b7a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":262,
                  "y":290},
                "size":{
                  "width":68,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u13.png"}},
{
          "id":"f9b72e8f820b4f3da26fa2532154f913",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":130,
              "y":360},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8909866bfe7475698643896ab746180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":130,
                  "y":360},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "55b0d24fc7144457ba9cfa20db3d4bb0":{
      "scriptId":"u0"},
    "4686c1d162e64ce7b567ce8756f5ac14":{
      "scriptId":"u1"},
    "94418486dadd4ab89b61228f1bd49a1c":{
      "scriptId":"u2"},
    "793d4306d9b8482287248d71007f17ea":{
      "scriptId":"u3"},
    "f986cb040cb648dd9e411b980090b8e1":{
      "scriptId":"u4"},
    "a74488c9c87b44659efb69235d8ecf75":{
      "scriptId":"u5"},
    "60c77670783d4e1eaa288a0e5053d095":{
      "scriptId":"u6"},
    "ef0992541ab34ccb84e232e9d4e2da72":{
      "scriptId":"u7"},
    "6d388e43c6a047edb6f73d3fd261e0e3":{
      "scriptId":"u8"},
    "0735d49021a64d7181c6befa5f151c9b":{
      "scriptId":"u9"},
    "07e0ed9f60a747f5bef5a217ea01daf3":{
      "scriptId":"u10"},
    "dde798b9f70b4319959861c3b874e485":{
      "scriptId":"u11"},
    "a88ec217a87945bf9bf6b0623eb6e519":{
      "scriptId":"u12"},
    "fe9d1188aefe415d868a84502ed5468d":{
      "scriptId":"u13"},
    "f4a0c499ef6b43e19352a778d94b7a29":{
      "scriptId":"u14"},
    "f9b72e8f820b4f3da26fa2532154f913":{
      "scriptId":"u15"},
    "c8909866bfe7475698643896ab746180":{
      "scriptId":"u16"}}});