$axure.loadCurrentPage({
  "url":"会员管理.html",
  "generationDate":new Date(1428320976748.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5d35c055b69e4b1b82e4386e66d3bf23",
    "type":"Axure:Page",
    "name":"会员管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c16ce5e2b157429ea8c93371f3421823",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a86c3ab49e34aa484d09fd6bce27410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32e7fa18dbe74fce86f1c1c1d7bc78da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"51656b8005a249e280305d8912e00990",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":722,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d90540c2c0e449379cc76ecda99d9acd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa146e52fa4743d8a993a0c3ad99eeeb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"a3e0aeaa1ab14d5ebebd679abc7535d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fc43cad51c04184beff92481fcdb8b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"822ee4346bf14c91a9ccb10b09ce9e6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44c4b35973994824809d31abb097641f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"4f9632442b104fa2a9560ae3a6580c2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cbeb23f0dddc43579e2e798fd4989db9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":344,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"65a93d18a4e84d4088de8807894be585",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0bf2bf0f28b0483ea30b62dca0d9bcaa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":344,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"c9c2c03e3ac448c784e84fc3111595fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb13e7182e224ea992fe9073e613d63e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":344,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"03da703bab3241dcba4b3285a6f7a1b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ad912158210466cbb2f4ddb634e76a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"10237ec9eca74cf5a1f1e61d44ea1db9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":90},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12bac888f7684c8db6b9ca1fd38e6ab9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":344,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"88426e20784949f5a6f937a780922fb3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c44723b531145c98ca601c7b373652a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u30.png"}},
{
              "id":"1660ba773d694b388aec9b1757571a76",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":344,
                  "y":120},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8c06f7ac0524154bc76b911af4709a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":344,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"c1292ba1598d43958273394788803881",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":0},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"462a2e2b396f45178be72ff5a8c4a241",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":0},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u10.png"}},
{
              "id":"dd86c361afad4858815e2d2e49bb913f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":30},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e76e994338ea44fa8a1d076e9fd37ea3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":30},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u10.png"}},
{
              "id":"ef1fb29212b9422d988ac65fe94a6087",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":60},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e554e4119a2f4d9483919920a462568a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":60},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u10.png"}},
{
              "id":"0cbe8c0e2de441428ac501e45b00385d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":90},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"241a2be78ac742a5b5e258cecdeb0955",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":90},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u10.png"}},
{
              "id":"17b579bcffeb41a6bb9b3d597304d9e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":444,
                  "y":120},
                "size":{
                  "width":133,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46a617ea1e4d483a8b0eacd4999a01ff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":444,
                      "y":120},
                    "size":{
                      "width":133,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u50.png"}},
{
              "id":"8f31f4d3eb994c678d4f5cc7dd38f294",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":577,
                  "y":0},
                "size":{
                  "width":145,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00722192570e4c0da3f6f427894a5a5e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":577,
                      "y":0},
                    "size":{
                      "width":145,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u12.png"}},
{
              "id":"9948e674a8f4429d97fbac3594c7816d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":30},
                "size":{
                  "width":145,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7dd090f4ae484dfbae785226e56a5be8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":577,
                      "y":30},
                    "size":{
                      "width":145,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u12.png"}},
{
              "id":"905676c9de7342a788191924bd59d255",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":60},
                "size":{
                  "width":145,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a04054cbe5ed4115adf1a014369a686c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":577,
                      "y":60},
                    "size":{
                      "width":145,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u12.png"}},
{
              "id":"cfa5c40e25ed4ad3a6b38352b925788a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":90},
                "size":{
                  "width":145,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40e35365dda649428499b7a8bba2c8e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":577,
                      "y":90},
                    "size":{
                      "width":145,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u12.png"}},
{
              "id":"a59f65716db5457684a547b5ddff3bf1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":577,
                  "y":120},
                "size":{
                  "width":145,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5019ba1f8944e27849e24ba52d55ad9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":577,
                      "y":120},
                    "size":{
                      "width":145,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u52.png"}},
{
              "id":"c47139ec8e824fc29215caa9a438c8b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":144,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62bed9a93b9443eb9ec289ae609ef7d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":144,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u6.png"}},
{
              "id":"efc13ac51d5c48c0a1922d41220e23f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":144,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16ecbb6a1a1a4500b656313150aeab89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":144,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u6.png"}},
{
              "id":"07517cbf8261486aa21109f3c5f65029",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":144,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38ab42f1335a497493a679057249678b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":144,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u6.png"}},
{
              "id":"86200bbe54bc49f4bd62f112645ec9a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":144,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8347bf35f317402c8c2a6f1b290622ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":200,
                      "y":90},
                    "size":{
                      "width":144,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u6.png"}},
{
              "id":"d27dbf6a693f4b44b8527e72f78abdd3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":144,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c350c0b7e6184bbaae24ce4fa45bd0eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":144,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u46.png"}}]},
{
          "id":"029a778c333e49bbb8e185e60e53a604",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":193},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aa9200ecaa8a4ac5a39cf26fcb046536",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":225},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1ea168a6b2b34f18aaaac7c7e24de308",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":255},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d906c3dcb71b4210a5c45389116419e1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":286},
            "size":{
              "width":100,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c16ce5e2b157429ea8c93371f3421823":{
      "scriptId":"u0"},
    "3a86c3ab49e34aa484d09fd6bce27410":{
      "scriptId":"u1"},
    "32e7fa18dbe74fce86f1c1c1d7bc78da":{
      "scriptId":"u2"},
    "51656b8005a249e280305d8912e00990":{
      "scriptId":"u3"},
    "d90540c2c0e449379cc76ecda99d9acd":{
      "scriptId":"u4"},
    "fa146e52fa4743d8a993a0c3ad99eeeb":{
      "scriptId":"u5"},
    "c47139ec8e824fc29215caa9a438c8b8":{
      "scriptId":"u6"},
    "62bed9a93b9443eb9ec289ae609ef7d6":{
      "scriptId":"u7"},
    "4f9632442b104fa2a9560ae3a6580c2a":{
      "scriptId":"u8"},
    "cbeb23f0dddc43579e2e798fd4989db9":{
      "scriptId":"u9"},
    "c1292ba1598d43958273394788803881":{
      "scriptId":"u10"},
    "462a2e2b396f45178be72ff5a8c4a241":{
      "scriptId":"u11"},
    "8f31f4d3eb994c678d4f5cc7dd38f294":{
      "scriptId":"u12"},
    "00722192570e4c0da3f6f427894a5a5e":{
      "scriptId":"u13"},
    "a3e0aeaa1ab14d5ebebd679abc7535d0":{
      "scriptId":"u14"},
    "7fc43cad51c04184beff92481fcdb8b8":{
      "scriptId":"u15"},
    "efc13ac51d5c48c0a1922d41220e23f9":{
      "scriptId":"u16"},
    "16ecbb6a1a1a4500b656313150aeab89":{
      "scriptId":"u17"},
    "65a93d18a4e84d4088de8807894be585":{
      "scriptId":"u18"},
    "0bf2bf0f28b0483ea30b62dca0d9bcaa":{
      "scriptId":"u19"},
    "dd86c361afad4858815e2d2e49bb913f":{
      "scriptId":"u20"},
    "e76e994338ea44fa8a1d076e9fd37ea3":{
      "scriptId":"u21"},
    "9948e674a8f4429d97fbac3594c7816d":{
      "scriptId":"u22"},
    "7dd090f4ae484dfbae785226e56a5be8":{
      "scriptId":"u23"},
    "822ee4346bf14c91a9ccb10b09ce9e6c":{
      "scriptId":"u24"},
    "44c4b35973994824809d31abb097641f":{
      "scriptId":"u25"},
    "07517cbf8261486aa21109f3c5f65029":{
      "scriptId":"u26"},
    "38ab42f1335a497493a679057249678b":{
      "scriptId":"u27"},
    "c9c2c03e3ac448c784e84fc3111595fa":{
      "scriptId":"u28"},
    "eb13e7182e224ea992fe9073e613d63e":{
      "scriptId":"u29"},
    "ef1fb29212b9422d988ac65fe94a6087":{
      "scriptId":"u30"},
    "e554e4119a2f4d9483919920a462568a":{
      "scriptId":"u31"},
    "905676c9de7342a788191924bd59d255":{
      "scriptId":"u32"},
    "a04054cbe5ed4115adf1a014369a686c":{
      "scriptId":"u33"},
    "03da703bab3241dcba4b3285a6f7a1b5":{
      "scriptId":"u34"},
    "7ad912158210466cbb2f4ddb634e76a0":{
      "scriptId":"u35"},
    "86200bbe54bc49f4bd62f112645ec9a5":{
      "scriptId":"u36"},
    "8347bf35f317402c8c2a6f1b290622ed":{
      "scriptId":"u37"},
    "10237ec9eca74cf5a1f1e61d44ea1db9":{
      "scriptId":"u38"},
    "12bac888f7684c8db6b9ca1fd38e6ab9":{
      "scriptId":"u39"},
    "0cbe8c0e2de441428ac501e45b00385d":{
      "scriptId":"u40"},
    "241a2be78ac742a5b5e258cecdeb0955":{
      "scriptId":"u41"},
    "cfa5c40e25ed4ad3a6b38352b925788a":{
      "scriptId":"u42"},
    "40e35365dda649428499b7a8bba2c8e2":{
      "scriptId":"u43"},
    "88426e20784949f5a6f937a780922fb3":{
      "scriptId":"u44"},
    "2c44723b531145c98ca601c7b373652a":{
      "scriptId":"u45"},
    "d27dbf6a693f4b44b8527e72f78abdd3":{
      "scriptId":"u46"},
    "c350c0b7e6184bbaae24ce4fa45bd0eb":{
      "scriptId":"u47"},
    "1660ba773d694b388aec9b1757571a76":{
      "scriptId":"u48"},
    "a8c06f7ac0524154bc76b911af4709a9":{
      "scriptId":"u49"},
    "17b579bcffeb41a6bb9b3d597304d9e6":{
      "scriptId":"u50"},
    "46a617ea1e4d483a8b0eacd4999a01ff":{
      "scriptId":"u51"},
    "a59f65716db5457684a547b5ddff3bf1":{
      "scriptId":"u52"},
    "b5019ba1f8944e27849e24ba52d55ad9":{
      "scriptId":"u53"},
    "029a778c333e49bbb8e185e60e53a604":{
      "scriptId":"u54"},
    "aa9200ecaa8a4ac5a39cf26fcb046536":{
      "scriptId":"u55"},
    "1ea168a6b2b34f18aaaac7c7e24de308":{
      "scriptId":"u56"},
    "d906c3dcb71b4210a5c45389116419e1":{
      "scriptId":"u57"}}});