$axure.loadCurrentPage({
  "url":"线路管理.html",
  "generationDate":new Date(1427610287910.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2d2ab940c30e4d11979f4e3e82610236",
    "type":"Axure:Page",
    "name":"线路管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"240295a8ecc242229e9c80842689523c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":78,
              "y":30},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9002bc6e1734c6da352a8fc33c429f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":78,
                  "y":30},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec054e2622334f57a885e5879c52905d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":78,
              "y":240},
            "size":{
              "width":70,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a03b1ee8f6fa4433af5a5e903cc68954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":78,
                  "y":240},
                "size":{
                  "width":70,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的运单/u19.png"}},
{
          "id":"5c78d463b48d48969df51d90fbd9802c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":115},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eca366aae404977a06793fcd62184c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":115},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5207733277e141b0b6a38a959f1a744c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":194},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"749fbc2353f0436bbd68aa110b4fb889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":194},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbc73a932dfb404fb67e29d86c529e90",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":109},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d7d64bf367f24e84934efab0626f9ec5",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":109},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"23b491f3cddb4c80aeb09f9ed44e00bc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":109},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"42744ed4761c4e3385e2af2436d08714",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":154},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9bf420093b4a92bfe701a16564b009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":154},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44a9f01ce8034124a75ee7862a314fc6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":148},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7379a2e3ad1348adad639702ce239d07",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":148},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f273086f59034d8cbd38e8c0b4f3b8c8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":148},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"6b34e43f96f0403f8cf0583aa9135020",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":188},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c8f997261647435192b8815e8b3ad521",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":290},
            "size":{
              "width":550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/线路管理/u17_line.png"}},
{
          "id":"029d860f57bb4ca28054e786c31da466",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":73},
            "size":{
              "width":550,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/线路管理/u17_line.png"}},
{
          "id":"22cc85df340548ae8911014e12eef608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":540,
              "y":30},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ca6f614b364ab3afbd0fb141bb58b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":540,
                  "y":30},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/线路管理/u19.png"}},
{
          "id":"4488b3dbf0464196b76ef79ae7bf5005",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":340},
            "size":{
              "width":804,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97fa0680233c4317a0c074dd40b1abe6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":120,
                  "y":0},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4395c29c2eb74a38989be64f63cfb6cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":120,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u24.png"}},
{
              "id":"9a14b15b89154210ab39a8d5854f39a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":40},
                "size":{
                  "width":200,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3365095b084d47ce9bc2d1414ccc92e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":40},
                    "size":{
                      "width":200,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u36.png"}},
{
              "id":"774806d4605241c58415200c2e642b24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":120,
                  "y":108},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a146997bbd9407cbbc881fd0177d263",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":120,
                      "y":108},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u48.png"}},
{
              "id":"0e4bd35f3ff74ff5b2c7675aa5661312",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":320,
                  "y":0},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60c38f4e67794d24a1797dd0bff5cc5e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u7.png"}},
{
              "id":"b2765c1d46564a3989f3d73714bf0a67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":320,
                  "y":40},
                "size":{
                  "width":100,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c70668b5e99b47db9b05c46528a68e00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":320,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路/u19.png"}},
{
              "id":"628204269a3e48d298677c6e15a0bad7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":320,
                  "y":108},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"767f2b95b27341c4b73832035726e796",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":320,
                      "y":108},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查找列表/u23.png"}},
{
              "id":"468fd87a8fd74993bc61313c0e062652",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":420,
                  "y":0},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"587c807adfca4d4d8c61f81d9c9a13aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u3.png"}},
{
              "id":"9b2b5046c7d74754ac73f88929cc7965",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":420,
                  "y":40},
                "size":{
                  "width":150,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2da634b7a244deca7d7a7d4016e8ec7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":420,
                      "y":40},
                    "size":{
                      "width":150,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u11.png"}},
{
              "id":"e724d0b2534e4d538bf04d24d392501c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":420,
                  "y":108},
                "size":{
                  "width":150,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40ba6c9c522b4b3cb435107d9f2b6848",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":420,
                      "y":108},
                    "size":{
                      "width":150,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查找列表/u25.png"}},
{
              "id":"0b3943445afa4f768c901d4864482288",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":704,
                  "y":0},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b36352cb98a7497ca526ecff5ee3156e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":704,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u32.png"}},
{
              "id":"dd841b8ded1f4ee08e95e9e7451af9f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":704,
                  "y":40},
                "size":{
                  "width":100,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e15cb0b7f7744af985bae047e4dbaf8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":704,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u44.png"}},
{
              "id":"85ee0cc79f8c4cf5a2d3d22267e69f88",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":704,
                  "y":108},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa923d09303f4cf981c532ce46ad2e1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":704,
                      "y":108},
                    "size":{
                      "width":100,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u56.png"}},
{
              "id":"05b5738292054d758f5d6e0b1806de25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79e5d945e8064c95a0f4c5b2c0c9fe75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":120,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u22.png"}},
{
              "id":"6d7985535a4141d2ba95d6e4f68ad9be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":120,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35c14d48113749389256b864a14652bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":120,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u34.png"}},
{
              "id":"0c48be58394040b0bcd5b3c575654e43",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":108},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e2af3e99bef4efe9a9f52bfabe74b92",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":108},
                    "size":{
                      "width":120,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/线路管理/u46.png"}},
{
              "id":"ba0b557f0e8d40e0a55d55148ad12d41",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":570,
                  "y":0},
                "size":{
                  "width":134,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0edd432ecc69454daec60cf502dbb88a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "location":{
                      "x":570,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u5.png"}},
{
              "id":"d4cb619f0f274fd3a54b088994ccdb62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":40},
                "size":{
                  "width":134,
                  "height":68}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c25f850627544759340eb96fedaf7c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":40},
                    "size":{
                      "width":134,
                      "height":68}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u13.png"}},
{
              "id":"bc409e4c5879497b953aafdbb9af1428",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":570,
                  "y":108},
                "size":{
                  "width":134,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71a06410cf374f1495e8a91a4456ae62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":570,
                      "y":108},
                    "size":{
                      "width":134,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/网点介绍/u21.png"}}]},
{
          "id":"256b3e367e7b46c9b8ee08c86869a90a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":347},
            "size":{
              "width":70,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7f6cd071d44243f683cfb96ffd2c7614",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":402},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777119f8c86f4ed89358f4383b117a90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":402},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"aa41e40759a84232907862f53badc653",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":460},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be542b9a57c84f7c90b39135ee876725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":460},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "240295a8ecc242229e9c80842689523c":{
      "scriptId":"u0"},
    "c9002bc6e1734c6da352a8fc33c429f7":{
      "scriptId":"u1"},
    "ec054e2622334f57a885e5879c52905d":{
      "scriptId":"u2"},
    "a03b1ee8f6fa4433af5a5e903cc68954":{
      "scriptId":"u3"},
    "5c78d463b48d48969df51d90fbd9802c":{
      "scriptId":"u4"},
    "5eca366aae404977a06793fcd62184c2":{
      "scriptId":"u5"},
    "5207733277e141b0b6a38a959f1a744c":{
      "scriptId":"u6"},
    "749fbc2353f0436bbd68aa110b4fb889":{
      "scriptId":"u7"},
    "bbc73a932dfb404fb67e29d86c529e90":{
      "scriptId":"u8"},
    "d7d64bf367f24e84934efab0626f9ec5":{
      "scriptId":"u9"},
    "23b491f3cddb4c80aeb09f9ed44e00bc":{
      "scriptId":"u10"},
    "42744ed4761c4e3385e2af2436d08714":{
      "scriptId":"u11"},
    "2c9bf420093b4a92bfe701a16564b009":{
      "scriptId":"u12"},
    "44a9f01ce8034124a75ee7862a314fc6":{
      "scriptId":"u13"},
    "7379a2e3ad1348adad639702ce239d07":{
      "scriptId":"u14"},
    "f273086f59034d8cbd38e8c0b4f3b8c8":{
      "scriptId":"u15"},
    "6b34e43f96f0403f8cf0583aa9135020":{
      "scriptId":"u16"},
    "c8f997261647435192b8815e8b3ad521":{
      "scriptId":"u17"},
    "029d860f57bb4ca28054e786c31da466":{
      "scriptId":"u18"},
    "22cc85df340548ae8911014e12eef608":{
      "scriptId":"u19"},
    "d2ca6f614b364ab3afbd0fb141bb58b2":{
      "scriptId":"u20"},
    "4488b3dbf0464196b76ef79ae7bf5005":{
      "scriptId":"u21"},
    "05b5738292054d758f5d6e0b1806de25":{
      "scriptId":"u22"},
    "79e5d945e8064c95a0f4c5b2c0c9fe75":{
      "scriptId":"u23"},
    "97fa0680233c4317a0c074dd40b1abe6":{
      "scriptId":"u24"},
    "4395c29c2eb74a38989be64f63cfb6cc":{
      "scriptId":"u25"},
    "0e4bd35f3ff74ff5b2c7675aa5661312":{
      "scriptId":"u26"},
    "60c38f4e67794d24a1797dd0bff5cc5e":{
      "scriptId":"u27"},
    "468fd87a8fd74993bc61313c0e062652":{
      "scriptId":"u28"},
    "587c807adfca4d4d8c61f81d9c9a13aa":{
      "scriptId":"u29"},
    "ba0b557f0e8d40e0a55d55148ad12d41":{
      "scriptId":"u30"},
    "0edd432ecc69454daec60cf502dbb88a":{
      "scriptId":"u31"},
    "0b3943445afa4f768c901d4864482288":{
      "scriptId":"u32"},
    "b36352cb98a7497ca526ecff5ee3156e":{
      "scriptId":"u33"},
    "6d7985535a4141d2ba95d6e4f68ad9be":{
      "scriptId":"u34"},
    "35c14d48113749389256b864a14652bf":{
      "scriptId":"u35"},
    "9a14b15b89154210ab39a8d5854f39a9":{
      "scriptId":"u36"},
    "3365095b084d47ce9bc2d1414ccc92e7":{
      "scriptId":"u37"},
    "b2765c1d46564a3989f3d73714bf0a67":{
      "scriptId":"u38"},
    "c70668b5e99b47db9b05c46528a68e00":{
      "scriptId":"u39"},
    "9b2b5046c7d74754ac73f88929cc7965":{
      "scriptId":"u40"},
    "f2da634b7a244deca7d7a7d4016e8ec7":{
      "scriptId":"u41"},
    "d4cb619f0f274fd3a54b088994ccdb62":{
      "scriptId":"u42"},
    "0c25f850627544759340eb96fedaf7c5":{
      "scriptId":"u43"},
    "dd841b8ded1f4ee08e95e9e7451af9f0":{
      "scriptId":"u44"},
    "e15cb0b7f7744af985bae047e4dbaf8c":{
      "scriptId":"u45"},
    "0c48be58394040b0bcd5b3c575654e43":{
      "scriptId":"u46"},
    "3e2af3e99bef4efe9a9f52bfabe74b92":{
      "scriptId":"u47"},
    "774806d4605241c58415200c2e642b24":{
      "scriptId":"u48"},
    "5a146997bbd9407cbbc881fd0177d263":{
      "scriptId":"u49"},
    "628204269a3e48d298677c6e15a0bad7":{
      "scriptId":"u50"},
    "767f2b95b27341c4b73832035726e796":{
      "scriptId":"u51"},
    "e724d0b2534e4d538bf04d24d392501c":{
      "scriptId":"u52"},
    "40ba6c9c522b4b3cb435107d9f2b6848":{
      "scriptId":"u53"},
    "bc409e4c5879497b953aafdbb9af1428":{
      "scriptId":"u54"},
    "71a06410cf374f1495e8a91a4456ae62":{
      "scriptId":"u55"},
    "85ee0cc79f8c4cf5a2d3d22267e69f88":{
      "scriptId":"u56"},
    "fa923d09303f4cf981c532ce46ad2e1c":{
      "scriptId":"u57"},
    "256b3e367e7b46c9b8ee08c86869a90a":{
      "scriptId":"u58"},
    "7f6cd071d44243f683cfb96ffd2c7614":{
      "scriptId":"u59"},
    "777119f8c86f4ed89358f4383b117a90":{
      "scriptId":"u60"},
    "aa41e40759a84232907862f53badc653":{
      "scriptId":"u61"},
    "be542b9a57c84f7c90b39135ee876725":{
      "scriptId":"u62"}}});