$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1428320975939.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d5dfb136ea354a9797e87cc57f2244af",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"88e7f83aa4b54f518ef41446cb2ea172",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":40},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da58a3a6bf742a3b3121a9d5517803b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":40},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0230bd0aa1ea4653b99351a8a82508e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":124},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c24c9c193368414281ced31a6c9fc333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":124},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b225f91655f64cde8679868cccbb19ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":150},
            "size":{
              "width":362,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a10bd1b86dc4a6ea7a2d21f887bdb43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":150},
                "size":{
                  "width":362,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u4.png"}},
{
          "id":"a776cbae599e4454852b87d9725020d3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":330},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "88e7f83aa4b54f518ef41446cb2ea172":{
      "scriptId":"u0"},
    "9da58a3a6bf742a3b3121a9d5517803b":{
      "scriptId":"u1"},
    "0230bd0aa1ea4653b99351a8a82508e1":{
      "scriptId":"u2"},
    "c24c9c193368414281ced31a6c9fc333":{
      "scriptId":"u3"},
    "b225f91655f64cde8679868cccbb19ee":{
      "scriptId":"u4"},
    "6a10bd1b86dc4a6ea7a2d21f887bdb43":{
      "scriptId":"u5"},
    "a776cbae599e4454852b87d9725020d3":{
      "scriptId":"u6"}}});