$axure.loadCurrentPage({
  "url":"物流园录入.html",
  "generationDate":new Date(1428320978890.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f9103a70d074ed0919237c1a1f8629f",
    "type":"Axure:Page",
    "name":"物流园录入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd7c4cc35f6646d78e7614bc5118101a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":66},
            "size":{
              "width":141,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ead96818df1493486c415b8f327bac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":66},
                "size":{
                  "width":141,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62d56086ac6140aa88c6136fb44f838f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":740,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/基本信息/u4_line.png"}},
{
          "id":"df6f99bd67ac42c88f813bb8ed037525",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":170},
            "size":{
              "width":714,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f86e315de13840bab0c94aea9bd05a34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"73864fc09c9041f2ae772fba933b00cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流园录入/u6.png"}},
{
              "id":"da926ca114d349678b34cd264d58ad90",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0afc689583b742cf9777a4d0ef7e92d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/会员管理/u4.png"}},
{
              "id":"3a438f1ac3a247a694b5f3ea327365b9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":523,
                  "y":0},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"44d87f46d06743bbacd81a3bcb71507a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":523,
                      "y":0},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u8.png"}},
{
              "id":"d8b551e2ffbc4897932add7e04193432",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":523,
                  "y":30},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cd4eac94ee3c425a83fe6531f0018d4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":523,
                      "y":30},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u12.png"}},
{
              "id":"9131efa5c0354588849563c99730be26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b702bb094b540d18f832bb09594a07b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/收货地址/u30.png"}},
{
              "id":"91868b145b5242feb9ac673936230115",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":523,
                  "y":60},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7fc25a6bacef46cfb7719b94fe9693a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":523,
                      "y":60},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台基础页面管理/u16.png"}},
{
              "id":"958924257df141339154c12f8336079a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8497c6fefa8e4d80a2c05d338ce5a3d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/意见反馈管理/u4.png"}},
{
              "id":"a358d36de09a474884d2df966e4b98a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ebc5a2120cc402989e7551f9c6e1822",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u24.png"}},
{
              "id":"bf6186e157c44a9ca8a5bb0eb1eae6fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f86c1cf4ff84a57af2121e1a1d6c0a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加线路/u28.png"}},
{
              "id":"06902328826a49b7b59118fc68ffd7c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":223,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f88767536838421a8622f3c585c49484",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":223,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流园录入/u8.png"}},
{
              "id":"6d60fc3adea14ae8b4fa24fbdc689cd1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":223,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96df5a7af7a849dba96b8f4c679db343",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":223,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流园录入/u16.png"}},
{
              "id":"f7a4127ea21a44018571a86043d73a53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":223,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32e342ec514c4b5db6f7a97356d85b69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":223,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/物流园录入/u24.png"}}]},
{
          "id":"7641299979934e8cafb78888fec940ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF006699},
            "location":{
              "x":690,
              "y":73},
            "size":{
              "width":90,
              "height":26},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9663d8df794421c81949c9b2e1f3978",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF006699},
                "location":{
                  "x":690,
                  "y":73},
                "size":{
                  "width":90,
                  "height":26},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的线路/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fd7c4cc35f6646d78e7614bc5118101a":{
      "scriptId":"u0"},
    "8ead96818df1493486c415b8f327bac6":{
      "scriptId":"u1"},
    "62d56086ac6140aa88c6136fb44f838f":{
      "scriptId":"u2"},
    "df6f99bd67ac42c88f813bb8ed037525":{
      "scriptId":"u3"},
    "958924257df141339154c12f8336079a":{
      "scriptId":"u4"},
    "8497c6fefa8e4d80a2c05d338ce5a3d0":{
      "scriptId":"u5"},
    "f86e315de13840bab0c94aea9bd05a34":{
      "scriptId":"u6"},
    "73864fc09c9041f2ae772fba933b00cd":{
      "scriptId":"u7"},
    "06902328826a49b7b59118fc68ffd7c2":{
      "scriptId":"u8"},
    "f88767536838421a8622f3c585c49484":{
      "scriptId":"u9"},
    "3a438f1ac3a247a694b5f3ea327365b9":{
      "scriptId":"u10"},
    "44d87f46d06743bbacd81a3bcb71507a":{
      "scriptId":"u11"},
    "a358d36de09a474884d2df966e4b98a8":{
      "scriptId":"u12"},
    "1ebc5a2120cc402989e7551f9c6e1822":{
      "scriptId":"u13"},
    "da926ca114d349678b34cd264d58ad90":{
      "scriptId":"u14"},
    "0afc689583b742cf9777a4d0ef7e92d0":{
      "scriptId":"u15"},
    "6d60fc3adea14ae8b4fa24fbdc689cd1":{
      "scriptId":"u16"},
    "96df5a7af7a849dba96b8f4c679db343":{
      "scriptId":"u17"},
    "d8b551e2ffbc4897932add7e04193432":{
      "scriptId":"u18"},
    "cd4eac94ee3c425a83fe6531f0018d4b":{
      "scriptId":"u19"},
    "bf6186e157c44a9ca8a5bb0eb1eae6fe":{
      "scriptId":"u20"},
    "5f86c1cf4ff84a57af2121e1a1d6c0a3":{
      "scriptId":"u21"},
    "9131efa5c0354588849563c99730be26":{
      "scriptId":"u22"},
    "0b702bb094b540d18f832bb09594a07b":{
      "scriptId":"u23"},
    "f7a4127ea21a44018571a86043d73a53":{
      "scriptId":"u24"},
    "32e342ec514c4b5db6f7a97356d85b69":{
      "scriptId":"u25"},
    "91868b145b5242feb9ac673936230115":{
      "scriptId":"u26"},
    "7fc25a6bacef46cfb7719b94fe9693a0":{
      "scriptId":"u27"},
    "7641299979934e8cafb78888fec940ce":{
      "scriptId":"u28"},
    "f9663d8df794421c81949c9b2e1f3978":{
      "scriptId":"u29"}}});