$axure.loadCurrentPage({
  "url":"忘记密码.html",
  "generationDate":new Date(1428320974644.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8d7143e3de35434aba52783f5a908109",
    "type":"Axure:Page",
    "name":"忘记密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4f45d0be0fc14539844c5af88b0acb45",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":58,
              "y":20},
            "size":{
              "width":113,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9e1a87d70e4bf6b2b0a9c39b19d91d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":58,
                  "y":20},
                "size":{
                  "width":113,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f31b440b14f49868ccfcc574bfede26",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":80},
            "size":{
              "width":840,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF777777}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u2_line.png"}},
{
          "id":"a4ee749c0b7d43c48190ecd8b0eeb103",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":58,
              "y":130},
            "size":{
              "width":66,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62309c386d1d40688c8ef3cffeece7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":58,
                  "y":130},
                "size":{
                  "width":66,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc12d9905fe489a8e4b254d85eaea3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":140},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8966e04cc0aa47608a90ece11f6c7f28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":140},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"4e6a7903543f4e8598008c33b5780b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":190},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f04463f10f4c47f2a3b28cfbe91af6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":190},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"cf9e9ee3e3ba47f3858c319d038e5128",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":240},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd4d22b4f20245608b2df7859d839e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":240},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"6da0e777afb74707b471e9e808b06eb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":240},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66fb28b3f9b545ae98257aa0091dfe01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":240},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u11.png"}},
{
          "id":"e17d4ea7d7474477a681283ccc7db007",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":130,
              "y":310},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc739c75d1a0412da851c3462cca1e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":130,
                  "y":310},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}},
{
          "id":"cca4fc52e4864a5c88f1b953889751fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"48px",
            "location":{
              "x":778,
              "y":130},
            "size":{
              "width":79,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b091e8c4bdc49b8a21126125b822f70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"48px",
                "location":{
                  "x":778,
                  "y":130},
                "size":{
                  "width":79,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8d4955c65924905bfd35ff23bd5a5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":140},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f97e90a5ee446b933f547e47bfea5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":140},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"7f2fba2092784e27855dcf76b57325c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":190},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d1e95d04a774514acefeb35e503687f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":880,
                  "y":190},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u5.png"}},
{
          "id":"d454be3f4b3547de9d21a175ecd3eb27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":880,
              "y":250},
            "size":{
              "width":200,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e32a99206144f85a67a47a5113484f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF},
                "location":{
                  "x":880,
                  "y":250},
                "size":{
                  "width":200,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u15.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4f45d0be0fc14539844c5af88b0acb45":{
      "scriptId":"u0"},
    "be9e1a87d70e4bf6b2b0a9c39b19d91d":{
      "scriptId":"u1"},
    "8f31b440b14f49868ccfcc574bfede26":{
      "scriptId":"u2"},
    "a4ee749c0b7d43c48190ecd8b0eeb103":{
      "scriptId":"u3"},
    "62309c386d1d40688c8ef3cffeece7d5":{
      "scriptId":"u4"},
    "7dc12d9905fe489a8e4b254d85eaea3c":{
      "scriptId":"u5"},
    "8966e04cc0aa47608a90ece11f6c7f28":{
      "scriptId":"u6"},
    "4e6a7903543f4e8598008c33b5780b7c":{
      "scriptId":"u7"},
    "f04463f10f4c47f2a3b28cfbe91af6f5":{
      "scriptId":"u8"},
    "cf9e9ee3e3ba47f3858c319d038e5128":{
      "scriptId":"u9"},
    "fd4d22b4f20245608b2df7859d839e9d":{
      "scriptId":"u10"},
    "6da0e777afb74707b471e9e808b06eb3":{
      "scriptId":"u11"},
    "66fb28b3f9b545ae98257aa0091dfe01":{
      "scriptId":"u12"},
    "e17d4ea7d7474477a681283ccc7db007":{
      "scriptId":"u13"},
    "cc739c75d1a0412da851c3462cca1e05":{
      "scriptId":"u14"},
    "cca4fc52e4864a5c88f1b953889751fe":{
      "scriptId":"u15"},
    "4b091e8c4bdc49b8a21126125b822f70":{
      "scriptId":"u16"},
    "b8d4955c65924905bfd35ff23bd5a5a3":{
      "scriptId":"u17"},
    "61f97e90a5ee446b933f547e47bfea5f":{
      "scriptId":"u18"},
    "7f2fba2092784e27855dcf76b57325c1":{
      "scriptId":"u19"},
    "5d1e95d04a774514acefeb35e503687f":{
      "scriptId":"u20"},
    "d454be3f4b3547de9d21a175ecd3eb27":{
      "scriptId":"u21"},
    "0e32a99206144f85a67a47a5113484f9":{
      "scriptId":"u22"}}});